### ISSUE TITLE
Print Format not showing in preview

### ISSUE THREAD

**Issue by correiarmjoao** [frappe/print_designer#11]
I made a simple print format demo, everything seems to work fine.

![Screenshot 2023-06-20 at 15 17 17](https://github.com/frappe/print_designer/assets/29627639/3eceb532-45f6-4544-9b68-d04e7574602d)

When i try to preview it, it doesn't show even though its selected as the print format to use.

![Screenshot 2023-06-20 at 15 19 44](https://github.com/frappe/print_designer/assets/29627639/d31e97e6-f34e-44b5-a812-69afe42c7fa6)

I looked through the logs and I don't see any errors

**Comment by maharshivpatel** [comment]
did you ran migrations on your site ?

**Comment by correiarmjoao** [comment]
@maharshivpatel Yes I did

**Comment by correiarmjoao** [comment]
The first steps did not work, but the install on a new site worked correctly. I will do some more test but i'm closing this for now as it might be related to some changes on my side.

Thank you for your help
