### ISSUE TITLE
feat: Enable Signature field as "Dynamic Image"

### ISSUE THREAD

**Issue by batonac** [frappe/print_designer#110]
This one's pretty simple:

I have a signature field:
![image](https://github.com/frappe/print_designer/assets/4996285/4e695420-733c-4e26-8f99-6f64b358c036)

Which I need incorporated into my print format, but the dynamic image list doesn't list Signature fields:
![image](https://github.com/frappe/print_designer/assets/4996285/2636a0f1-9fbb-4901-8dca-1b9e9b4560a8)

**Comment by maharshivpatel** [comment]
@batonac if you wish to give it i would be more than happy to help you.

otherwise, i will add this in sometime.
