### ISSUE TITLE
Server Error on render if there is an empty table

### ISSUE THREAD

**Issue by SvbZ3r0** [frappe/print_designer#112]
Made a new print format and this happened:
![image](https://github.com/frappe/print_designer/assets/57280279/804c6042-0b46-4c71-b012-6498996cc139)
No error is shown and the "show error" and "home" buttons are not clickable.

**Comment by maharshivpatel** [comment]
@SvbZ3r0 delete empty table on print format 😅

**Comment by SvbZ3r0** [comment]
Ohh.. got it. Only happens when there is an empty table. Checked after deleting the table and with a filled table.
Thanks. Would be best if there's an error message telling you what is wrong though.

**Comment by maharshivpatel** [comment]
yeah, i will add a fix for this.
