### ISSUE TITLE
header don't show on visualize print

### ISSUE THREAD

**Issue by Anjos-tg** [frappe/print_designer#114]
Hello!

I have a problem.

I testing print design, but when I print, the header don't show. Has anyone had this problem?

Here I setting up the header in the print design.
![image](https://github.com/frappe/print_designer/assets/154339980/1ed0f51d-1d85-4ed0-8bd5-113a915ae766)

Here an example, the body was printed but the header isn't.
![image](https://github.com/frappe/print_designer/assets/154339980/fd2d7e5e-9a6f-4c87-be5f-4e9e58557639)

**Comment by Anjos-tg** [comment]
I checked the version, it's correct.

![image](https://github.com/frappe/print_designer/assets/154339980/4c8463c7-89bd-4aa0-9784-767a3fa5994e)

**Comment by maharshivpatel** [comment]
it should be  with patched qt

**Comment by maharshivpatel** [comment]
@Anjos-tg please follow the guide shared in the faq earlier and install version that is with patched qt

**Comment by Anjos-tg** [comment]
I do this:
wget http://mirrors.kernel.org/ubuntu/pool/main/libj/libjpeg-turbo/libjpeg-turbo8_2.1.2-0ubuntu1_amd64.deb
sudo apt install ./libjpeg-turbo8_2.1.2-0ubuntu1_amd64.deb
sudo apt-get install xfonts-75dpi
wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.jammy_amd64.deb
sudo dpkg -i wkhtmltox_0.12.6.1-2.jammy_amd64.deb
sudo apt --fix-broken install
rm wkhtmltox_0.12.6.1-2.jammy_amd64.deb

Thanks!

**Comment by Anjos-tg** [comment]
Issue closed.
