### ISSUE TITLE
Header are shown on 2. page

### ISSUE THREAD

**Issue by RaySolo** [frappe/print_designer#117]
I believe that I've read a post where it was mentioned, that defining a header/footer area will dismiss the objects inside on the following page. That doesn't work for me. Or is there any magic I have to use?

**Comment by maharshivpatel** [comment]
@RaySolo check https://youtu.be/XpmrLzbianE?t=12m30s

**Comment by maharshivpatel** [comment]
@RaySolo closing this as i haven't heard from you and i can't do anything without more information. if you think there is still a problem please create new issue with more information
