### ISSUE TITLE
Server error If Format have standard set to Yes

### ISSUE THREAD

**Issue by 2old4thisShit** [frappe/print_designer#118]
Hi. I have created a new print format.

When I change the standard field to yes in the print format, I get this error when displaying the format:

Frappe Framework: v15.7.0 (version-15)
GVTLS: v0.0.1 (develop) (my custop app)
Print Designer: v1.0.0 (main)
wkhtmltopdf 0.12.6.1 (with patched qt)

![image](https://github.com/frappe/print_designer/assets/46288096/0ee7922d-8acf-4158-a40a-3063fe246de9)

**Comment by maharshivpatel** [comment]
can you please share more details? what do you mean when you say set standard field to yes

**Comment by maharshivpatel** [comment]
@2old4thisShit if you mean you set render jinja to yes and are getting this error. i found a bug, i will fix it tomorrow

**Comment by 2old4thisShit** [comment]
> can you please share more details? what do you mean when you say set standard field to yes

![image](https://github.com/frappe/print_designer/assets/46288096/2e99df2f-f09c-4f90-8299-94117dfe3362)

**Comment by maharshivpatel** [comment]
@2old4thisShit that is strange will check this. thank you for sharing the issue

**Comment by 2old4thisShit** [comment]
Thanks to you, if you need anything let me know

**Comment by thejoe8495** [comment]
I have a tipp for you. When you cop paste text from word the error comes. After we delete this fields it works.
But i have a other error problem, with the latest version there is only a error message "Unable to generate PDF" is tehre a way to get the error?

**Comment by maharshivpatel** [comment]
@thejoe8495 yes, Basically you replace `Standard` with `Your Print Format Name` in url of Full Page and you will be able to click on error and share it here.

https://github.com/frappe/print_designer/assets/39730881/05086ee7-7c5a-4041-841d-20332cb4cfa2

**Comment by maharshivpatel** [comment]
@2old4thisShit looks like changing standard to yes is not the issue. can you please see the video in previous comment and share the comment.

Also, update to latest version as i have fixed few issues.

**Comment by maharshivpatel** [comment]
@2old4thisShit nvm 😅 found it.

**Comment by 2old4thisShit** [comment]
> @2old4thisShit nvm 😅 found it.
You only gave me time to watch half of the video hahahaha

**Comment by maharshivpatel** [comment]
@2old4thisShit Please see the full video, It is useful for sharing error whenever any kind of error happens 😂

**Comment by thejoe8495** [comment]
> @thejoe8495 yes, Basically you replace `Standard` with `Your Print Format Name` in url of Full Page and you will be able to click on error and share it here.
> 
>  Screen.Recording.2023-12-06.at.2.30.54.PM.mov

Thank you worked perfect thank you. This is the result:
![image](https://github.com/frappe/print_designer/assets/15785677/e0a36a93-6475-46f6-bd6b-74c04a31421a)
of this layout:
![image](https://github.com/frappe/print_designer/assets/15785677/25d7d94d-f83a-4325-b243-e3ec01157169)

Any idea? ;)

**Comment by maharshivpatel** [comment]
@thejoe8495 this means there isn't any error. try getting pdf it should be working now.

if it's not create separate issue with more details.

Thank you

**Comment by 2old4thisShit** [comment]
I have updated the app. I have done what was in the video and the result is this:

![image](https://github.com/frappe/print_designer/assets/46288096/8478e66d-d9da-4e5b-b472-83e44e706bd1)

![image](https://github.com/frappe/print_designer/assets/46288096/6e946085-ed98-4e69-b980-7a57951447fa)


`Traceback (most recent call last):
  File "apps/frappe/frappe/website/serve.py", line 18, in get_response
    response = renderer_instance.render()
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
    html = self.get_html()
  File "apps/frappe/frappe/website/utils.py", line 524, in cache_html_decorator
    html = func(*args, **kwargs)
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 95, in get_html
    self.update_context()
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 163, in update_context
    data = self.run_pymodule_method("get_context")
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 225, in run_pymodule_method
    return method(self.context)
  File "apps/frappe/frappe/www/printview.py", line 57, in get_context
    body = get_rendered_template(
  File "apps/frappe/frappe/www/printview.py", line 168, in get_rendered_template
    template = get_template_from_string()
  File "apps/frappe/frappe/www/printview.py", line 149, in get_template_from_string
    return jenv.from_string(get_print_format(doc.doctype, print_format))
  File "apps/frappe/frappe/www/printview.py", line 407, in get_print_format
    frappe.throw(_("No template found at path: {0}").format(path), frappe.TemplateNotFoundError)
  File "apps/frappe/frappe/__init__.py", line 603, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 575, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 526, in _raise_exception
    raise exc
frappe.exceptions.TemplateNotFoundError: No template found at path: apps/gestion_veterinaria/gestion_veterinaria/gestión_veterinaria_tls/print_format/informe_vacunacion/informe_vacunacion.html`

Checking the path, I don't have any html files. Just a .json file and the __init__

**Comment by maharshivpatel** [comment]
Decided to add hook for loading template instead https://github.com/frappe/frappe/pull/25037
