### ISSUE TITLE
How does print designer handles print format pagination?

### ISSUE THREAD

**Issue by correiarmjoao** [frappe/print_designer#12]
Most of the problems I find when building print formats is handling pagination.

If I use the default pagination provided by frappe (using css counters / page breaks ) it works fine, but if I need more control over how items are shown this way of doing it quickly breaks down.

For example designing a format where the tax field appears empty in every page but filled on the last, showing a QR code only on the third page, showing pagination on a specific place in the header.

How does print_designer handle pagination? Is there a way to handle this use cases?

Thank you,
João

**Comment by maharshivpatel** [comment]
Only show on first and last page is possible with print designer.

different header and footer per page is not supported because this is limitation of wkhtmltopdf library which is used to generate pdfs.

if you face any particular issue while designing print format please create issue.
