### ISSUE TITLE
Error on send in emailqueue 

### ISSUE THREAD

**Issue by thejoe8495** [frappe/print_designer#125]
We have an error when the server try to generate an invoice, error see below.

**Steps to reproduce:**
- Make an Print design
- Set the Print design to default for invoices or other
- Take an invoice, go to E-mail and send the Invoice per mail
- When the Server send it over queue it use an wrong template to generate the Invoice
- When i press the send now button it use the right template and work without any problem

I tried to get the html to write the file on line
https://github.com/frappe/frappe/blob/a04bfddbf922b777340fc73502f9d42ff4ed2cfe/frappe/utils/pdf.py#L84
It works on the automatic queue send. But on the manual send now button there is no generated html file. 
I found the send now button, use the same function like the cronjob but i have no idea why there are two different printlayouts on the same function.

Any suggestions to find out what the Problem?
Is it the same problem like this issue? https://github.com/frappe/print_designer/issues/118

**Versions:**
erpnext 15.7.0
frappe 15.6.1
print_designer 1.0.0
payments 0.0.1
hrms 15.6.0
erpnext_shipping 0.0.1
an some more tiny apps without print.

**Error**
  File "/opt/erpnext/apps/frappe/frappe/email/doctype/email_queue/email_queue.py", line 166, in send
    message = ctx.build_message(recipient.recipient)
  File "/opt/erpnext/apps/frappe/frappe/email/doctype/email_queue/email_queue.py", line 312, in build_message
    message = self.include_attachments(message)
  File "/opt/erpnext/apps/frappe/frappe/email/doctype/email_queue/email_queue.py", line 385, in include_attachments
    print_format_file = frappe.attach_print(**attachment)
  File "/opt/erpnext/apps/frappe/frappe/__init__.py", line 2168, in attach_print
    else get_print(doctype, name, **kwargs)
  File "/opt/erpnext/apps/frappe/frappe/__init__.py", line 2127, in get_print
    return get_pdf(html, options=pdf_options, output=output) if as_pdf else html
  File "/opt/erpnext/apps/frappe/frappe/utils/pdf.py", line 98, in get_pdf
    frappe.throw(_("PDF generation failed because of broken image links"))
  File "/opt/erpnext/apps/frappe/frappe/__init__.py", line 603, in throw
    msgprint(
  File "/opt/erpnext/apps/frappe/frappe/__init__.py", line 575, in msgprint
    _raise_exception()
  File "/opt/erpnext/apps/frappe/frappe/__init__.py", line 526, in _raise_exception
    raise exc

**Comment by maharshivpatel** [comment]
can you send pdf's from both processes ? 

also, error says PDF generation failed because of broken image links

can you try one format without any images and check ?

**Comment by thejoe8495** [comment]
Yes it work for both processes in different doctypes so i found the current problem. On the Dunning doctype it use the wrong template but send it. On the invoice came the error on the used wrong template.

I cant test it on the moment but later i test what happend when i select a different template on send. If it use the different then the default or use always the wrong default. And look in the Database what is saved.

**Comment by thejoe8495** [comment]
I think i found something, not realy with the different template but with my error. The fileupload is over print designer but the files are all private what i see. The server in backgroundjob has no access to this file (forbidden) hes not logged in. I think we need to change the file to public but how can i change the URL from print designer to this file?

**Comment by maharshivpatel** [comment]
just go to the file doctype and change it from there. then come back to the print designer and remove and reselect the file.

**Comment by maharshivpatel** [comment]
> I found the send now button, use the same function like the cronjob but i have no idea why there are two different printlayouts on the same function.

When it is run from cronjob it gets same permissions as administrator so basically all. but when you click on send now button or execute any job manually it is run with same permissions as the user who runs it.

that maybe the reason that you get error when you run manually but not when through cronjob

**Comment by maharshivpatel** [comment]
@thejoe8495 closing this as this was permission error if i understand correctly and not related to print designer.

If you think there is any issue with print designer please open this again or create new one with all details

Thank you.
