### ISSUE TITLE
Text with jinja parsing does not respond to changing font size

### ISSUE THREAD

**Issue by 2old4thisShit** [frappe/print_designer#128]
ERPNext: v15.0.0 (version-15)
Frappe Framework: v15.0.1 (version-15)
Payments: v0.0.1 (develop)
Print Designer: v1.0.0 (main)
Webshop: v0.0.1 (develop)
XFR: v0.0.1 (develop) (custom app)

I have placed some text with jinja parsing on yes, but when I try to modify the size of the text, the size does not change no matter what size I set.

In the preview it looks correct, but not in the final view.

It doesn't seem to position itself correctly either. 

Preview size
![image](https://github.com/frappe/print_designer/assets/46288096/3f11de6c-c2c1-4274-9592-d81f306fd9d3)
Final view size
![image](https://github.com/frappe/print_designer/assets/46288096/7415e9f6-e195-4b09-936f-ec6ed9c20990)

Preview position
![image](https://github.com/frappe/print_designer/assets/46288096/522877a0-3400-4f9a-8ca8-d2e2015115fd)
Final view position
![image](https://github.com/frappe/print_designer/assets/46288096/109cf524-1286-4994-a731-01e5c564553b)

**Comment by maharshivpatel** [comment]
@2old4thisShit I think You have set page margins 😅

**Comment by 2old4thisShit** [comment]
![image](https://github.com/frappe/print_designer/assets/46288096/81bc81cf-0372-4e43-b9a2-8f871ee559ac)

Yes

Is there any type of incompatibility with page margins?

The margins don't seem to work correctly either, but I'll detail that later in another issue.

**Comment by 2old4thisShit** [comment]
I did another format from the beginning, also with page margins and in that it does seem to work correctly.

**Comment by maharshivpatel** [comment]
is it happening if text is after primary table ?

**Comment by 2old4thisShit** [comment]
In the format there is only static text and the date with jinja. There are no tables.

**Comment by maharshivpatel** [comment]
<img width="473" alt="Screenshot 2024-01-30 at 3 16 33 PM" src="https://github.com/frappe/print_designer/assets/39730881/3782b51b-bfac-4d6b-8007-820c7b1348f7">


@2old4thisShit i am able to change font size, weight and color. can you please share format

**Comment by 2old4thisShit** [comment]
Jinja:
`En Monforte de Lemos, a {{ frappe.utils.formatdate(frappe.utils.nowdate(), "d 'de' MMMM 'de' yyyy") }}
`

**Preview in designer:**
![image](https://github.com/frappe/print_designer/assets/46288096/2a9bb548-b953-472f-bba2-9bafb5905daa)

**FInal view:**
![image](https://github.com/frappe/print_designer/assets/46288096/a52b2e65-22e0-4309-9d95-b381e418a2e3)

**Format:**
`{"name":"Autorización uso de imágenes","creation":"2024-01-24 16:54:20.481353","modified":"2024-01-30 11:12:19.316370","modified_by":"Administrator","docstatus":0,"idx":0,"print_designer_after_table":"[]","print_designer_settings":"{\"page\":{\"UOM\":\"mm\",\"footerHeight\":-75.590551182,\"footerHeightWithMargin\":0,\"headerHeight\":-37.795275591,\"headerHeightWithMargin\":37.795275591,\"height\":1122.52,\"marginBottom\":75.590551182,\"marginLeft\":75.590551182,\"marginRight\":75.590551182,\"marginTop\":75.590551182,\"width\":793.701},\"pdfPrintDPI\":96,\"globalStyles\":{\"barcode\":{\"isDynamic\":false,\"isGlobalStyle\":true,\"mainCssRule\":{},\"mainRuleSelector\":\".barcode\",\"style\":{\"backgroundColor\":\"\",\"border\":\"none\",\"borderColor\":\"#000000\",\"borderRadius\":0,\"borderStyle\":\"solid\",\"borderWidth\":\"0px\",\"boxShadow\":\"none\",\"display\":\"block\",\"margin\":\"0px\",\"minHeight\":\"0px\",\"minWidth\":\"0px\",\"opacity\":1,\"paddingBottom\":\"0px\",\"paddingLeft\":\"0px\",\"paddingRight\":\"0px\",\"paddingTop\":\"0px\",\"userSelect\":\"none\",\"whiteSpace\":\"normal\"},\"styleEditMode\":\"main\",\"type\":\"barcode\"},\"dynamicText\":{\"isDynamic\":true,\"isGlobalStyle\":true,\"labelCssRule\":{},\"labelDisplayStyle\":\"standard\",\"labelRuleSelector\":\".dynamicText .label-text\",\"labelStyle\":{\"backgroundColor\":\"#ffffff\",\"border\":\"none\",\"borderColor\":\"#000000\",\"borderRadius\":0,\"borderStyle\":\"solid\",\"borderWidth\":\"0px\",\"boxShadow\":\"none\",\"color\":\"#000000\",\"fontFamily\":\"Inter\",\"fontSize\":\"14px\",\"fontStyle\":\"normal\",\"fontWeight\":600,\"letterSpacing\":\"0px\",\"lineHeight\":1.25,\"margin\":\"0px\",\"minHeight\":\"0px\",\"minWidth\":\"0px\",\"opacity\":1,\"paddingBottom\":\"0px\",\"paddingLeft\":\"0px\",\"paddingRight\":\"0px\",\"paddingTop\":\"0px\",\"textAlign\":\"left\",\"textDecoration\":\"none\",\"textTransform\":\"none\",\"userSelect\":\"none\",\"whiteSpace\":\"normal\",\"zIndex\":1},\"mainCssRule\":{},\"mainRuleSelector\":\".dynamicText\",\"style\":{\"backgroundColor\":\"#ffffff\",\"border\":\"none\",\"borderColor\":\"#000000\",\"borderRadius\":0,\"borderStyle\":\"solid\",\"borderWidth\":\"0px\",\"boxShadow\":\"none\",\"color\":\"#000000\",\"contenteditable\":false,\"display\":\"inline-block\",\"fontFamily\":\"Inter\",\"fontSize\":\"14px\",\"fontStyle\":\"normal\",\"fontWeight\":400,\"letterSpacing\":\"0px\",\"lineHeight\":1.25,\"margin\":\"0px\",\"minHeight\":\"0px\",\"minWidth\":\"0px\",\"opacity\":1,\"overflow\":\"hidden\",\"overflowWrap\":\"break-word\",\"paddingBottom\":\"0px\",\"paddingLeft\":\"0px\",\"paddingRight\":\"0px\",\"paddingTop\":\"0px\",\"textAlign\":\"left\",\"textDecoration\":\"none\",\"textTransform\":\"none\",\"userSelect\":\"none\",\"whiteSpace\":\"normal\"},\"styleEditMode\":\"main\",\"type\":\"text\"},\"image\":{\"isDynamic\":false,\"isGlobalStyle\":true,\"mainCssRule\":{},\"mainRuleSelector\":\".image\",\"style\":{\"backgroundColor\":\"\",\"backgroundPosition\":\"center center\",\"backgroundRepeat\":\"no-repeat\",\"backgroundSize\":\"contain\",\"border\":\"none\",\"borderColor\":\"#000000\",\"borderRadius\":0,\"borderStyle\":\"solid\",\"borderWidth\":\"0px\",\"boxShadow\":\"none\",\"display\":\"block\",\"margin\":\"0px\",\"minHeight\":\"0px\",\"minWidth\":\"0px\",\"objectFit\":\"scale-down\",\"objectPosition\":\"center center\",\"opacity\":1,\"paddingBottom\":\"0px\",\"paddingLeft\":\"0px\",\"paddingRight\":\"0px\",\"paddingTop\":\"0px\",\"userSelect\":\"none\",\"whiteSpace\":\"normal\"},\"styleEditMode\":\"main\",\"type\":\"image\"},\"rectangle\":{\"isDynamic\":false,\"isGlobalStyle\":true,\"mainCssRule\":{},\"mainRuleSelector\":\".rectangle\",\"style\":{\"alignContent\":\"flex-start\",\"alignItems\":\"flex-start\",\"backgroundColor\":\"#ffffff\",\"border\":\"1px solid black\",\"borderColor\":\"#000000\",\"borderRadius\":0,\"borderStyle\":\"solid\",\"borderWidth\":\"1px\",\"boxShadow\":\"none\",\"boxSizing\":\"border-box\",\"color\":\"#000000\",\"display\":\"inline-flex\",\"flex\":1,\"justifyContent\":\"flex-start\",\"margin\":\"0px\",\"minHeight\":\"0px\",\"minWidth\":\"0px\",\"opacity\":1,\"outline\":\"none\",\"paddingBottom\":\"0px\",\"paddingLeft\":\"0px\",\"paddingRight\":\"0px\",\"paddingTop\":\"0px\",\"userSelect\":\"none\",\"whiteSpace\":\"normal\",\"zIndex\":0},\"styleEditMode\":\"main\",\"type\":\"rectangle\"},\"staticText\":{\"isDynamic\":false,\"isGlobalStyle\":true,\"labelDisplayStyle\":\"standard\",\"mainCssRule\":{},\"mainRuleSelector\":\".staticText\",\"style\":{\"backgroundColor\":\"#ffffff\",\"border\":\"none\",\"borderColor\":\"#000000\",\"borderRadius\":0,\"borderStyle\":\"solid\",\"borderWidth\":\"0px\",\"boxShadow\":\"none\",\"color\":\"#000000\",\"contenteditable\":false,\"display\":\"inline-block\",\"fontFamily\":\"Inter\",\"fontSize\":\"14px\",\"fontStyle\":\"normal\",\"fontWeight\":400,\"letterSpacing\":\"0px\",\"lineHeight\":1.25,\"margin\":\"0px\",\"minHeight\":\"0px\",\"minWidth\":\"0px\",\"opacity\":1,\"overflow\":\"hidden\",\"overflowWrap\":\"break-word\",\"paddingBottom\":\"0px\",\"paddingLeft\":\"0px\",\"paddingRight\":\"0px\",\"paddingTop\":\"0px\",\"textAlign\":\"left\",\"textDecoration\":\"none\",\"textTransform\":\"none\",\"userSelect\":\"none\",\"whiteSpace\":\"normal\",\"zIndex\":1},\"styleEditMode\":\"main\",\"type\":\"text\"},\"table\":{\"headerCssRule\":{},\"headerRuleSelector\":\".printTable th\",\"headerStyle\":{\"backgroundColor\":\"#ffffff\",\"border\":\"none\",\"borderColor\":\"#000000\",\"borderRadius\":0,\"borderStyle\":\"solid\",\"borderWidth\":\"1px\",\"boxShadow\":\"none\",\"color\":\"#000000\",\"fontFamily\":\"Inter\",\"fontSize\":\"11px\",\"fontStyle\":\"normal\",\"fontWeight\":600,\"letterSpacing\":\"0px\",\"lineHeight\":1.25,\"margin\":\"0px\",\"minHeight\":\"0px\",\"minWidth\":\"0px\",\"opacity\":1,\"paddingBottom\":\"10px\",\"paddingLeft\":\"10px\",\"paddingRight\":\"10px\",\"paddingTop\":\"10px\",\"textAlign\":\"left\",\"textDecoration\":\"none\",\"textTransform\":\"none\",\"userSelect\":\"none\",\"whiteSpace\":\"normal\",\"zIndex\":1},\"isDynamic\":true,\"isGlobalStyle\":true,\"labelCssRule\":{},\"labelDisplayStyle\":\"standard\",\"labelRuleSelector\":\".printTable .label-text\",\"labelStyle\":{\"backgroundColor\":\"#ffffff\",\"border\":\"none\",\"borderColor\":\"#000000\",\"borderRadius\":0,\"borderStyle\":\"solid\",\"borderWidth\":\"0px\",\"boxShadow\":\"none\",\"color\":\"#000000\",\"fontFamily\":\"Inter\",\"fontSize\":\"10px\",\"fontStyle\":\"normal\",\"fontWeight\":600,\"letterSpacing\":\"0px\",\"lineHeight\":1.25,\"margin\":\"0px\",\"minHeight\":\"0px\",\"minWidth\":\"0px\",\"opacity\":1,\"paddingBottom\":\"0px\",\"paddingLeft\":\"0px\",\"paddingRight\":\"0px\",\"paddingTop\":\"0px\",\"textAlign\":\"left\",\"textDecoration\":\"none\",\"textTransform\":\"none\",\"userSelect\":\"none\",\"verticalAlign\":\"baseline\",\"whiteSpace\":\"normal\",\"zIndex\":1},\"mainCssRule\":{},\"mainRuleSelector\":\".printTable td\",\"style\":{\"backgroundColor\":\"#ffffff\",\"border\":\"none\",\"borderColor\":\"#000000\",\"borderRadius\":0,\"borderStyle\":\"solid\",\"borderWidth\":\"1px\",\"boxShadow\":\"none\",\"color\":\"#000000\",\"contenteditable\":false,\"fontFamily\":\"Inter\",\"fontSize\":\"10px\",\"fontStyle\":\"normal\",\"fontWeight\":400,\"letterSpacing\":\"0px\",\"lineHeight\":1.25,\"margin\":\"0px\",\"minHeight\":\"0px\",\"minWidth\":\"0px\",\"opacity\":1,\"overflowWrap\":\"break-word\",\"paddingBottom\":\"10px\",\"paddingLeft\":\"10px\",\"paddingRight\":\"10px\",\"paddingTop\":\"10px\",\"textAlign\":\"left\",\"textDecoration\":\"none\",\"textTransform\":\"none\",\"userSelect\":\"none\",\"verticalAlign\":\"baseline\",\"whiteSpace\":\"normal\"},\"styleEditMode\":\"main\",\"type\":\"table\"}},\"currentPageSize\":\"CUSTOM\",\"isHeaderFooterAuto\":false,\"currentDoc\":\"EXP-2023-000202\",\"textControlType\":\"static\",\"currentFonts\":[\"Inter\"],\"printHeaderFonts\":{\"Inter\":{\"weight\":[700],\"italic\":[]}},\"printFooterFonts\":null,\"printBodyFonts\":{\"Inter\":{\"weight\":[400,600,700],\"italic\":[]}},\"userProvidedJinja\":\"\\r\\n\",\"schema_version\":\"1.0.1\"}","print_designer_header":"[{\"id\":\"xTRKXowMMI\",\"type\":\"text\",\"content\":\"AUTORIZACIÓN USO DE IMÁGENES\",\"contenteditable\":false,\"isDynamic\":false,\"isFixedSize\":true,\"isDraggable\":true,\"isResizable\":true,\"isDropZone\":false,\"parseJinja\":false,\"startX\":173.50994881800005,\"startY\":-0.014025590999999338,\"pageX\":877,\"pageY\":189.78125,\"width\":305.5,\"height\":24.5,\"styleEditMode\":\"main\",\"labelDisplayStyle\":\"standard\",\"style\":{\"fontWeight\":\"700\",\"textAlign\":\"center\",\"fontSize\":\"16px\"},\"classes\":[],\"printY\":75.576525591}]","print_designer_footer":"[]","print_designer_body":"[{\"id\":\"cHfyCDfbgH\",\"type\":\"text\",\"content\":\"\",\"contenteditable\":false,\"isDynamic\":true,\"isFixedSize\":true,\"dynamicContent\":[{\"doctype\":\"\",\"parentField\":\"\",\"fieldname\":\"UJZduvDwdn\",\"value\":\"CONSIENTE EXPRESAMENTE\",\"fieldtype\":\"StaticText\",\"is_static\":true,\"is_labelled\":false,\"nextLine\":false,\"style\":{\"fontSize\":\"16px\"},\"labelStyleEditing\":false,\"parseJinja\":false,\"spanRef\":null}],\"selectedDynamicText\":null,\"isDraggable\":true,\"isResizable\":true,\"isDropZone\":false,\"startX\":170.30682381800005,\"startY\":210.409448818,\"pageX\":778,\"pageY\":400,\"width\":301.90625,\"height\":25.75,\"styleEditMode\":\"main\",\"labelDisplayStyle\":\"standard\",\"style\":{\"fontWeight\":\"700\",\"fontSize\":\"15px\",\"textAlign\":\"center\"},\"labelStyle\":{},\"classes\":[],\"printY\":248.204724409},{\"id\":\"prgooJzSPd\",\"type\":\"text\",\"content\":\"\",\"contenteditable\":false,\"isDynamic\":true,\"isFixedSize\":true,\"dynamicContent\":[{\"doctype\":\"\",\"parentField\":\"\",\"fieldname\":\"mPrCwdhaGf\",\"value\":\"<div>Y de forma libre y voluntaria, a FUNERARIA RAUL SL, con domicilio en CALLE ROBERTO BAAMONDE 120, 27400 - MONFORTE DE LEMOS (LUGO), a proceder a la publicación de su imagen a través de una plataforma propia, permitiendo visualizar imágenes retransmitidas en directo desde la capilla del Tanatorio, con la exclusiva finalidad de mostrar el funeral a los familiares.<br>&nbsp;</div><div>Dichos datos serán tratados por FUNERARIA RAUL SL, pudiendo el/la interesado/a ejercer los derechos de acceso, rectificación, supresión, oposición, limitación del tratamiento, portabilidad de datos y a no ser objeto de decisiones individualizadas, automatizadas, en relación con los datos objeto del tratamiento, ante el responsable del tratamiento en la dirección anteriormente indicada, adjuntando copia de su DNI o documento equivalente. En caso de que no haya obtenido satisfacción en el ejercicio de sus derechos, puede presentar una reclamación ante la&nbsp; Autoridad de Control en materia Protección de Datos competente, siendo ésta la Agencia Española de Protección de Datos, y cuyos datos de contacto están accesibles en https://sedeagpd.gob.es/sede-electronica-web/vistas/formNuevaReclamacion/reclamacion.jsf<br><br></div><div>Asimismo, tiene derecho a oponerse y/o retirar dicho consentimiento, en cualquier momento, mediante notificación al responsable del tratamiento, en la dirección mencionada.<br><br></div><div>Los datos proporcionados se conservarán hasta que ejerza su derecho de oposición o cancelación de los mismos, y no serán cedidos a terceros salvo que exista obligación legal.</div><div>FUNERARIA RAUL SL no elaborará ningún tipo de “perfil” en base a la información facilitada. No se tomarán decisiones automatizadas en base a perfiles.</div>\",\"fieldtype\":\"StaticText\",\"is_static\":true,\"is_labelled\":false,\"nextLine\":false,\"style\":{},\"labelStyleEditing\":false,\"parseJinja\":false,\"spanRef\":null}],\"selectedDynamicText\":null,\"isDraggable\":true,\"isResizable\":true,\"isDropZone\":false,\"startX\":-0.013488681999938024,\"startY\":245.409448818,\"pageX\":363.15625,\"pageY\":408,\"width\":642.515625,\"height\":505.8125,\"styleEditMode\":\"main\",\"labelDisplayStyle\":\"standard\",\"style\":{\"textAlign\":\"left\",\"fontSize\":\"14px\",\"lineHeight\":1.5,\"letterSpacing\":\"0px\"},\"labelStyle\":{},\"classes\":[],\"printY\":283.204724409},{\"id\":\"EheHjpqnGx\",\"type\":\"text\",\"content\":\"Firma:\",\"contenteditable\":false,\"isDynamic\":false,\"isFixedSize\":false,\"isDraggable\":true,\"isResizable\":true,\"isDropZone\":false,\"parseJinja\":false,\"startX\":5.985974409000001,\"startY\":856.220349409,\"pageX\":643.78125,\"pageY\":758.015625,\"width\":45.578125,\"height\":25.75,\"styleEditMode\":\"main\",\"labelDisplayStyle\":\"standard\",\"style\":{\"fontSize\":\"15px\"},\"classes\":[],\"printY\":894.015625},{\"id\":\"NteegesNxc\",\"type\":\"text\",\"content\":\"Don/Dña.: _______________________________________ con D.N.I: ____________ o, en su caso, su representante legal D/Dª___________________________________ con D.N.I __________ y domicilio en _________________________________________, reuniendo las condiciones de madurez suficientes,&nbsp;<br>De conformidad con lo establecido en la normativa vigente en materia de Protección de Datos de Carácter Personal, y en el artículo 2.2 de la Ley Orgánica 1/1982, de 5 de mayo, de protección civil del derecho del honor, a la intimidad personal y familiar y a la propia imagen,<br><br>\",\"contenteditable\":false,\"isDynamic\":false,\"isFixedSize\":true,\"isDraggable\":true,\"isResizable\":true,\"isDropZone\":false,\"parseJinja\":false,\"startX\":-0.014025590999999338,\"startY\":59.204724408999994,\"pageX\":640,\"pageY\":249,\"width\":642.515625,\"height\":141.5,\"styleEditMode\":\"main\",\"labelDisplayStyle\":\"standard\",\"style\":{\"fontSize\":\"14px\",\"lineHeight\":1.5},\"classes\":[],\"printY\":97},{\"id\":\"cfrdGkLWJx\",\"type\":\"text\",\"content\":\"<div>En Monforte de Lemos, a {{ frappe.utils.formatdate(frappe.utils.nowdate(), \\\"d 'de' MMMM 'de' yyyy\\\") }}</div><div><br></div>\",\"contenteditable\":false,\"isDynamic\":false,\"isFixedSize\":true,\"isDraggable\":true,\"isResizable\":true,\"isDropZone\":false,\"parseJinja\":true,\"startX\":0,\"startY\":765.21875,\"pageX\":538,\"pageY\":726,\"width\":639.5291748046875,\"height\":73.78125,\"styleEditMode\":\"main\",\"labelDisplayStyle\":\"standard\",\"style\":{\"fontSize\":\"30px\",\"color\":\"#d61111\"},\"classes\":[],\"printY\":803.014025591}]","print_designer":1,"doc_type":"XF Expediente","module":"Xestion Funeraria Raul","standard":"No","custom_format":0,"disabled":0,"print_format_type":"Jinja","raw_printing":0,"margin_top":15,"margin_bottom":15,"margin_left":15,"margin_right":15,"align_labels_right":0,"show_section_headings":0,"line_breaks":0,"absolute_value":0,"font_size":14,"page_number":"Hide","css":":root { --scale-factor: 1px; --modal-x: 0px; --modal-y: 0px; } .staticText { display: inline-block; font-family: Inter; font-size: 14px; font-weight: 400; color: rgb(0, 0, 0); text-align: left; font-style: normal; text-decoration: none; text-transform: none; line-height: 1.25; letter-spacing: 0px; border: 0px solid rgb(0, 0, 0); border-radius: 0px; background-color: rgb(255, 255, 255); padding: 0px; margin: 0px; min-width: 0px; min-height: 0px; box-shadow: none; overflow: hidden; overflow-wrap: break-word; white-space: normal; user-select: none; opacity: 1; z-index: 1; } .dynamicText { display: inline-block; font-family: Inter; font-size: 14px; font-weight: 400; color: rgb(0, 0, 0); text-align: left; font-style: normal; text-decoration: none; text-transform: none; line-height: 1.25; letter-spacing: 0px; border: 0px solid rgb(0, 0, 0); border-radius: 0px; background-color: rgb(255, 255, 255); padding: 0px; margin: 0px; min-width: 0px; min-height: 0px; box-shadow: none; overflow: hidden; overflow-wrap: break-word; white-space: normal; user-select: none; opacity: 1; } .dynamicText .label-text { font-family: Inter; font-size: 14px; font-weight: 600; color: rgb(0, 0, 0); text-align: left; font-style: normal; text-decoration: none; text-transform: none; line-height: 1.25; letter-spacing: 0px; border: 0px solid rgb(0, 0, 0); border-radius: 0px; background-color: rgb(255, 255, 255); padding: 0px; margin: 0px; min-width: 0px; min-height: 0px; box-shadow: none; white-space: normal; user-select: none; opacity: 1; z-index: 1; } .rectangle { display: inline-flex; place-content: flex-start; align-items: flex-start; flex: 1 1 0%; padding: 0px; margin: 0px; white-space: normal; user-select: none; min-width: 0px; min-height: 0px; color: rgb(0, 0, 0); background-color: rgb(255, 255, 255); border: 1px solid rgb(0, 0, 0); box-sizing: border-box; outline: none; border-radius: 0px; box-shadow: none; opacity: 1; z-index: 0; } .image { display: block; border: 0px solid rgb(0, 0, 0); border-radius: 0px; padding: 0px; margin: 0px; min-width: 0px; min-height: 0px; box-shadow: none; white-space: normal; user-select: none; object-fit: scale-down; object-position: center center; background-size: contain; background-position: center center; background-repeat: no-repeat; opacity: 1; } .barcode { display: block; border: 0px solid rgb(0, 0, 0); border-radius: 0px; padding: 0px; margin: 0px; min-width: 0px; min-height: 0px; box-shadow: none; white-space: normal; user-select: none; opacity: 1; } .printTable td { font-family: Inter; font-size: 10px; font-weight: 400; color: rgb(0, 0, 0); text-align: left; font-style: normal; text-decoration: none; text-transform: none; line-height: 1.25; letter-spacing: 0px; border: 1px solid rgb(0, 0, 0); border-radius: 0px; background-color: rgb(255, 255, 255); padding: 10px; margin: 0px; min-width: 0px; min-height: 0px; box-shadow: none; overflow-wrap: break-word; white-space: normal; user-select: none; vertical-align: baseline; opacity: 1; } .printTable .label-text { font-family: Inter; font-size: 10px; font-weight: 600; color: rgb(0, 0, 0); text-align: left; font-style: normal; text-decoration: none; text-transform: none; line-height: 1.25; letter-spacing: 0px; border: 0px solid rgb(0, 0, 0); border-radius: 0px; background-color: rgb(255, 255, 255); padding: 0px; margin: 0px; min-width: 0px; min-height: 0px; box-shadow: none; white-space: normal; user-select: none; opacity: 1; vertical-align: baseline; z-index: 1; } .printTable th { font-family: Inter; font-size: 11px; font-weight: 600; color: rgb(0, 0, 0); text-align: left; font-style: normal; text-decoration: none; text-transform: none; line-height: 1.25; letter-spacing: 0px; border: 1px solid rgb(0, 0, 0); border-radius: 0px; background-color: rgb(255, 255, 255); padding: 10px; margin: 0px; min-width: 0px; min-height: 0px; box-shadow: none; white-space: normal; user-select: none; opacity: 1; z-index: 1; } :root, ::after, ::before { --print-width: 210.000mm; --print-height: 297.000mm; --print-container-width: 230.000mm; --print-container-height: 317.000mm; --print-margin-top: -20mm; --print-margin-bottom: 20.000mm; --print-margin-left: -20mm; --print-margin-right: 20.000mm; }@page { size: 210mm 297mm; margin: 0mm; } @page { size: 210mm 297mm; margin: 0mm; } @page { size: 210mm 297mm; margin: 20mm; }","print_format_builder":0,"print_format_builder_beta":0,"doctype":"Print Format","__onload":{"print_templates":[]},"__last_sync_on":"2024-01-30T10:12:19.426Z"}`

Note: This format was initially created with an older version of Print Designer. But even updating the app has never worked correctly, even if I edited it.

On the other hand, I have managed to create the format perfectly from 0 in the version I currently have.

This one, however, still doesn't work.

**Comment by maharshivpatel** [comment]
@2old4thisShit This is because you pasted the text and chrome added a div 🥲 . please always use  paste without formatting `cmd/ctrl + shift + v`

**Comment by maharshivpatel** [comment]
closing this as already similar issue is shared in #129
