### ISSUE TITLE
Erpnext is not accessible 

### ISSUE THREAD

**Issue by Rajanthony123** [frappe/print_designer#13]
Hello ,my name is  Makwin ,recently i have installed the print designer app for my erpnext version14 in frappe bench.
i saw some errors occurring as couldnot resolve pinia  .
After the installation my erpnext site is not accessible i mean the UI has disturbed  and i cant even login also.
Please let me know how can i solve this .

does print designer supports version 14 ?

**Comment by rmehta** [comment]
Print designer does not support 14.

**Comment by maharshivpatel** [comment]
Please note that print designer is only compatible with develop version of frappe framework. v14 is not supported as this app requires vue3.

Create a site with develop / nightly version of frappe framework and try it out.

To fix your erpnext site just remove the app and restart.
