### ISSUE TITLE
Unable Generate PDF When Print

### ISSUE THREAD

**Issue by donnieferdian** [frappe/print_designer#130]
hi @maharshivpatel 

I am experiencing an issue after finishing the design for the print format.
When I select the print format that I created using the print designer,
I've got an error message as shown in the following picture:

<img width="455" alt="Screenshot 2024-01-12 at 03 24 13" src="https://github.com/frappe/print_designer/assets/109821040/3a28ad15-9005-4d17-8ecf-c974e0f036d1">

<br>
<br>

```
Print Designer: v1.0.0 (main)
wkhtmltopdf 0.12.6
``` 

regards,.

**Comment by maharshivpatel** [comment]
@donnieferdian you need internet connection because fonts are loaded from google fonts.

what kind of setup you are using ?

**Comment by maharshivpatel** [comment]
@donnieferdian are you able to generate pdf of normal print format.

when checking for normal formats you need to click on get pdf and not click on print button.
