### ISSUE TITLE
Print format in table needs to allow wrapping

### ISSUE THREAD

**Issue by SantoshSrinivas79** [frappe/print_designer#14]
Thank you for this module.  Could you please  suggest how to make sure the text in a table wraps correctly?
My current output is show below:

![CleanShot 2023-06-29 at 13 26 43](https://github.com/frappe/print_designer/assets/1036163/12342f59-9be6-4b58-a5dd-ad73d2759a23)

**Comment by maharshivpatel** [comment]
I am aware of this and will solve this as soon as possible.

**Comment by maharshivpatel** [comment]
@SantoshSrinivas79 
1. Install the latest version
2. migrate the site
3. open your format in Print Designer and check if text is wrapped correctly.
4. Now save the format

**Comment by SantoshSrinivas79** [comment]
Thank you @maharshivpatel ... works perfectly now!

**Comment by SantoshSrinivas79** [comment]
Another question @maharshivpatel .... how to make the table flow into the next page? It seem be getting cut out.

Also, is the way to include the PDF as attachment to notifications is to just use `Attach Print` in the notification section?

<img width="808" alt="CleanShot 2023-06-30 at 12 25 53@2x" src="https://github.com/frappe/print_designer/assets/1036163/76962cdc-3f48-45fc-a5c9-51b38dc5338a">

**Comment by maharshivpatel** [comment]
can you share the full screenshot or pdf ? i am unable to understand the issue.

**Comment by SantoshSrinivas79** [comment]
Sure. Could you please advise where I can export to PDF? 

Below is the full screen .... but I can't see the rest of it. I have also attached the standard print version so that you can see the difference. Hope I am able to clarify the issue I am figuring out.

**With Print-Designer**

![CleanShot 2023-06-30 at 19 09 17@2x](https://github.com/frappe/print_designer/assets/1036163/8dc204fd-3820-4983-9cb8-c5b7f91b45c9)

**Standard Print Layout**
![CleanShot 2023-06-30 at 19 11 48@2x](https://github.com/frappe/print_designer/assets/1036163/4cf1ad03-0b02-4ce5-bf31-c6a5a43c951f)

**Comment by maharshivpatel** [comment]
you can try changing format to refresh on printview page. on print designer page you are not suppose to see whole table. it is designed this way so you can add more elements after the table and in actual print it will be added after the whole table.

**Comment by SantoshSrinivas79** [comment]
Thank you @maharshivpatel
