### ISSUE TITLE
feat: Ability for the user to add pages when working with static text and jinja.

### ISSUE THREAD

**Issue by 2old4thisShit** [frappe/print_designer#141]
Would it be possible to add the possibility of adding new pages in the future?

I seem to remember that if the content of a childtable exceeds the size of the page, new pages are automatically created.

But the possibility that the user can add more pages could be interesting, for example if you are creating documentation based on static text and jinja.

**Comment by maharshivpatel** [comment]
This is duplicate as it will be solved by #102 please follow that for update on this. Thank you
