### ISSUE TITLE
Invalid file path error

### ISSUE THREAD

**Issue by sooryakalai** [frappe/print_designer#16]
An error pops up when I select print designer > create new> select doctype > give it a name and then click on create

Message
Invalid file path: print_designer.bundle.js

could you please help ?
![image](https://github.com/frappe/print_designer/assets/20853406/715f84a1-8fcb-4c48-8342-2dc6451da6a1)

**Comment by maharshivpatel** [comment]
Try these steps :

bench build --app print_designer --force
bench --site {{ site-name }} clear-cache

**Comment by maharshivpatel** [comment]
@sooryakalai did you try the steps i shared ? let me know if that worked or not !

**Comment by mez-vulero** [comment]
It did not work for me. Is it compatible with v14?

**Comment by maharshivpatel** [comment]
Please note that print designer is only compatible with develop version of frappe framework. v14 is not supported

**Comment by maharshivpatel** [comment]
Closing as there is no response. if you still face the issue please reopen with details / errors.
