### ISSUE TITLE
The Frappe Print design gives the wrong page height and width in the print preview of the single document in doctype.

### ISSUE THREAD

**Issue by parimal-ts** [frappe/print_designer#162]
I have created one custom print format using print designer app but in the print page it will provide the wrong page size in frappe.
Report Design:
![img1](https://github.com/frappe/print_designer/assets/96576823/0097acc2-4cfd-4a26-b7f3-efd4e9bdcd97)

Print Preview:
![img2](https://github.com/frappe/print_designer/assets/96576823/62d134dd-478a-41d3-9a35-3ea18b656286)

**Comment by maharshivpatel** [comment]
@parimal-ts please check https://github.com/frappe/print_designer?tab=readme-ov-file#faq

**Comment by parimal-ts** [comment]
Thanks @maharshivpatel it work for me!!
Below are steps to update version from 0.12.5 to 0.12.6
sudo apt-get install xfonts-75dpi
wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.focal_amd64.deb
sudo dpkg -i ~/Downloads/wkhtmltox_0.12.6-1.focal_amd64.deb
