### ISSUE TITLE
Print from POS messed up

### ISSUE THREAD

**Issue by kholidraf** [frappe/print_designer#164]
So I have ERPNext 15 with Print Designer app installed.

I did setup the print format for POS Invoice using print designer app, let say I give it under the name (POS Print Format A). Everything gonna ok when I print from POS Invoice list menu. But when I print directly prom POS after checkout, the print format is messed up like this:
![Screenshot from 2024-02-09 23-47-55](https://discuss.frappe.io/uploads/default/original/3X/7/3/7360a457053cf0741d8645ee5632d8298646fb62.png)
![Screenshot from 2024-02-09 23-47-55](https://discuss.frappe.io/uploads/default/original/3X/b/b/bb8414c18ce1f4ae4e74ecc890eb5242b29ba74a.png)
But when I generate pdf from POS Invoice lists, everything gone ok with pdf file. 
![Screenshot from 2024-02-15 15-08-25](https://github.com/frappe/print_designer/assets/13441252/e99a5ffe-d864-4e03-afda-8e130201bae0)
Please help me figure out this issue. :)

**Comment by maharshivpatel** [comment]
@kholidraf Thanks for reporting this. i will fix this as soon as possible.

**Comment by maharshivpatel** [comment]
@kholidraf Please check and let me know if now it works as intended.

**Comment by kholidraf** [comment]
@maharshivpatel thanks, did I need to update the bench before?
