### ISSUE TITLE
Barcode Field Height is very big

### ISSUE THREAD

**Issue by infinity-sys** [frappe/print_designer#165]
Hello,
i am trying to print out a barcode label with size of 9 cm width and 5 cm height.
this label should contain a barcode on the bottom with height 1 cm and width 7 cmd

first note is that when i choose page size CUSTOM and define 9 cm x 5 cm it comes out on actual printing 7 cm x 4 cm
second note is that barcode field is seems to be keeping aspect ratio, so although i defined 1 cm in height and 7 cm in width , it is printed in near correct width , but height is very big.

<img width="1699" alt="image" src="https://github.com/frappe/print_designer/assets/55486043/d821f396-9f6d-4d05-950e-11bf7be857d1">

<img width="371" alt="image" src="https://github.com/frappe/print_designer/assets/55486043/222b038c-9936-480b-9e22-b3a1ae0e97d8">

I appreciate your support.

**Comment by maharshivpatel** [comment]
@infinity-sys i am unable to reproduce this. do you have [correct version of wkhtmltopdf](https://github.com/frappe/print_designer?tab=readme-ov-file#faq) ?

**Comment by maharshivpatel** [comment]
@vanukw as you can see in preview you don't have actual value that is why it is different in print and preview. please load some document that have the value and design accordingly. Thank you.
