### ISSUE TITLE
Cannot print Render correct

### ISSUE THREAD

**Issue by langjino** [frappe/print_designer#170]
Hi all
my app is:
ERPNext: v15.14.3 (version-15)
Frappe Framework: v15.15.0 (version-15)
Frappe HR: v16.0.0-dev (develop)
Print Designer: v1.0.0 (main)

i have new design print, but when apply cannot render correct, 

anybody know why ??

1. my design
![screenshot_1708487203](https://github.com/frappe/print_designer/assets/139469476/5bda95b6-71a1-4ca8-bb88-f11d19fe65b9)

3. when render
![screenshot_1708487262](https://github.com/frappe/print_designer/assets/139469476/c6dca293-2319-46d8-95ce-ff669df1fc80)

**Comment by maharshivpatel** [comment]
@langjino please install correct Wkhtmltopdf version https://github.com/frappe/print_designer#faq

**Comment by langjino** [comment]
> @langjino please install correct Wkhtmltopdf version https://github.com/frappe/print_designer#faq

i have Wkhtmltopdf  0.12.6, this is newest ??

**Comment by langjino** [comment]
@maharshivpatel, by step in https://github.com/frappe/print_designer#faq
Include 8 Step, I skipped steps 3,4
i am only install step 5 and 6

Is that the cause??

**Comment by maharshivpatel** [comment]
@langjino can you try mobile hotspot or different wifi. also, make sure you are connected to internet.

wkhtmltopdf should be with patched qt

**Comment by langjino** [comment]
> @langjino can you try mobile hotspot or different wifi. also, make sure you are connected to internet.
> 
> also, did you restart the bench
> 
> wkhtmltopdf should be with patched qt

i using default print format no broblem, it only with "Print Desinger Format"

**Comment by maharshivpatel** [comment]
@langjino it should be **( qt patched )** `wkhtmltopdf 0.12.6 (with patched qt)`

**Comment by langjino** [comment]
> @langjino it should be **( qt patched )** `wkhtmltopdf 0.12.6 (with patched qt)`

so thanhk, i have fixed by install wkhtmltopdf 0.12.6 (with patched qt)
This is my code

_$ wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.jammy_amd64.deb
_$ sudo apt install ./wkhtmltox_0.12.6.1-2.jammy_amd64.deb_
