### ISSUE TITLE
Print Designer 

### ISSUE THREAD

**Issue by webcomx** [frappe/print_designer#183]
l have installed perfectly on V15 production but does not show on desk.

**Comment by webcomx** [comment]
After creating a picking list print format using print designer, previewing gives me this error 
![image](https://github.com/frappe/print_designer/assets/103621094/7208343d-e699-4fca-b758-29ef66c43cc4)

**Comment by maharshivpatel** [comment]
have you installed latest version of print designer?
if no, please update print designer.
if you already have the latest version, check error log and share the error. thank you.

**Comment by maharshivpatel** [comment]
@webcomx closing this for now as i haven't heard from you in a while. 
if you still face the issue create new issue. Thank you
