### ISSUE TITLE
Header/Footer not working

### ISSUE THREAD

**Issue by T941** [frappe/print_designer#184]
I'm currently using the trial version, but the header/footer section isn't working. Do I need to set up anything additional for it to function?
![image](https://github.com/frappe/print_designer/assets/51939134/1a1be276-9944-4697-816d-a6be9cabcd7d)
![image](https://github.com/frappe/print_designer/assets/51939134/f3811fb7-d961-42e9-aa8d-dedc142b5a8e)

**Comment by maharshivpatel** [comment]
@T941 please install correct version of wkhtmltopdf https://github.com/frappe/print_designer?tab=readme-ov-file#faq

**Comment by T941** [comment]
@maharshivpatel Wonderful, thank you so much.

**Comment by maharshivpatel** [comment]
@T941 closing the issue as this should solve your problem. feel free to open new issue if you still face some kind of problem. thank you
