### ISSUE TITLE
Printing does not show header and footer 

### ISSUE THREAD

**Issue by webcomx** [frappe/print_designer#189]
Hello thare ! 
am having an issue of the printing header and footer not showing - but showing in print designer, also it shrings the page table so you see a big margin to your right when printing. any change you can help

**Comment by maharshivpatel** [comment]
@webcomx you need to install correct version of wkhtmltopdf https://github.com/frappe/print_designer?tab=readme-ov-file#faq

**Comment by webcomx** [comment]
[INVOICE.pdf](https://github.com/frappe/print_designer/files/14536862/INVOICE.pdf)

Thanks for the update, will update when l get to the office, however l have tested print designer in the cloud and it seems am not able to display Batch no. and expire date is that possible with print designer APP. attach is a tally invoice l want to create

**Comment by webcomx** [comment]
hello l notice from the doctype batch there is no data field called batch_no we have batch_id any chance l can update that, seems when create one form add txt and use render in jinja it does not work

**Comment by webcomx** [comment]
![image](https://github.com/frappe/print_designer/assets/103621094/e7754ce6-1261-40aa-a6c8-7c2ac2645410)

**Comment by webcomx** [comment]
![image](https://github.com/frappe/print_designer/assets/103621094/80b4e9b3-c081-4dda-bfa3-0955dde09768)
Is A4 but shrinks when you preview

**Comment by webcomx** [comment]
![image](https://github.com/frappe/print_designer/assets/103621094/50e5ea46-1c0b-4599-82dc-448417eaa5a1)
alreaady have the  wkhtmltopdf  latest

**Comment by maharshivpatel** [comment]
@webcomx it needs to be qt patched. please go through https://github.com/frappe/print_designer/discussions/172#discussion-6247440

**Comment by maharshivpatel** [comment]
@webcomx i hope issue was solved as problem was you didn't have correct wkhtmltopdf version. please let me know if you are still facing the issue. i am closing this for now. Thank you
