### ISSUE TITLE
Lazy load JS/CSS

### ISSUE THREAD

**Issue by ankush** [frappe/print_designer#19]
https://github.com/frappe/print_designer/blob/cddb2baa2c3436492e51c20c6b568814346fe243/print_designer/hooks.py#L14-L15

This is added in default JS/CSS. Is it _really_ required by default?

**Comment by ankush** [comment]
@maharshivpatel easy to fix in framework 😄 

Use localForage instead of localStorage, it was added for this problem only.

**Comment by maharshivpatel** [comment]
pdf.worker.bundle.js can't be lazy loaded because of the way pdfjs worker is used in pdfjs ( will need to add npm package someday ) css and others js are lazy loaded.
