### ISSUE TITLE
Feature Request: Web View Support

### ISSUE THREAD

**Issue by yamenzk** [frappe/print_designer#191]
Currently the web-view of print formats generated via designer seems broken (specially within the header and footer).
It would be nice to have a print format that is identical on prints, pdf as well as web view.

**Comment by maharshivpatel** [comment]
@yamenzk i didn't understand what you mean by web view. can you share example.

**Comment by yamenzk** [comment]
Hello!
I will share an example directly from my instance, please let me know when you see it so I can remove the link. 
You can get the web view by clicking on "Full Page" from a print format
![Screenshot_20240314_073625_Chrome](https://github.com/frappe/print_designer/assets/98694759/ec21370f-2776-41db-bd4c-10212620155a)

We usually share these with our clients/suppliers, specially via SMS or for requesting e-signatures without them needing to have a user.

Please check the web view link below and you can use the e-signature form to sign it if you want. 

[Purchase Receipt Web View](https://eserv.mirageclinics.com/printview?doctype=Purchase%20Receipt&name=MC-PR24081&format=%5BMC%5D%20Purchase%20Receipt&no_letterhead=0&letterhead=%5BMC%5D%20Letterhead&settings=%7B%7D&_lang=en)

Also try to print/export as PDF and see how almost the webview, print and pdf are almost identical.

However, I tested this using Print Designer on Job Applicant, here are the results:
PDF (Print Designer):
![Screenshot_20240314_074553_Adobe Acrobat](https://github.com/frappe/print_designer/assets/98694759/9a7a3b15-07bf-4554-9166-19beed6810eb)

Web View (Print Designer)
![Screenshot_20240314_074744_Chrome~2](https://github.com/frappe/print_designer/assets/98694759/3e2ab44c-0805-4173-8f37-75328a908c6b)

**Comment by maharshivpatel** [comment]
@yamenzk is it fine if we send pdf link instead of printview to customers ? print designer is not suppose to work with html. it is supposed to work only with pdfs

**Comment by yamenzk** [comment]
You mean something like [Adobe Document Cloud](https://www.adobe.com/ae_en/documentcloud.html) where we can share a pdf link and people can fill & sign online?

**Comment by maharshivpatel** [comment]
i mean, printview doesn't have any signing capability right ? so users must be generating pdf from their browser and signing them. 

what if you send them pdf link directly where they can download and sign it.

**Comment by yamenzk** [comment]
It does, print webview is amazing to add HTML/JS and even run API calls directly from the print format. The benefit of this is we can request e-signatures from clients/suppliers directly on documents. 

[Please sign this document](https://eserv.mirageclinics.com/printview?doctype=Purchase%20Receipt&name=MC-PR24081&format=%5BMC%5D%20Purchase%20Receipt&no_letterhead=0&letterhead=%5BMC%5D%20Letterhead&settings=%7B%7D&_lang=en)

**Comment by maharshivpatel** [comment]
i don't have the permission 😅

**Comment by yamenzk** [comment]
Woops! I shared the wrong link
[Try now](https://eserv.mirageclinics.com/Purchase%20Receipt/MC-PR24081?key=ad9f99dd4d9c580956c2c9e2bb973da93d58b59b7d37a66d1c1fc2ab)

**Comment by maharshivpatel** [comment]
@yamenzk got it. let me think how this can be solved. 

there is 1 workaround where you just create separate format for signing and if you load that format in printview just embed pdf instead of html above sign 😅

i will think of better way but this is something you can do in the meantime.

**Comment by yamenzk** [comment]
Yeah that's why I was wondering if Print Designer can generate HTML friendly results that will allow us to benefit from webview

**Comment by maharshivpatel** [comment]
@yamenzk i will find some solution but just a suggestion create portal pages and load pdf and sign field on it instead of modifying printview.

**Comment by yamenzk** [comment]
That is definitely a solution, but I find it more convenient like this, every document can be signed directly from the print format. 

It's totally not an urgent feature, my current solution is working but soon, I want to ditch the old print formats and start working with designer

**Comment by yamenzk** [comment]
Also great work on this ❤️
