### ISSUE TITLE
print designer page not found

### ISSUE THREAD

**Issue by classita** [frappe/print_designer#192]
i had installed the print designer into my erpnext v15. but i do facing a problem when running the apps.

please assist 

![print-designer](https://github.com/frappe/print_designer/assets/163496841/ce967ec2-f212-40c4-b0f0-10b8b3053baf)

**Comment by maharshivpatel** [comment]
@classita  Please migrate your site and restart the bench

**Comment by classita** [comment]
ok now. Thanks
