### ISSUE TITLE
import { createPinia } from "pinia"; frappe.exceptions.ValidationError: Invalid file path: print_designer.bundle.js

### ISSUE THREAD

**Issue by Doreen2002** [frappe/print_designer#2]

**Comment by maharshivpatel** [comment]
Print Designer is only supported with frappe framework on develop branch. please make sure you are using latest develop version.

**Comment by maharshivpatel** [comment]
can you please provide the full traceback.

**Comment by maharshivpatel** [comment]
Please note that print designer is only compatible with develop version of frappe framework. closing this issue. if you are still getting the error reopen and share the full traceback.
