### ISSUE TITLE
print_designer issue

### ISSUE THREAD

**Issue by nobychenjoseph** [frappe/print_designer#201]
I'm using a self-hosted ERPNext instance with versions ERPNext v15.17.1 (version-15) and Frappe Framework v15.18.0 (version-15). Following the instructions on GitHub, I successfully installed the print-designer app without encountering any errors. However, when I type 'print designer' into the Awesome Bar, no suggestions or indications of the app appear. I'm unsure what steps to take next to address this issue. Can you please provide assistance?

**Comment by IvanGuevaraM** [comment]
Did you?
```
Bench --site yourdomain.com install-app print_designer
bench update --build
```
Then open
.../app/print-designer

**Comment by nobychenjoseph** [comment]
bench start
bench new-site print-designer.test
bench --site print-designer.test add-to-hosts
bench get-app https://github.com/frappe/print_designer
bench --site print-designer.test install-app print_designer        

Above commands i have passed sir...

**Comment by maharshivpatel** [comment]
@nobychenjoseph please migrate the site and restart then bench

```
bench --site print-designer.test migrate
```
```
bench restart
```

**Comment by nobychenjoseph** [comment]
when i pass  sudo  Bench --site http://192.168.29.126 install-app print_designer
the error shows that  Bench: command not found

**Comment by nobychenjoseph** [comment]
Thank you its done now
