### ISSUE TITLE
Payment Entry not able to delete 

### ISSUE THREAD

**Issue by nobychenjoseph** [frappe/print_designer#202]
Cannot delete or cancel because Sales Invoice [ACC-SINV-2024-00026](http://192.168.29.126/app/Form/Sales%20Invoice/ACC-SINV-2024-00026) is linked with Payment Ledger Entry [34a4871756]. this is happens. when i go to 34a4871756 (Ledger entry). i am not able to delete it. because this invoice was made by mistake. i should delete this
what to do. There is no option to delete it. can you give me the guidance to delete it?   my version is                   ERPNext: v15.17.4 (version-15)

Frappe Framework: v15.18.0 (version-15)

**Comment by maharshivpatel** [comment]
@nobychenjoseph This repo is for print_desginer. your question is not related to it.

Also, use [discuss.frappe.io](https://discuss.frappe.io/) for asking functional queries ( How to )

Thank you.
