### ISSUE TITLE
preview before printing is getting this error ! please help

### ISSUE THREAD

**Issue by yousef-shpair** [frappe/print_designer#203]
![Screenshot 2024-03-26 004947](https://github.com/frappe/print_designer/assets/136029636/f89fa4b5-d3a9-4ce4-bf91-5ea8bd6b26dd)

**Comment by maharshivpatel** [comment]
@yousef-shpair please open the error log and check the error. if you can't figure out you can copy-paste to share the error here

**Comment by yousef-shpair** [comment]
there is no error log created to it error log is empty 

We need to use the application... Please help me

I downloaded it, but when displayed, it does not work. Perhaps it works by connecting to another party

What is the problem with Google fonts?

It has not been addressed by you yet

Is there another application installed on the operating system?

**Comment by abdopcnet** [comment]
hello mr maharshivpatel
thank you for this perfect app

my server is on contabo vps alone
one site with static ip
demo.future-support.online
administrator
123123

i tried installing a lot of times

but i cant  at all
i tried 
apt install -y libffi-dev && \
apt install -y libssl-dev && \
apt install -y libxrender1 && \
apt install -y libfontconfig && \
apt install -y fontconfig && \
apt install -y xvfb && \
apt install -y xfonts-base && \
apt install -y xfonts-75dpi && \
apt install -y python3-pdfkit && \
apt install -y python3-django-wkhtmltopdf && \
apt install -y wkhtmltopdf


2.also tried 
xvfb wkhtmltopdf libfontconfig

gives 
wkhtmltopdf --version
wkhtmltopdf 0.12.6.1

3.also tried 
wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-3/wkhtmltox_0.12.6.1-3.jammy_amd64.deb
sudo dpkg -i wkhtmltox_0.12.6.1-3.jammy_amd64.deb
gives
wkhtmltopdf --version
wkhtmltopdf 0.12.6.1 (with patched qt)

in did all tries every time on clean install
no luck

please can you give us the installion and how to run it

**Comment by maharshivpatel** [comment]
you need to share minimum reproducible demo in order for me to help you. basically share url to exact format with document where this error happens.

Please check this video on how to use it : https://youtu.be/XpmrLzbianE?feature=shared&t=135

please have in mind that it is not optimised for RTL layout yet. 

also, please delete the comment later on as it has your credentials.

**Comment by abdopcnet** [comment]
it is demo no problem

i watch all videos i cant make it work

it doesnt preview any format after designing ? why ?

**Comment by maharshivpatel** [comment]
your site is not in english so i am unable to navigate and find the format on my own that is causing the issue. please share the link here where you are facing the issue.

**Comment by abdopcnet** [comment]
i converted to admin user to english
also i created sales invoice profile
here
https://demo.future-support.online/app/print-designer/test-printdesigner

**Comment by abdopcnet** [comment]
also this is another demo
https://erp15.aystest.online/app/home
administrator
123123

**Comment by maharshivpatel** [comment]
@abdopcnet works fine for me 😅

<img width="1289" alt="Screenshot 2024-03-27 at 1 21 00 AM" src="https://github.com/frappe/print_designer/assets/39730881/36af9e20-94db-4c0c-9d98-039a5de28d03">

**Comment by abdopcnet** [comment]
![image](https://github.com/frappe/print_designer/assets/48860652/50c7679a-3905-46bc-a2fe-583050c257af)

its not working !!!

**Comment by abdopcnet** [comment]
where is the problem ?

**Comment by maharshivpatel** [comment]
@abdopcnet can you press f12 when you get this error and share the screenshot.

**Comment by abdopcnet** [comment]
![image](https://github.com/frappe/print_designer/assets/48860652/fb739c2a-3dc1-4881-8b15-b8005107db7b)

**Comment by abdopcnet** [comment]
**maharshivpatel !

is there any solutions ?

how to make it work ?**

**Comment by abdopcnet** [comment]
**maharshivpatel !

is there any solutions ?

how to make it work ?**

i installed the system more times with no luck 

how to make it work ?


###################################################################################
sudo apt-get install -y \
  libpango1.0-dev \
  libjpeg-dev \
  libgif-dev \
  librsvg2-dev \

  libcairo2 \
  libcairo2-dev \
  libcairo2-ocaml \

  xvfb \
  libfontconfig \
  fontconfig \
  xfonts-base \
  xfonts-utils \
  xfonts-75dpi \
  xfonts-encodings \

  libfontenc1 \
  libffi-dev \
  libxrender1 \
  libxrender-dev \
  libx11-dev \
  libxext-dev \
  libfreetype6-dev \
  libfontconfig1-dev
####################################
wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-3/wkhtmltox_0.12.6.1-3.jammy_amd64.deb
sudo dpkg -i wkhtmltox_0.12.6.1-3.jammy_amd64.deb

# Verify the installation
wkhtmltopdf --version
wkhtmltopdf 0.12.6.1 (with patched qt)
####################################
please help ?

**Comment by abdopcnet** [comment]
sometimes it work then stops again ?

**Comment by abdopcnet** [comment]
![image](https://github.com/frappe/print_designer/assets/48860652/2ef28a59-d954-4985-aad6-0fba8353ab13)

**Comment by abdopcnet** [comment]
![image](https://github.com/frappe/print_designer/assets/48860652/5563ac37-0834-4db5-af6c-e21354f8d599)

**Comment by abdopcnet** [comment]
work on 
![image](https://github.com/frappe/print_designer/assets/48860652/42f28299-1e9e-46c7-ac8f-aea1eb7e16fb)

**Comment by abdopcnet** [comment]
work on vivaldi
![image](https://github.com/frappe/print_designer/assets/48860652/58e15182-ad70-41f0-afa3-1cefae75973a)

**Comment by abdopcnet** [comment]
work ok with google chrome in mobile
![image](https://github.com/frappe/print_designer/assets/48860652/e268e4f9-c1af-43fe-84a5-e1b7c35d9689)

**Comment by abdopcnet** [comment]
vivaldi browser on computer not working
![image](https://github.com/frappe/print_designer/assets/48860652/c6407fb1-3025-4c4e-89a8-c2048a889767)

**Comment by abdopcnet** [comment]
this is the erros i see in firefox developer
despite the print preview work ok !
![image](https://github.com/frappe/print_designer/assets/48860652/5f171146-e37c-4c27-8b98-fe86bae67b43)

**Comment by maharshivpatel** [comment]
> this is the erros i see in firefox developer despite the print preview work ok ! ![image](https://private-user-images.githubusercontent.com/48860652/317941266-b1b8e98e-725b-4165-baa3-42f6f42d17c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2ODMxODAsIm5iZiI6MTcxMTY4Mjg4MCwicGF0aCI6Ii80ODg2MDY1Mi8zMTc5NDEyNjYtYjFiOGU5OGUtNzI1Yi00MTY1LWJhYTMtNDJmNmY0MmQxN2M3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDAzMjgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4MDQxZDA5NTI1N2UxNTViMTkyYjhjOGQ1ZDFhMTIwZjVjNDIxOWZkNjYzMDgxZmEzMzQ3ZDVkNWQ4ZDhjZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T859mFjdWxHj0WfRxwkX4KWZlDCZzxhJ-jwPDWexTiA)
> 
> ![image](https://private-user-images.githubusercontent.com/48860652/317941655-039aadac-162c-4573-908d-00ea18a9ce48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2ODMxODAsIm5iZiI6MTcxMTY4Mjg4MCwicGF0aCI6Ii80ODg2MDY1Mi8zMTc5NDE2NTUtMDM5YWFkYWMtMTYyYy00NTczLTkwOGQtMDBlYTE4YTljZTQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDAzMjgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkMTRiZTVjZjU0OTVlMzdhZmM3YzU3MjkwMmU0YzE4ZDAxN2JkZDk0ODE2Yjc2NjEzYjkwN2VjNDYzODc2YzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._3fGI0IecSq2I8_5C3JmeoVFPjl7AvZ8xVwUc6aVsOE)
> 
> ![image](https://private-user-images.githubusercontent.com/48860652/317941820-54ec4391-969c-4220-9bd3-28d893ac1220.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2ODMxODAsIm5iZiI6MTcxMTY4Mjg4MCwicGF0aCI6Ii80ODg2MDY1Mi8zMTc5NDE4MjAtNTRlYzQzOTEtOTY5Yy00MjIwLTliZDMtMjhkODkzYWMxMjIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDAzMjgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkZDhiOWRjNzA4YjUzMWExNjNhZDEyOWJjYmY3YmNjMmFiOTdhMTU5NzI4YTJhYzAwZTcwMjQ0NWU1NDVlOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XfPNl_ia8Ym4jqAAdM9RXD_BS_EIpyXPJcBkBVY7a8k)
> 
> ![image](https://private-user-images.githubusercontent.com/48860652/317941863-f5f2f207-56c1-4c8e-b828-90193154ecff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2ODMxODAsIm5iZiI6MTcxMTY4Mjg4MCwicGF0aCI6Ii80ODg2MDY1Mi8zMTc5NDE4NjMtZjVmMmYyMDctNTZjMS00YzhlLWI4MjgtOTAxOTMxNTRlY2ZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDAzMjgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5NGY5Njg3MzlkMTJjMjg4Nzc2YjZjYTA0ZGU2OGQ3YzE2Yzk1MDkxYTk2OGUwNGJlYzE1YTQxYzc4NDBkN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B3L_jlRB1PZqdZeOxxPad1gK7PPhKFsUVNHUHh_1qGE)
> 
> ![image](https://private-user-images.githubusercontent.com/48860652/317941903-22691bba-68d9-4cee-8204-59880de71a5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2ODMxODAsIm5iZiI6MTcxMTY4Mjg4MCwicGF0aCI6Ii80ODg2MDY1Mi8zMTc5NDE5MDMtMjI2OTFiYmEtNjhkOS00Y2VlLTgyMDQtNTk4ODBkZTcxYTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDAzMjgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzN2JkMjc3ZjQ2MWYwZDI1ZWM0YTJiZWZkZDkwNDY0MWRiZGIwYWY1NTk0YjljNWM2N2U1ZWJjNzc0M2MxNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OkaNE513bw5kzg3onlKXduobK5EKqh3bLvD10kMmb38)
> 
> ![image](https://private-user-images.githubusercontent.com/48860652/317941938-9368e25f-7435-40dc-a2b6-bb9233c256e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2ODMxODAsIm5iZiI6MTcxMTY4Mjg4MCwicGF0aCI6Ii80ODg2MDY1Mi8zMTc5NDE5MzgtOTM2OGUyNWYtNzQzNS00MGRjLWEyYjYtYmI5MjMzYzI1NmU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDAzMjgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkMzJhNDY0ZTlhNjgxYTM3YTNkOGM1NTUwNjJkM2IyZmMyMDYwMTU3OTZmM2Y1MjJkMWFjNTUzNTY5NjU0ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Xij424HsOsqaJ46bTPOntG4xd4-_XuC1HErh8KdfTc0)

This errors are fine. ignore it.

**Comment by abdopcnet** [comment]
![image](https://github.com/frappe/print_designer/assets/48860652/ea87076e-e46b-4198-a725-e3cbc896a820)

**Comment by maharshivpatel** [comment]
@abdopcnet It is most likely some ad blocker extension that you have https://www.keycdn.com/support/how-to-solve-err-blocked-by-client

I am closing this as it doesn't look related to print_designer but if you feel this is related to print_designer. please create a new issue. Thank you.
