### ISSUE TITLE
Preview header and footer missing

### ISSUE THREAD

**Issue by classita** [frappe/print_designer#204]
the header and footer disappear from the print preview.

please assist.

**Comment by maharshivpatel** [comment]
@classita please install the correct / latest version of wkhtmltopdf with qt patched

[https://wkhtmltopdf.org/downloads.html 10](https://wkhtmltopdf.org/downloads.html)

**Comment by classita** [comment]
hello Maharshi Patel,

current version wkhtmltopdf 0.12.6

**Comment by maharshivpatel** [comment]
@classita you have wkhtmltopdf which is **not** ( with patched qt )

```
wkhtmltopdf --version
```

output should be similar to `wkhtmltopdf 0.12.6 (with patched qt)`

Install correct version by following [installation guide](https://frappeframework.com/docs/user/en/installation) and confirm

**Comment by maharshivpatel** [comment]
@classita I hope this solved your issue.

**Comment by classita** [comment]
solved. thanks

**Comment by classita** [comment]
Hi Maharshi Patel,

as my current print_designer version was 1.2.0how to upgrade to the latest version?

erpnext 15.31.4
frappe 15.36.1
frappe_pdf 0.0.1
hrms 16.0.0-dev
it_management 0.0.1
payments 0.0.1
print_designer 1.2.0
