### ISSUE TITLE
bug: only render new line if value is present

### ISSUE THREAD

**Issue by maharshivpatel** [frappe/print_designer#206]
https://discuss.frappe.io/t/print-designer-customer-address/119950

**Comment by vanukw** [comment]
@maharshivpatel ,

Please check **Country** also, I notice it's blank 
![image](https://github.com/frappe/print_designer/assets/6521432/a5e5e23a-bf6b-4c52-ae80-166528a58a61)

Also, I have a custom field called state and type is link which is  not showing in the customer Address, Assume both related to the Type of the field.

**Comment by maharshivpatel** [comment]
@vanukw please check once https://youtu.be/XpmrLzbianE?feature=shared . bug i will fix tomorrow
