### ISSUE TITLE
Current Page, Total Pages, Print Date & Print Time not show

### ISSUE THREAD

**Issue by bobotdls** [frappe/print_designer#218]
Before I use the v.1 but the Current Page, Total Pages, Print Date & Print Time not show
Then I see that you have a new version, I thought it was just a bugs, Right now I'am using v1.1.0 still same not showing 
Current Page, Total Pages, Print Date & Print Time not show

**Comment by maharshivpatel** [comment]
@bobotdls Current Page, Total Pages, Print Date & Print Time only shows if you they are in header / footer.

please make sure they are in header/footer area.

**Comment by bobotdls** [comment]
Yup they are in the footer but  it's not show

**Comment by hmb47** [comment]
the same issue

**Comment by hmb47** [comment]
> 1.1.0 
no, before 1.1.0

**Comment by bobotdls** [comment]
even before 1.1.0

**Comment by bobotdls** [comment]
but I remember on Frappe v. 14 before I still can use the page now I'am using v.15

**Comment by bobotdls** [comment]
ERPNext: v15.17.0 (version-15)

Frappe Framework: v15.17.3 (version-15)

Print Designer: v1.0.0 (main)

on that version above the Current Page, Total Pages, Print Date & Print Time is showing fine

but below version 

ERPNext: v15.19.1 (version-15)

Frappe Framework: v15.20.0 (version-15)

Print Designer: v1.1.0 (main)

is not showing

**Comment by maharshivpatel** [comment]
sorry for the inconvenience this slipped through the recent refactor.
fixed now will be available in the next week's release.

**Comment by bobotdls** [comment]
ok thanks
