### ISSUE TITLE
Issue in displaying page

### ISSUE THREAD

**Issue by chetan-SMRI** [frappe/print_designer#222]
I was getting the page printed normally after setting up all the things including wkhtmltopdf to latest version.
then i just adjusted some text and added some new text, then i got this issue.
**TRACEBACK**
`Traceback with variables (most recent call last):
  File "apps/frappe/frappe/core/doctype/file/utils.py", line 358, in attach_files_to_document
    file.insert(ignore_permissions=True)
      doc = <PDPrintFormat: Sales Invoice>
      event = 'on_update'
      attach_fields = [<Attach ImageDocField: print_designer_preview_img parent=Print Format>]
      df = <Attach ImageDocField: print_designer_preview_img parent=Print Format>
      value = '/private/files/print_designer-sales_invoice-preview.jpg'
      unattached_file = None
      file = <File: unsaved>
  File "apps/frappe/frappe/model/document.py", line 283, in insert
    self.run_method("before_insert")
      self = <File: unsaved>
      ignore_permissions = True
      ignore_links = None
      ignore_if_duplicate = False
      ignore_mandatory = None
      set_name = None
      set_child_names = True
  File "apps/frappe/frappe/model/document.py", line 959, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
      self = <File: unsaved>
      method = 'before_insert'
      args = ()
      kwargs = {}
      fn = <function Document.run_method.<locals>.fn at 0x7f170b2d74c0>
  File "apps/frappe/frappe/model/document.py", line 1319, in composer
    return composed(self, method, *args, **kwargs)
      self = <File: unsaved>
      args = ()
      kwargs = {}
      hooks = []
      method = 'before_insert'
      doc_events = {'*': {'on_update': ['frappe.desk.notifications.clear_doctype_notifications', 'frappe.workflow.doctype.workflow_action.workflow_action.process_workflow_actions', 'frappe.core.doctype.file.utils.attach_files_to_document', 'frappe.automation.doctype.assignment_rule.assignment_rule.apply', 'frappe.automation.doctype.assignment_rule.assignment_rule.update_due_date', 'frappe.core.doctype.user_type.user_type.apply_permissions_for_non_standard_user_type'], 'after_rename': ['frappe.desk.notifications.clear_doctype_notifications'], 'on_cancel': ['frappe.desk.notifications.clear_doctype_notifications', 'frappe.workflow.doctype.workflow_action.workflow_action.process_workflow_actions', 'frappe.automation.doctype.assignment_rule.assignment_rule.apply'], 'on_trash': ['frappe.desk.notifications.clear_doctype_notifications', 'frappe.workflow.doctype.workflow_action.workflow_action.process_workflow_actions'], 'on_update_after_submit': ['frappe.workflow.doctype.workflow_action.workflow_action.process_w...
      composed = <function Document.hook.<locals>.compose.<locals>.runner at 0x7f170ab10860>
      compose = <function Document.hook.<locals>.compose at 0x7f170ab10e00>
      f = <function Document.run_method.<locals>.fn at 0x7f170b2d74c0>
  File "apps/frappe/frappe/model/document.py", line 1301, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
      self = <File: unsaved>
      method = 'before_insert'
      args = ()
      kwargs = {}
      add_to_return_value = <function Document.hook.<locals>.add_to_return_value at 0x7f170ab11760>
      fn = <function Document.run_method.<locals>.fn at 0x7f170b2d74c0>
      hooks = ()
  File "apps/frappe/frappe/model/document.py", line 956, in fn
    return method_object(*args, **kwargs)
      self = <File: unsaved>
      args = ()
      kwargs = {}
      method_object = <bound method File.before_insert of <File: unsaved>>
      method = 'before_insert'
  File "apps/frappe/frappe/core/doctype/file/file.py", line 103, in before_insert
    self.save_file(content=self.get_content())
      self = <File: unsaved>
  File "apps/frappe/frappe/core/doctype/file/file.py", line 534, in get_content
    with open(file_path, mode="rb") as f:
      self = <File: unsaved>
      file_path = './192.168.29.37/private/files/print_designer-sales_invoice-preview.jpg'
builtins.FileNotFoundError: [Errno 2] No such file or directory: './192.168.29.37/private/files/print_designer-sales_invoice-preview.jpg'`

However if i visit the folder, then i can see the file being saved, but i guess the file is being modified when the software tries to fetch it, can you please tell me how to correct it?

**Comment by maharshivpatel** [comment]
@chetan-SMRI  are you creating a standard format?

**Comment by chetan-SMRI** [comment]
I don't understand what you wanted to say, I had created one sales invoice
template using designer and then selected it in the print format, earlier
it was visible and was working fine but when I just made some
small changes, then it stopped working and gave the above issue.
If you are comfortable then we can discuss this on whatsapp aswell.
https://wa.me/918989153870

**Comment by chetan-SMRI** [comment]
hi, @maharshivpatel sir, please advise me what can i do for this? attaching screenshot for both print designer and error page.
![image](https://github.com/frappe/print_designer/assets/84266613/00ecf070-52b2-409b-b105-315b817e33f3)
![image](https://github.com/frappe/print_designer/assets/84266613/bcc85ed7-866e-4cf2-ba3f-19fd6ebb75e6)
![image](https://github.com/frappe/print_designer/assets/84266613/36a1a1ee-e3cf-40f8-8bea-360d1f63d4be)

**Comment by maharshivpatel** [comment]
@chetan-SMRI please share the full error.

**Comment by chetan-SMRI** [comment]
It's the whole error log which I sent in first message, if their is any
other error log then please let me know, I will try to fetch it for you.

**Comment by chetan-SMRI** [comment]
> @chetan-SMRI please share the full error.

hi, can you please tell me what i can do further?

**Comment by maharshivpatel** [comment]
@chetan-SMRI this is not full error traceback !! please copy the full text and paste it here.

![image](https://github.com/frappe/print_designer/assets/39730881/aeb430ee-1d8d-4e7f-a51c-034d81913b15)

**Comment by maharshivpatel** [comment]
@chetan-SMRI please open this link and share the error http://192.168.29.37:8000/printview?doctype=Sales%20Invoice&name=000001&format=Sales%20Invoice&no_letterhead=0

**Comment by chetan-SMRI** [comment]
hi, it doesnt give any issue when i go to the link you mentioned, but when i am trying to go to sales invoice-> selecting invoice-> printing invoice - > then i am getting the issue
![image](https://github.com/frappe/print_designer/assets/84266613/a1f1b41c-a777-4ffb-ba39-55ce9017c93e)
![image](https://github.com/frappe/print_designer/assets/84266613/6c7a54d9-aa96-4cd3-99f0-a2609383f164)

**Comment by maharshivpatel** [comment]
@chetan-SMRI As discussed over the telegram issue is with your jinja code. you haven't set any variable called customer. you need to fetch customer using [custom data feature](https://github.com/frappe/print_designer/pull/115) and then you use it.

**Comment by WavesSkipper** [comment]
Hello, is there any solution for that ?

Also while I’m creating the print format, it stuck and generate the error below in error log then the header part of the report will disappear

Traceback with variables (most recent call last):
File “apps/frappe/frappe/core/doctype/file/utils.py”, line 358, in attach_files_to_document
file.insert(ignore_permissions=True)
doc = <PDPrintFormat: Sales Invoice 02>
event = ‘on_update’
attach_fields = []
df =
value = ‘/private/files/print_designer-sales_invoice_02-preview419306.jpg’
unattached_file = None
file = <File: unsaved>
File “apps/frappe/frappe/model/document.py”, line 283, in insert
self.run_method(“before_insert”)
self = <File: unsaved>
ignore_permissions = True
ignore_links = None
ignore_if_duplicate = False
ignore_mandatory = None
set_name = None
set_child_names = True
File “apps/frappe/frappe/model/document.py”, line 960, in run_method
out = Document.hook(fn)(self, *args, **kwargs)
self = <File: unsaved>
method = ‘before_insert’
args = ()
kwargs = {}
fn = <function Document.run_method..fn at 0x7f1eeede2520>
File “apps/frappe/frappe/model/document.py”, line 1320, in composer
return composed(self, method, args, **kwargs)
self = <File: unsaved>
args = ()
kwargs = {}
hooks = []
method = ‘before_insert’
doc_events = {'': {‘on_update’: [‘frappe.desk.notifications.clear_doctype_notifications’, ‘frappe.workflow.doctype.workflow_action.workflow_action.process_workflow_actions’, ‘frappe.core.doctype.file.utils.attach_files_to_document’, ‘frappe.automation.doctype.assignment_rule.assignment_rule.apply’, ‘frappe.automation.doctype.assignment_rule.assignment_rule.update_due_date’, ‘frappe.core.doctype.user_type.user_type.apply_permissions_for_non_standard_user_type’], ‘after_rename’: [‘frappe.desk.notifications.clear_doctype_notifications’], ‘on_cancel’: [‘frappe.desk.notifications.clear_doctype_notifications’, ‘frappe.workflow.doctype.workflow_action.workflow_action.process_workflow_actions’, ‘frappe.automation.doctype.assignment_rule.assignment_rule.apply’], ‘on_trash’: [‘frappe.desk.notifications.clear_doctype_notifications’, ‘frappe.workflow.doctype.workflow_action.workflow_action.process_workflow_actions’], ‘on_update_after_submit’: ['frappe.workflow.doctype.workflow_action.workflow_action.process_w…
composed = <function Document.hook..compose..runner at 0x7f1eeede25c0>
compose = <function Document.hook..compose at 0x7f1eeede1940>
f = <function Document.run_method..fn at 0x7f1eeede2520>
File “apps/frappe/frappe/model/document.py”, line 1302, in runner
add_to_return_value(self, fn(self, *args, **kwargs))
self = <File: unsaved>
method = ‘before_insert’
args = ()
kwargs = {}
add_to_return_value = <function Document.hook..add_to_return_value at 0x7f1eeede1d00>
fn = <function Document.run_method..fn at 0x7f1eeede2520>
hooks = ()
File “apps/frappe/frappe/model/document.py”, line 957, in fn
return method_object(*args, **kwargs)
self = <File: unsaved>
args = ()
kwargs = {}
method_object = <bound method File.before_insert of <File: unsaved>>
method = ‘before_insert’
File “apps/frappe/frappe/core/doctype/file/file.py”, line 103, in before_insert
self.save_file(content=self.get_content())
self = <File: unsaved>
File “apps/frappe/frappe/core/doctype/file/file.py”, line 534, in get_content
with open(file_path, mode=“rb”) as f:
self = <File: unsaved>
file_path = ‘./ggdev.waves-skipper.com/private/files/print_designer-sales_invoice_02-preview419306.jpg’
builtins.FileNotFoundError: [Errno 2] No such file or directory: ‘./ggdev.waves-skipper.com/private/files/print_designer-sales_invoice_02-preview419306.jpg’

**Comment by samy4sam** [comment]
@chetan-SMRI 
Can you please share your solution?
