### ISSUE TITLE
while Designing the format I can only use a single page

### ISSUE THREAD

**Issue by DhruthiBoddupelli** [frappe/print_designer#228]
Not able to use multiple pages for design or text fields if not assigned a box for the complete text is not displaying

**Comment by maharshivpatel** [comment]
@DhruthiBoddupelli please share more details and screenshot as i am unable to understand the issue.

**Comment by maharshivpatel** [comment]
@DhruthiBoddupelli closing there isn't enough information to work on it. 
If you are still facing the issue then please feel free to open another issue with details, Thank you.
