### ISSUE TITLE
Export Design from Dev to Prod Environment

### ISSUE THREAD

**Issue by moizsami** [frappe/print_designer#234]
Hi,

For some of my clients we usually create two environments, one for testing and development and another which is the production environment.

Currently I am creating a new print design using the Print Designer, but finding no option to export this design to my production environment. Can we expect this feature soon? else I would have to create it manually which is not the optimal solution.

Thanks.

**Comment by maharshivpatel** [comment]
@moizsami you can export and import using standard framework feature. just copy like this and paste on prod environment. https://github.com/frappe/print_designer/issues/225#issuecomment-2044517602

**Comment by moizsami** [comment]
> @moizsami you can export and import using standard framework feature. just copy like this and paste on prod environment. [#225 (comment)](https://github.com/frappe/print_designer/issues/225#issuecomment-2044517602)

Wow, didnt know, thanks
