### ISSUE TITLE
cannot install it in docker image for  ARM64 devices

### ISSUE THREAD

**Issue by sudhegan** [frappe/print_designer#239]
when i try to install print designer in docker image for ARM64 host it throws error on yarn install --check-files cmd

but it installs fine in amd64

the error as follows

>$ cd frontend && yarn install --check-files
2705.6 yarn install v1.22.22
2705.6 [1/4] Resolving packages...
2705.6 [2/4] Fetching packages...
2705.6 info There appears to be trouble with your network connection. Retrying...
2705.6 info There appears to be trouble with your network connection. Retrying...
2705.6 info There appears to be trouble with your network connection. Retrying...
2705.6 info There appears to be trouble with your network connection. Retrying...
2705.6 info There appears to be trouble with your network connection. Retrying...
2705.6 info There appears to be trouble with your network connection. Retrying...
2705.6 info There appears to be trouble with your network connection. Retrying...
2705.6 info There appears to be trouble with your network connection. Retrying...
2705.6 info There appears to be trouble with your network connection. Retrying...
2705.6 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
2705.6 info There appears to be trouble with your network connection. Retrying...
2705.6 info There appears to be trouble with your network connection. Retrying...
2705.6 info There appears to be trouble with your network connection. Retrying...
2705.6 info There appears to be trouble with your network connection. Retrying...
2705.6 info There appears to be trouble with your network connection. Retrying...
2705.6 info There appears to be trouble with your network connection. Retrying...
2705.6 info There appears to be trouble with your network connection. Retrying...
2705.6 info There appears to be trouble with your network connection. Retrying...
2705.6 info There appears to be trouble with your network connection. Retrying...
2705.6 verbose 852.672362179 Error: Command failed with exit code 1.
2705.6     at ProcessTermError.ExtendableBuiltin (/home/frappe/.nvm/versions/node/v18.20.0/lib/node_modules/yarn/lib/cli.js:721:66)
2705.6     at ProcessTermError.MessageError (/home/frappe/.nvm/versions/node/v18.20.0/lib/node_modules/yarn/lib/cli.js:750:123)
2705.6     at new ProcessTermError (/home/frappe/.nvm/versions/node/v18.20.0/lib/node_modules/yarn/lib/cli.js:790:113)
2705.6     at /home/frappe/.nvm/versions/node/v18.20.0/lib/node_modules/yarn/lib/cli.js:34408:30
2705.6     at Generator.throw (<anonymous>)
2705.6     at step (/home/frappe/.nvm/versions/node/v18.20.0/lib/node_modules/yarn/lib/cli.js:310:30)
2705.6     at /home/frappe/.nvm/versions/node/v18.20.0/lib/node_modules/yarn/lib/cli.js:323:13
2705.6     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2705.6 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
2705.6 subprocess.CalledProcessError: Command 'yarn install --check-files --verbose' returned non-zero exit status 1.
2705.6 
2705.6 The above exception was the direct cause of the following exception:
2705.6 
2705.6 Traceback (most recent call last):
2705.6   File "/usr/local/lib/python3.11/site-packages/bench/commands/make.py", line 75, in init
2705.6     init(
2705.6   File "/usr/local/lib/python3.11/site-packages/bench/utils/render.py", line 105, in wrapper_fn
2705.6     return fn(*args, **kwargs)
2705.6            ^^^^^^^^^^^^^^^^^^^
2705.6   File "/usr/local/lib/python3.11/site-packages/bench/utils/system.py", line 98, in init
2705.6     install_apps_from_path(apps_path, bench_path=path)
2705.6   File "/usr/local/lib/python3.11/site-packages/bench/app.py", line 1025, in install_apps_from_path
2705.6     get_app(
2705.6   File "/usr/local/lib/python3.11/site-packages/bench/app.py", line 772, in get_app
2705.6     app.install(verbose=verbose, skip_assets=skip_assets, restart_bench=restart_bench)
2705.6   File "/usr/local/lib/python3.11/site-packages/bench/utils/render.py", line 126, in wrapper_fn
2705.6     return fn(*args, **kwargs)
2705.6            ^^^^^^^^^^^^^^^^^^^
2705.6   File "/usr/local/lib/python3.11/site-packages/bench/app.py", line 255, in install
2705.6     install_app(
2705.6   File "/usr/local/lib/python3.11/site-packages/bench/app.py", line 915, in install_app
2705.6     bench.run(yarn_install, cwd=app_path)
2705.6   File "/usr/local/lib/python3.11/site-packages/bench/bench.py", line 48, in run
2705.6     return exec_cmd(cmd, cwd=cwd or self.cwd, _raise=_raise)
2705.6            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2705.6   File "/usr/local/lib/python3.11/site-packages/bench/utils/__init__.py", line 169, in exec_cmd
2705.6     raise CommandFailedError(cmd) from subprocess.CalledProcessError(return_code, cmd)
2705.6 bench.exceptions.CommandFailedError: yarn install --check-files --verbose
2705.6 
2705.6 ERROR: There was a problem while creating /home/frappe/frappe-bench

**Comment by maharshivpatel** [comment]
your docker container doesn't have access to the internet ! as the error says `2705.6 info There appears to be trouble with your network connection. Retrying...` . 

closing this as it is docker setup issue not related to print_designer app.

you can ask people on https://discuss.frappe.io/ and also checkout  https://github.com/frappe/frappe_docker/tree/main.

Thank you

**Comment by sudhegan** [comment]
actually the error i posted was wrong 

below is the actual error

`2135.4 $ node esbuild --production --run-build-command
2135.4 
2135.4 Error: Build failed with 2 errors:
2135.4 ../print_designer/print_designer/public/js/pdf.worker.min.js:22:25511: ER
ROR: Could not resolve "canvas"
2135.4 /home/frappe/frappe-bench/apps/frappe/esbuild/frappe-vue-style.js:10:41: 
ERROR: [plugin: frappe-vue-style] Cannot read properties of undefined (reading '
outputs')
2135.4     at failureErrorWithLog (/home/frappe/frappe-bench/apps/frappe/node_mo
dules/esbuild/lib/main.js:1624:15)
2135.4     at /home/frappe/frappe-bench/apps/frappe/node_modules/esbuild/lib/mai
n.js:1266:28
2135.4     at process.processTicksAndRejections (node:internal/process/task_queu
es:95:5)
2135.4 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about th
is command.
2135.4 subprocess.CalledProcessError: Command 'bench build' returned non-zero ex
it status 1.
2135.4 
2135.4 The above exception was the direct cause of the following exception:
2135.4 
2135.4 Traceback (most recent call last):
2135.4   File "/usr/local/lib/python3.11/site-packages/bench/commands/make.py", 
line 75, in init
2135.4     init(
2135.4   File "/usr/local/lib/python3.11/site-packages/bench/utils/render.py", l
ine 105, in wrapper_fn
2135.4     return fn(*args, **kwargs)
2135.4            ^^^^^^^^^^^^^^^^^^^
2135.4   File "/usr/local/lib/python3.11/site-packages/bench/utils/system.py", l
ine 112, in init
2135.4     build_assets(bench_path=path)
2135.4   File "/usr/local/lib/python3.11/site-packages/bench/utils/bench.py", li
ne 380, in build_assets
2135.4     exec_cmd(command, cwd=bench_path, env=env)
2135.4   File "/usr/local/lib/python3.11/site-packages/bench/utils/__init__.py",
 line 169, in exec_cmd
2135.4     raise CommandFailedError(cmd) from subprocess.CalledProcessError(retu
rn_code, cmd)
2135.4 bench.exceptions.CommandFailedError: bench build
2135.4 
2135.4 ERROR: There was a problem while creating /home/frappe/frappe-bench
`
