### ISSUE TITLE
bench build error for printdesigner in ARM64

### ISSUE THREAD

**Issue by sudhegan** [frappe/print_designer#240]
This is a followup issue of [#239 ]

the error i posted was worn
the below is the actual error

**it cannot resolve canvas in a js file i don't know what it is**

> yarn run v1.22.22
2135.4 $ node esbuild --production --run-build-command
2135.4 
2135.4 Error: Build failed with 2 errors:
2135.4 ../print_designer/print_designer/public/js/pdf.worker.min.js:22:25511: ER
ROR: Could not resolve "canvas"
2135.4 /home/frappe/frappe-bench/apps/frappe/esbuild/frappe-vue-style.js:10:41: 
ERROR: [plugin: frappe-vue-style] Cannot read properties of undefined (reading '
outputs')
2135.4     at failureErrorWithLog (/home/frappe/frappe-bench/apps/frappe/node_mo
dules/esbuild/lib/main.js:1624:15)
2135.4     at /home/frappe/frappe-bench/apps/frappe/node_modules/esbuild/lib/mai
n.js:1266:28
2135.4     at process.processTicksAndRejections (node:internal/process/task_queu
es:95:5)
2135.4 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about th
is command.
2135.4 subprocess.CalledProcessError: Command 'bench build' returned non-zero ex
it status 1.
2135.4 
2135.4 The above exception was the direct cause of the following exception:
2135.4 
2135.4 Traceback (most recent call last):
2135.4   File "/usr/local/lib/python3.11/site-packages/bench/commands/make.py", 
line 75, in init
2135.4     init(
2135.4   File "/usr/local/lib/python3.11/site-packages/bench/utils/render.py", l
ine 105, in wrapper_fn
2135.4     return fn(*args, **kwargs)
2135.4            ^^^^^^^^^^^^^^^^^^^
2135.4   File "/usr/local/lib/python3.11/site-packages/bench/utils/system.py", l
ine 112, in init
2135.4     build_assets(bench_path=path)
2135.4   File "/usr/local/lib/python3.11/site-packages/bench/utils/bench.py", li
ne 380, in build_assets
2135.4     exec_cmd(command, cwd=bench_path, env=env)
2135.4   File "/usr/local/lib/python3.11/site-packages/bench/utils/__init__.py",
 line 169, in exec_cmd
2135.4     raise CommandFailedError(cmd) from subprocess.CalledProcessError(retu
rn_code, cmd)
2135.4 bench.exceptions.CommandFailedError: bench build
2135.4 
2135.4 ERROR: There was a problem while creating /home/frappe/frappe-bench

**Comment by maharshivpatel** [comment]
@sudhegan please check FAQ No 3 : https://github.com/frappe/print_designer?tab=readme-ov-file#faq

**Comment by sudhegan** [comment]
Yes this solved the issue thanks
Sorry for not noticeing the faq
