### ISSUE TITLE
Changes in the data script disappear when switching to another browser window.

### ISSUE THREAD

**Issue by 2old4thisShit** [frappe/print_designer#241]
Hello, today I encountered a small but important issue.

While running a data script, if you switch to another window, the modified content disappears from the screen.

This is quite crucial because if you switch screens to check something in the documentation, for example, all unsaved changes made will disappear.

Attached video.

Thank you very much.

Frappe Builder: v1.x.x-develop () (develop)

Frappe Framework: v15.23.0 (version-15)

Testapp: v0.0.1 (develop)

https://github.com/frappe/print_designer/assets/46288096/ddda9e71-54c7-4c71-9d6e-35db229c00ce

**Comment by maharshivpatel** [comment]
@2old4thisShit wrong repo 😅

**Comment by 2old4thisShit** [comment]
> @2old4thisShit wrong repo 😅

hahaahaha sorry :D
