### ISSUE TITLE
Item table not break properly. Item Description overlapping while its more than one page. @maharshivpatel

### ISSUE THREAD

**Issue by smthakor1979** [frappe/print_designer#243]
Item table not break properly. Item Description overlapping while its more than one page. @maharshivpatel 

![image](https://github.com/frappe/print_designer/assets/66081909/b224c14d-ab7f-453c-b3c8-eed9ce4a9d30)

_Originally posted by @smthakor1979 in https://github.com/frappe/print_designer/issues/15#issuecomment-2051547761_

**Comment by maharshivpatel** [comment]
@smthakor1979 can you please share the format

**Comment by smthakor1979** [comment]
@maharshivpatel , please find the attachment.

[DIPL_069.pdf](https://github.com/frappe/print_designer/files/15153556/DIPL_069.pdf)

**Comment by maharshivpatel** [comment]
@smthakor1979  i need format to replicate the issue can you please share the format. also, if you can share the item description shown in the pdf that would be great.

### you share your format like this :
You can paste the data here ( change any personal info )

https://github.com/frappe/print_designer/assets/39730881/b7b761c7-a2b1-43d4-a3b3-0dde25ba9699

**Comment by itsdaveit** [comment]
This even happens with the templates delivered with the print designer, like:

print_designer/default_templates/erpnext/sales_order_pd_v2.json

Just create *one* item with a decription that long, it causes a page break.

This behaviour is also still present in the old print format system.

![image](https://github.com/frappe/print_designer/assets/9453135/1e874295-d564-46fd-906e-9598b1c46d57)

**Comment by maharshivpatel** [comment]
@itsdaveit as you pointed out yourself 

> This behaviour is also still present in the old print format system

This is caused by underlying library wkhtmltopdf there is nothing we can do here. i am still trying to find some workaround.

**Comment by maharshivpatel** [comment]
Issue is in wkhtmltopdf, not much we can do about it.
