### ISSUE TITLE
Page numbers in Footer

### ISSUE THREAD

**Issue by vanukw** [frappe/print_designer#244]
@maharshivpatel ,

How should I add page numbers in the footer section as bellow using print designer?

![image](https://github.com/frappe/print_designer/assets/6521432/85cd186a-cacd-4e06-ab06-19d5ffedea56)

Thank you

**Comment by maharshivpatel** [comment]
@vanukw please check this. also, you can use discussion for how to questions.

https://github.com/frappe/print_designer/assets/39730881/bb15befe-272d-4e63-943a-24e921c18f6a

**Comment by vanukw** [comment]
Thank you
