### ISSUE TITLE
add new page to the format

### ISSUE THREAD

**Issue by vanukw** [frappe/print_designer#245]
@maharshivpatel ,

I'm using 1.2 and could you please let me know how I can add a new page/ 2nd page please?

TIA

**Comment by vanukw** [comment]
@maharshivpatel ,

May I know the update please?

Thank you

**Comment by jll-02** [comment]
I totally agree. Being able to add another page would be a huge benefit to the print designer.

An other option, at least for me, would be to make the page expandable and only the rendered pdf is seperated in different pages.

**Comment by maharshivpatel** [comment]
@jll-02 already working on it. if all goes fine we can have it by the end of this month.

**Comment by jll-02** [comment]
great news! Thanks for the quick response @maharshivpatel
