### ISSUE TITLE
What is the correct way to update my Print Designer apps into new version v1.2.0 (main)

### ISSUE THREAD

**Issue by bobotdls** [frappe/print_designer#246]
I have a fresh instance ERPNext 

Installed Apps
ERPNext: v15.20.6 (version-15)
Frappe Framework: v15.23.0 (version-15)
Frappe HR: v16.0.0-dev (develop)
Payments: v0.0.1 (develop)
Print Designer: v1.0.0 (develop)

I would like to update the Print Designer into v1.2.0 (Main)
I use the command on frappe-bench folder
bench update
but it's still on the v1.0.0 (develop)

my I know what is the correct way to update my Print Designer apps into new version

Thanks in advance

**Comment by maharshivpatel** [comment]
@bobotdls  change the branch to main instead of develop.

**Comment by mask2082** [comment]
Could you please advise on how to do that?

**Comment by maharshivpatel** [comment]
@mask2082 go to the print_designer folder and run  
```
git checkout main && git pull
```

**Comment by bobotdls** [comment]
I execute the code your give 

git checkout main && git pull

got error message...
error: pathspec 'main' did not match any file(s) known to git

**Comment by maharshivpatel** [comment]
my bad 😅 you can just use 
```
bench switch-to-branch main print_designer
```
