### ISSUE TITLE
in preview  during print size reduce

### ISSUE THREAD

**Issue by amet123** [frappe/print_designer#248]
Hi 

after setup first time preview show very well when i refresh print privew from quotaion size go to 75% 

Thanks

![error](https://github.com/frappe/print_designer/assets/326649/a260cc10-9543-4d73-b0d0-49ba5d0311f8)

**Comment by maharshivpatel** [comment]
@amet123 can you share the format ? i am unable to reproduce this

**Comment by maharshivpatel** [comment]
@amet123 closing this if you still face the issue please open and provide more information. Thank you

**Comment by amet123** [comment]
Hi
pls chk
 
![print](https://github.com/frappe/print_designer/assets/326649/26c1915a-71c5-4f26-82c8-859744e78515)
