### ISSUE TITLE
[Feature] Selection of multiple fields in Barcode element

### ISSUE THREAD

**Issue by samy4sam** [frappe/print_designer#256]
For example, to generate QR codes from dynamic URLs, it would be great if you could select several fields in combination with static tests.

<img width="1140" alt="Bildschirmfoto 2024-05-09 um 19 54 04" src="https://github.com/frappe/print_designer/assets/42201209/43a59f52-c4bf-451a-86b1-8fea6d3a68e6">

**Comment by maharshivpatel** [comment]
@samy4sam  use jinja !

**Comment by samy4sam** [comment]
@maharshivpatel thanks for your fast reply!

I tried it with Jinja but, there is an artifact in the qr code which makes the scanned url not useful: `https://myerp.com/app/work-order/</a>MFG-WO-2024-00002`
Do you have a tipp, how I can get rid of `</a>`?

<img width="1135" alt="Bildschirmfoto 2024-05-09 um 21 11 16" src="https://github.com/frappe/print_designer/assets/42201209/f612c793-bea9-4f1e-b17d-ec6405f5abf1">

**Comment by samy4sam** [comment]
I was able to fix it myself:
{{ 'https://myerp.com/app/work-order/' + doc.name }}
