### ISSUE TITLE
No option to select Letter Head when print format is created using Print designer

### ISSUE THREAD

**Issue by Irfan778899** [frappe/print_designer#257]
When print format is created using Print designer, there is no option to select the Letter Head for the Print format while printing.

**Comment by maharshivpatel** [comment]
@Irfan778899 it is recommended to design letterhead inside print designer. however, if you must have letterhead here is video on how you can do it. Thank you


https://github.com/frappe/print_designer/assets/39730881/dcd2a6a9-51c2-491f-8094-4b36d676b1dd

**Comment by Irfan778899** [comment]
![Screenshot 2024-05-14 142624](https://github.com/frappe/print_designer/assets/127736908/6d6e00de-8b3e-42fe-a522-4e0f2f6e45bd)
I have selected letter head based on Image and attached that image to Letter head. But in print format unable to select the letter head.
