### ISSUE TITLE
NoneType - object is not iterable - pdf rendoring 

### ISSUE THREAD

**Issue by webcomx** [frappe/print_designer#262]
When l have internet access to my on-premise ERPNEXT box print can render the pdf document, when the internet is unavailable pdf cannot render and l get - NoneType - object is not iterable. 

What l want to know is "Print designer" requires the internet to work.?

**Comment by maharshivpatel** [comment]
@webcomx yes as print designer uses google fonts you need internet to generate pdfs

**Comment by maharshivpatel** [comment]
@webcomx not as of now. I am closing this as there is already issue regarding this #242 . you can check progress there. Thank you.
