### ISSUE TITLE
Invoice print pdf is showing blank 

### ISSUE THREAD

**Issue by nobychenjoseph** [frappe/print_designer#266]
### Information about bug

I have designed a custom invoice in my ERP version 15. It was working fine. i have generated many invoices before. but suddenly the print pdf is showing blank. I don’t know what to do. Please help me. i need generate many invoice today

### Module

other

### Version

ERPNext: v15.18.3 (version-15)

### Installation method

manual install

**Comment by maharshivpatel** [comment]
@nobychenjoseph  please share more information and format.
What version are you using etc.

### you share your format like this :
You can paste the data here ( change any personal info )

https://github.com/frappe/print_designer/assets/39730881/b7b761c7-a2b1-43d4-a3b3-0dde25ba9699

**Comment by maharshivpatel** [comment]
@nobychenjoseph as you have not provided the format or any more information i am closing this for now. please do share the info if you are still facing the issue. Thank you
