### ISSUE TITLE
Page print-designer not found

### ISSUE THREAD

**Issue by prosigns** [frappe/print_designer#267]
Hi, i am using ERPNext V15, upgraded from V14. and installed the print designer app as per the instructions. but when I select "Try the new Print Designer" on any report, it gives me below error:

Page print-designer not found
The resource you are looking for is not available

What could be the issue?

**Comment by maharshivpatel** [comment]
have you restarted the bench after app install ?

**Comment by prosigns** [comment]
i have restarted both bench and even the server

**Comment by rareMaxim** [comment]
Im too
![image](https://github.com/frappe/print_designer/assets/4525776/6bdbfd6e-206f-4cad-88e9-f6789a00ab13)

**Comment by legolas108** [comment]
Had the same problem. Turned out the installation instructions don't work if you already have a site installed. After dropping the print-designer.test site and installing the print_designer app in the already existing site it works fine.

**Comment by IvanGuevaraM** [comment]
Perhaps...
`bench switch-to-branch main print_designer` and then
`bench update --reset --patch`

**Comment by d3mah-24** [comment]
Just run this command `bench migrate`

**Comment by maharshivpatel** [comment]
Closing this as it is setup issue. Thank you.
