### ISSUE TITLE
Difference in Preview and Actual Print

### ISSUE THREAD

**Issue by mrkeshwani** [frappe/print_designer#273]
Hello,

In the item code column item name appears as "Item Code: Item Name" in the form and the preview in the print designer. However in actual print only item code appears. See the image below:

![Screenshot (186)](https://github.com/frappe/print_designer/assets/69404119/30093491-a3c1-4fef-98e3-aa3c252e3b4d)
![Screenshot (187)](https://github.com/frappe/print_designer/assets/69404119/646d61a7-c658-4cfa-aca0-3ae6e51bfce7)

Preview and actual print (pdf) should be the same. In the preview print designer shows the field as displayed in the form, however in the print, it shows only the "Item Code" field.

I am not an IT professional or coder.

Thanks
Mahesh Keshwani

**Comment by PhantomKunai** [comment]
This is an issue I noticed as well. Preview renders any link formatters in the JS of the doctype but the jinja does not consider that. Its just a matter of misrepresentation in print designer preview.

**Comment by aceIsHere** [comment]
Setup
**ERPNext:** v15.26.1
**Print Designer:** v1.2.0

I think this issue is not limited to scope of designer preview, it still shows the same from the print view of a doctype form. 
Further, on printing it to pdf it still omits the name of the item, just includes its code, which however is not the case while in the designer view.

Further my issue exceeds this and has a misalignment with the margins of the page (I have already set up the print setting both in designer and print settings panel to A4)

![image](https://github.com/frappe/print_designer/assets/100718147/a947ecc7-cb63-45aa-a890-3b84fd35946c)

**Comment by maharshivpatel** [comment]
@mrkeshwani formatting is handled by framework. will see what can be done though.

**Comment by maharshivpatel** [comment]
@mrkeshwani can you raise issue on Frappe Cloud so i can debug this issue on your site. Thank you.

**Comment by mrkeshwani** [comment]
@maharshivpatel I dont know how to raise an issue on Frappe Cloud. Our site is on a public bench. Could you please guide me?

**Comment by mrkeshwani** [comment]
@maharshivpatel Hi, have raised the issue on Frappe Cloud #18185, could you please look into it.

**Comment by maharshivpatel** [comment]
I believe what you want to print is Item Name and not Item Code.

https://github.com/frappe/print_designer/assets/39730881/229752bf-eadd-4599-9eb6-36b3234f0449

**Comment by mrkeshwani** [comment]
I need both item code and item name, have done this workaround:

Format designed:
![Screenshot (202)](https://github.com/frappe/print_designer/assets/69404119/db950cc0-e94c-4d00-a847-46183ef1d831)

Displayed/PDF

![Screenshot (203)](https://github.com/frappe/print_designer/assets/69404119/b50bee70-dfef-46ad-9517-e8a54873259e)

**Comment by maharshivpatel** [comment]
@mrkeshwani so this formatting is done in framework. i don't think there is anything we can do in print_designer as this is edge case. i will be closing support ticket as i will consider this when i rewrite print_designer but nothing can be done quickly. 

if you really hate it you can use jinja to show item code and item name like : 

https://github.com/frappe/print_designer/assets/39730881/fcf0de4a-39da-48fd-a639-7547aceb12fc

```
{{ row.get("item_code") }}
```
```
{{ row.get("item_name") }}
```
