### ISSUE TITLE
Print Misalignment with Margins

### ISSUE THREAD

**Issue by aceIsHere** [frappe/print_designer#277]
Setup

**ERPNext:** v15.26.1
**Frappe Framework:** v15.29.0
**Frappe HR:** v15.22.0
**Print Designer:** v1.2.0

**wkhtmltopdf**: 0.12.6

The print format looks fine in the designers tab and its preview settings but while trying to print it from a doctype's default print form panel (both  the preview and the print) it comes out misaligned with the margins. Similar to an issued (https://github.com/frappe/print_designer/issues/273) raised.

![image](https://github.com/frappe/print_designer/assets/100718147/0fe6379c-61fe-4452-8f22-cdc4a4d6ce04)

Also have crosscheck page size in print setting of the designer and default print form panel to A4

Print Settings of Designer:
![image](https://github.com/frappe/print_designer/assets/100718147/91585f4c-6724-4dec-a6e7-5bd09f9a1427)

Default print settings:
![image](https://github.com/frappe/print_designer/assets/100718147/1c4cbcc0-55a7-4c3b-a1b8-a24642eb4628)

**Comment by maharshivpatel** [comment]
@aceIsHere you need to install wkhtmltopdf with qt pacthed https://github.com/frappe/print_designer?tab=readme-ov-file#faq

**Comment by maharshivpatel** [comment]
@aceIsHere closing this as it is due to incorrect wkhtmltopdf version in your setup. please open new issue if you face any other issue.  Thank you.

**Comment by aceIsHere** [comment]
Upgrade the versions as instructed, the situation has improved, issue still persists however.

**wkhtmltopdf 0.12.6.1 (with patched qt)**

Have shared  the images in negative to better highlight the margins and boundaries.

![image](https://github.com/frappe/print_designer/assets/100718147/b846a5ba-13e3-4d7b-9742-d5bca19926e0)

![image](https://github.com/frappe/print_designer/assets/100718147/784ed92c-d7bd-4e22-8acd-a7e8b2226b00)

Both print designer and the default built-in print functionality page settings have been set to a4

I have to fight with the print designer to get my table/rectangle boundaries within a single page, this is especially noticeable as stark difference in the vertical coordinates, If I move my lower border in print designer to its actual designated places it just overflows by creating it on two pages in the print preview of the built-in printing pane.
