### ISSUE TITLE
Print Margins (border) Overflow

### ISSUE THREAD

**Issue by aceIsHere** [frappe/print_designer#281]
Upgrade the versions as instructed, misunderstood it as a comment rather than an actual patch https://github.com/frappe/print_designer/issues/277.
The situation has improved, issue still persists however.

wkhtmltopdf 0.12.6.1 (with patched qt)

Have shared the images in negative to better highlight the margins and boundaries.

![image](https://github.com/frappe/print_designer/assets/100718147/490537e8-9a01-4c4c-b308-4f76bd173020)
![image](https://github.com/frappe/print_designer/assets/100718147/4ffd30ba-0539-4dfe-bf87-462870f1b2ab)
Both print designer and the default built-in print functionality page settings have been set to a4

I have to fight with the print designer to get my table/rectangle boundaries within a single page, this is especially noticeable as stark difference in the vertical coordinates, If I move my lower border in print designer to its actual designated places it just overflows by creating it on two pages in the print preview of the built-in printing pane.

**Comment by maharshivpatel** [comment]
@aceIsHere can you share the format as i am unable to under the issue you are facing. Thank you.

### you share your format like this :
You can paste the data here

https://github.com/frappe/print_designer/assets/39730881/b7b761c7-a2b1-43d4-a3b3-0dde25ba9699

**Comment by maharshivpatel** [comment]
@aceIsHere as you haven't provided more information i am assuming that issue is resolved. If not please feel free to create new issue with more information and format. Thank you.
