### ISSUE TITLE
Table Button not visible/available

### ISSUE THREAD

**Issue by eis-qazi** [frappe/print_designer#302]
Why can't i see the table button in print designer?
![Screenshot from 2024-06-22 01-14-58](https://github.com/frappe/print_designer/assets/127878195/3bc69b0d-8956-4035-9b1d-b13b45a35517)

I have checkout latest main and develop branch, and then did bench migrate, but i still can't see the button.

**Comment by maharshivpatel** [comment]
@eis-qazi because your doctype doesn't have any child tables
