### ISSUE TITLE
version 1.2 stuck i confused please help

### ISSUE THREAD

**Issue by abdopcnet** [frappe/print_designer#303]
i installed latest version on fresh erpnext
i found that it is version 1.2.0
despite i see the current release is 1.3.3
so what version i use now !!
![image](https://github.com/frappe/print_designer/assets/48860652/209e8b27-461e-482f-917d-2749b51bd70e)

**Comment by maharshivpatel** [comment]
@abdopcnet where are you hosting? frappe cloud or your own server ?

**Comment by maharshivpatel** [comment]
https://github.com/frappe/print_designer/tree/main as you can check the last commit : https://github.com/frappe/print_designer/commit/59302de3c0a11558823c21e26b704e0a7e16cc3b
