### ISSUE TITLE
No header footer some pages

### ISSUE THREAD

**Issue by vanukw** [frappe/print_designer#308]
Hi @maharshivpatel ,

I have a scenario as below,

There's a Tax invoice and letter attached to it. For tax invoice, I have a header and footer.

But, for the letter, there's no header footer and the letter continues to the next page as well.

I want them together as one report, Could you please help me to sort out this issue?

Thank you.

**Comment by maharshivpatel** [comment]
@vanukw limitation is from wkhtmltopdf. it is not possible and not much we can do about it. Thank you.
