### ISSUE TITLE
Why I cannot see the boxes

### ISSUE THREAD

**Issue by mrkeshwani** [frappe/print_designer#309]
Hello,

Can anyone tell me why I am unable to see the boxes made while designing a new format. See the screen shots below:

![Screenshot (198)](https://github.com/frappe/print_designer/assets/69404119/7ef57823-341b-4f79-b957-e71b9727f87c)
![Screenshot (199)](https://github.com/frappe/print_designer/assets/69404119/bbc7c396-288c-4a7b-9574-20dcf87cf354)

Thanks,
Mahesh Keshwani

**Comment by maharshivpatel** [comment]
@mrkeshwani already fixed. will be available in. next release

**Comment by mrkeshwani** [comment]
@maharshivpatel, thank you for the quick response.

**Comment by maharshivpatel** [comment]
fixed by #305
