### ISSUE TITLE
Not able to move text elements out of rectangle

### ISSUE THREAD

**Issue by the3dfox** [frappe/print_designer#316]
Adding text elements to rectangles is pretty straight forward, just drag and drop the item over an existing rectangle. Second method, draw a rectangle over an element and it will be automatically placed inside the rectangle.

Problem though is, there is no option to remove elements from rectangles, dragging lets you only move the element against the border of the rectangle. This can be very annoying because the only way is to delete the element and start from scratch.

**Comment by maharshivpatel** [comment]
press cmd/ctrl while dragging to move out
