### ISSUE TITLE
Installation on Rocky Linux 9.4 doesn't work

### ISSUE THREAD

**Issue by maverjk** [frappe/print_designer#327]
Hello to everyone

As mentioned in the title, I tried to install PrintDesigner on my Frappe / ERPnext Framework in a Rocky Linux 9.4 server.
Unfortunately, it doesn't get installed, the process tried to build it from code but failed. Following a portion of the failed building process:

```
...
 yarn run v1.22.22
$ node esbuild --production --apps print_designer --run-build-command
✘ [ERROR] Could not resolve "canvas"

    ../print_designer/print_designer/public/js/pdf.worker.min.js:22:25511:
      22 │ ...{!globalThis.DOMMatrix&&a.isNodeJS&&(globalThis.DOMMatrix=require("canvas").DOMMatrix)}();!function checkPath2D(){if(globalThis.Path2D||!a.i...
         ╵                                                                      ~~~~~~~~

  You can mark the path "canvas" as external to exclude it from the bundle, which will remove this
  error. You can also surround this "require" call with a try/catch block to handle this failure at
  run-time instead of bundle-time.

Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
✘ [ERROR] [plugin frappe-vue-style] Cannot read properties of undefined (reading 'outputs')
...
```
Any help to get around this issue is really welcome.

**Comment by maharshivpatel** [comment]
@maverjk i hope you looked at faq and resolved your issue with canvas. closing this for now. feel free to open issue if you face any issue. thank you

**Comment by maverjk** [comment]
Hi @maharshivpatel 

I have already look into print_designer faq and I tried to install all the debian equivalent libraries. 
Also doing this I keep haveing issues so I decided to open a ticket here.
