### ISSUE TITLE
Design and Print Preview Are Different

### ISSUE THREAD

**Issue by sipatha** [frappe/print_designer#331]
I have created a Sales Invoice Design as below. I expect the right text element to snap to the right edge of the print output

<img width="1024" alt="image" src="https://github.com/user-attachments/assets/f6dfb8bc-d461-4784-9fbb-98629cefd123">

Unfortunately on preview the test in not on the edge as expected.

<img width="1286" alt="image" src="https://github.com/user-attachments/assets/2853f716-3c72-41a5-bcce-0ceebc8e106c">

**Comment by maharshivpatel** [comment]
@sipatha are you self-hosting ? if yes then make sure you have correct wkhtmltopdf ( with patched qt ) version. https://github.com/frappe/print_designer?tab=readme-ov-file#faq . Thank you.

**Comment by sipatha** [comment]
You are right. It was the wkhtmltopdf version that caused the issue.
Initially we only saved the HTML output to pdf from the browser and were using: 
```
azureuser@erp:~# wkhtmltopdf --version
wkhtmltopdf 0.12.5
```
Now with:
```
azureuser@erp:~# wkhtmltopdf --version
wkhtmltopdf 0.12.6 (with patched qt)
```
The report outputs as designed.
