### ISSUE TITLE
Print designer doesn't appear in ERPNext 15 awesome search bar after successful installation

### ISSUE THREAD

**Issue by kitunzit** [frappe/print_designer#332]
Good day.
I have successfully installed print designer on Cloud Cluster ERPNext 15 without any error but print designer does not appear when i search using awesome bar.
Any help/advice will be highly appreciated. 
Tim.

**Comment by maharshivpatel** [comment]
@kitunzit can you please try and clear cache and restart bench once. Thank you.

**Comment by maharshivpatel** [comment]
i haven't heard from you. closing this for now. if you face any issue feel free to raise issue and provide detail. Thank you

**Comment by nguyen68126** [comment]
Hi, I am facing the same issue. I follow clear cache and restart bench but no luck. Please help
