### ISSUE TITLE
Update to version 1.4

### ISSUE THREAD

**Issue by classita** [frappe/print_designer#333]
hello there,

please assist on how to update to latest version.

erpnext 15.31.4
frappe 15.36.1
frappe_pdf 0.0.1
hrms 16.0.0-dev
it_management 0.0.1
payments 0.0.1
print_designer 1.2.0

**Comment by maharshivpatel** [comment]
@classita do you mean on Frappe Cloud ?

**Comment by classita** [comment]
> @classita do you mean on Frappe Cloud ?

self hosted

**Comment by classita** [comment]
Hello Maharshi Patel,

are you planned to stop this project?

**Comment by maharshivpatel** [comment]
Closing please check #345
