### ISSUE TITLE
Print Preview not render some text and layout in Persian layout and text 

### ISSUE THREAD

**Issue by zubairamini** [frappe/print_designer#335]
[ACC-ASM-2024-00027.pdf](https://github.com/user-attachments/files/16518843/ACC-ASM-2024-00027.pdf)
 i have design asset movement print in print designer it design correctly but it is not render some text and layout in print preview and printing

**Comment by maharshivpatel** [comment]
@zubairamini you need to install correct version to wkhtmltopdf (with patched qt). https://github.com/frappe/print_designer?tab=readme-ov-file#faq

**Comment by maharshivpatel** [comment]
@zubairamini did you install correct version ?

**Comment by maharshivpatel** [comment]
@zubairamini closing as you haven't replied and it looks like setup issue. Thank you.
