### ISSUE TITLE
Latest Version Installtion

### ISSUE THREAD

**Issue by TranscendentThinkers** [frappe/print_designer#337]
I am installing print_designer app on self hosted system. Used bench get-app git-link, but it is installing version 1.2.0. Also tried with bench get-app --branch develop git-link, this is also installing version 1.2.0. How to install latest version

**Comment by maharshivpatel** [comment]
can you share the `git-link` you are using ? exact command could give some details. Thank you

**Comment by maharshivpatel** [comment]
@TranscendentThinkers switch to main branch

**Comment by jefferdo** [comment]
@TranscendentThinkers  try below 
`
bench get-app https://github.com/frappe/print_designer --branch v1.4.1
`

**Comment by IvanGuevaraM** [comment]
`bench get-app print_designer --branch main`
or 
`bench get-app https://github.com/frappe/print_designer --branch main`

**Comment by IvanGuevaraM** [comment]
And, if its already installed...
`bench switch-to-branch main print_designer`

**Comment by maharshivpatel** [comment]
As people have already provided solution which is to switch to main branch.

There was a mix up which caused develop branch to have tag v1.2.0 it is actually dev branch and not v1.2.0.

Thank you.
