### ISSUE TITLE
Texts not wrapping

### ISSUE THREAD

**Issue by ajiragroup** [frappe/print_designer#339]
version:
erpnext 15.29.3
frappe 15.34.1
print_designer 1.4.0

Print format vs actual print (pdf) does not match. 

In PDF export:
![image](https://github.com/user-attachments/assets/96cebd1e-5cba-49da-830e-f24e470f74c1)

In preview:
![image](https://github.com/user-attachments/assets/6960fd18-4f9c-4054-96ce-41bcb593291b)

In print format:
![image](https://github.com/user-attachments/assets/2f57008e-2fb7-4a35-8b14-2eed26cfcdff)

**Comment by maharshivpatel** [comment]
@ajiragroup client script was not loaded properly. refresh the browser. it should go away thank you.

**Comment by ajiragroup** [comment]
still doesnot work. refreshed browsers, changed browser, clear cache as well with bench --site site1.local clear-cache .. nothing works
