### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by classita** [frappe/print_designer#343]
Hello,

Installed Apps
ERPNext: v15.33.2 (version-15)
Frappe Framework: v15.39.0 (version-15)
Frappe HR: v15.26.0 (version-15)
Print Designer: v1.2.0 (develop)

How to set the footer just to print in the last page?

**Comment by maharshivpatel** [comment]
@classita don't put it in footer just have it in the end of format and it will only print on last page.

also, on footer you can choose to show it on only last page by selecting from properties panel ( look at bottom right). but that will leave empty space on all pages.  choose method which suits your requirements Thank you.

<img width="1386" alt="Screenshot 2024-09-04 at 7 00 38 PM" src="https://github.com/user-attachments/assets/222c790d-66c5-4191-9cd9-24978dfbaa3d">

**Comment by classita** [comment]
Hello Maharshi Patel,

when I click Select Pages –> “Last”, at the properties panel, then i cannot save my changes.

please advice

**Comment by elvis82** [comment]
ya ... the issue still the same
