### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by classita** [frappe/print_designer#345]
Hello

How to update print designer to latest version?

still in develop?

self-hosted
Installed Apps
ERPNext: v15.33.5 (version-15)
Frappe Framework: v15.39.0 (version-15)
Frappe HR: v15.27.0 (version-15)
Print Designer: v1.2.0 (develop)

**Comment by IvanGuevaraM** [comment]
Please try, at the bench folder type:

bench switch-to-branch main print_designer

**Comment by IvanGuevaraM** [comment]
`bench version -f table`

**Comment by classita** [comment]
> Please try, at the bench folder type:
> 
> bench switch-to-branch main print_designer

worked. thanks

**Comment by IvanGuevaraM** [comment]
Perhaps, you want to close this issue...

**Comment by classita2661** [comment]
yes

**Comment by classita2661** [comment]
Hello Ivan,
May i ask your regarding barcode printing in Print Designer?

**Comment by IvanGuevaraM** [comment]
I´m sorry, i haven´t tried barcode printing with Print Designer so far.

**Comment by maharshivpatel** [comment]
@classita2661 closing this if you have question regarding barcode post in discussions or create issue. Thank you.
