### ISSUE TITLE
Cannot Delete Any Element in Print Designer

### ISSUE THREAD

**Issue by architectcoding** [frappe/print_designer#351]
I just updated print designer to the latest version v.1.4.2 (main). I am unable to delete any element using the delete key. I also tried to make sure that my print format is not corrupted by making new one, and the issue persisted. Tried with another site also and the issue seems replicable.

![image](https://github.com/user-attachments/assets/1c89105b-2ee3-4242-bf65-786567843323)

**Comment by ablashek** [comment]
Yes, same issue after updating yesterday.

**Comment by bobotdls** [comment]
same with me I cannot delete any elements after upgrading to new version

**Comment by maharshivpatel** [comment]
can anyone send me console error so i can see the problem i am unable to replicate it

**Comment by architectcoding** [comment]
Hi this is the console error generated when I try delete the element.

[error log-1726287037480.log](https://github.com/user-attachments/files/17000934/error.log-1726287037480.log)
[error log-1726287324982.log](https://github.com/user-attachments/files/17000949/error.log-1726287324982.log)

**Comment by cavinwela** [comment]
I have the same issue when I updated to latest version

**Comment by zenicolas** [comment]
Same issue on 1.4.2

Installed Apps
Frappe Builder: v1.11.6 (HEAD)
Desk Navbar Extended: v0.0.1 (HEAD)
ERPNext: v15.36.1 (HEAD)
Frappe Framework: v15.41.0 (HEAD)
Frappe HR: v15.29.0 (HEAD)
Print Designer: v1.4.2 (HEAD)

**Comment by moizsami** [comment]
Im facing the same issue

**Comment by DileepMedayil** [comment]
Same error, could not delete any element. any updates on this @maharshivpatel

**Comment by qsarthi** [comment]
@maharshivpatel this is really unfair and we get most issue in Print Format...Anytime I try to make any modification I have to spend really hours and hours scraching my head.. Please  keep a basic thing whenever you release: Don't break the working things, and give us option to rollback . I use Frappecloud and it gets auto upgraded

**Comment by maharshivpatel** [comment]
@qsarthi i understand the inconvenience caused by recent updates and i am really sorry for that. unfortunately, i am unable to replicate this issue that is why it is not fixed.

**Comment by qsarthi** [comment]
Just create a new Print designer Format and add any new element ..simple static text ..and then try to delete..

I can't even do that ..   Check attached if this helps.


[PrintDelete.zip](https://github.com/user-attachments/files/17158849/PrintDelete.zip)

**Comment by maharshivpatel** [comment]
it was working normally on my setup 😅 . anyways i have found the root cause and you can expect this to be fixed today can take few days to deploy on FC. i will try to do it as soon as possible. Thank you so much for sharing the issue.

**Comment by moizsami** [comment]
@maharshivpatel thanks for your support, by any chance you could tell us it would be fixed by when? Im using self hosted environment, my client is waiting for the changes so have to inform them.

**Comment by maharshivpatel** [comment]
can someone checkout develop branch and confirm that it is working before i release in main branch. thank you
