### ISSUE TITLE
Could not login after install

### ISSUE THREAD

**Issue by nguyen68126** [frappe/print_designer#353]
Hi,
I am installed app follow your instruction on ErpNext V15 . Install completed without issue but I could not login after that. Please see my login screen here and help me also with ID I will use to login please?

![2024-09-10_12-10-02](https://github.com/user-attachments/assets/b6e84182-d51c-4e89-b215-1e0dcb636b99)

**Comment by maharshivpatel** [comment]
@nguyen68126 because you have another issue where you have logged in i am assuming this was resolved. also, this looks like setup issue. thank you for sharing.
