### ISSUE TITLE
custom data instead of footer / header

### ISSUE THREAD

**Issue by cianmengy** [frappe/print_designer#368]
![image](https://github.com/user-attachments/assets/44528692-33c4-42fa-938d-18780e49c5e8)

**Comment by cianmengy** [comment]
please help why the footer / header change to custom data? 

thanks

**Comment by cianmengy** [comment]
sorry i got it already.thanks

**Comment by emmanuel-mwendwa** [comment]
Hello. What is the purpose of the Custom Data and how is it used?

**Comment by maharshivpatel** [comment]
please check pr called custom data for jinja 😄
