### ISSUE TITLE
Table not going to next page 

### ISSUE THREAD

**Issue by RuchiraJayamanna** [frappe/print_designer#370]
![image](https://github.com/user-attachments/assets/13655e2c-a152-4525-9dfe-f22a892103f7)

When we added a table and a section after the table , if the table rows getting more it is not going to next page , overlapping the below section, how to fix that?

**Comment by maharshivpatel** [comment]
press `ctrl/cmd + A` and see some elements must be overlapping with table which causes the height to be static. Thank You

**Comment by RuchiraJayamanna** [comment]
![PRint](https://github.com/user-attachments/assets/bf50551e-0654-4e09-8949-4f1db89d124e)

If the table having more rows then it is overlapping the Below Payment method Section, but what i need is ,that Payment Method section should move down with the increase of table rows or should move to the next page.

![Screenshot 2024-10-22 143854](https://github.com/user-attachments/assets/d579abc0-2638-46d5-89ff-b9a1dc93c8e8)
