### ISSUE TITLE
The format of the static text brokes when you click outside the edit box.

### ISSUE THREAD

**Issue by 2old4thisShit** [frappe/print_designer#373]
I'm trying to add the legal text to a document, but each time I click outside the edit box, the text completely loses its formatting.

Video attached.

I haven’t attached the template because it’s easy to reproduce.

The version is the latest published one.

https://github.com/user-attachments/assets/cb5adfa9-42c8-4b39-afa2-1975d588cbad

**Comment by 2old4thisShit** [comment]
Hi! @maharshivpatel  Have you had a chance to take a look at this?

**Comment by maharshivpatel** [comment]
@2old4thisShit I believe this is intentional.

**Comment by maharshivpatel** [comment]
@2old4thisShit please check https://github.com/frappe/print_designer/pull/227

**Comment by 2old4thisShit** [comment]
> @2old4thisShit please check #227

Indeed. That makes sense. I remember that issue with unnecessary tags in Chrome...  

Thank you so much.  

I’ll solve it through other means. Closing this now.  

Thanks again. Best regards.
