### ISSUE TITLE
Not able to render hindi unicode characters in PDF

### ISSUE THREAD

**Issue by samkit5495** [frappe/print_designer#378]
**Print Designer**

<img width="1315" alt="Screenshot 2024-12-01 at 10 40 47 AM" src="https://github.com/user-attachments/assets/46fe7ad4-eaee-4d37-b3f9-b2e3af92d993">

**PDF Preview**

<img width="1129" alt="Screenshot 2024-12-01 at 10 40 55 AM" src="https://github.com/user-attachments/assets/60aec457-1295-4a27-9a25-3e6b84ab9c14">

**Comment by Govind-Jangid** [comment]
@samkit5495 
sudo apt-get install fonts-deva

**Comment by samkit5495** [comment]
It still is not working, do I need to do anything else ?

**Comment by samkit5495** [comment]
> @samkit5495 sudo apt-get install fonts-deva

Thanks @Govind-Jangid its working now !
