### ISSUE TITLE
Header is not fixed correctly, if it contain a text component.

### ISSUE THREAD

**Issue by kittiu** [frappe/print_designer#379]
Print Designer: v1.4.3 (HEAD)

I have try test created this easy one multiple time and found that,

I test header and footer. The first one is OK,

![image](https://github.com/user-attachments/assets/d13f568f-5e40-44a9-8db8-11f9fda9744e)

But if I put and word in the block, it is like this,

![image](https://github.com/user-attachments/assets/bc868036-b435-4149-afd1-6ad60bb4a61a)

The footer look OK.

**Comment by maharshivpatel** [comment]
@kittiu you have to make the height of text/rectangle fixed instead of auto.
