### ISSUE TITLE
ERROR: bench build --app print_designer

### ISSUE THREAD

**Issue by xcode-ae** [frappe/print_designer#4]
Erpnext v14 
UBUNTU 22.04
<img width="500" alt="Screen Shot 2023-06-10 at 2 14 37 PM" src="https://github.com/frappe/print_designer/assets/112379904/bd1c375a-fca3-4cbc-9ea6-a98ac6cfefad">
<img width="488" alt="Screen Shot 2023-06-10 at 2 14 54 PM" src="https://github.com/frappe/print_designer/assets/112379904/e8d78947-5ad9-4277-bf40-649dfd77ee1c">
<img width="493" alt="Screen Shot 2023-06-10 at 2 15 13 PM" src="https://github.com/frappe/print_designer/assets/112379904/41b564e4-6f21-48c7-a07f-ea9ad03baf5a">
while install it

**Comment by wazen1** [comment]
same problem

**Comment by maharshivpatel** [comment]
Please note that print designer is only compatible with develop version of frappe framework. v14 is not supported as this app requires vue3.
