### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by KoduaWatson** [frappe/print_designer#46]
Hi Maharshi, 
thanks for your Print Designer App and your presentation on BuildWithHussain.

I've downloaded it from the github repo and tried installing it on my frappe site, but i get this error message:

__An error occurred while installing print_designer: ('Module Def', 'Print Designer', IntegrityError(1062, "Duplicate entry 'Print Designer' for key 'PRIMARY'"))__

Any help will be greatly appreciated, thanks.

**Comment by maharshivpatel** [comment]
This most likely happened because you tried to install print designer it failed and you are trying again. you can pass --force flag while installing.

**Comment by maharshivpatel** [comment]
@KoduaWatson please try this and if you still face the issue reopen with more information.

```
bench --site {your_site_name} install-app print_designer --force   
```
