### ISSUE TITLE
Print-designer installation issue

### ISSUE THREAD

**Issue by yugajoshi** [frappe/print_designer#53]
installed successfully. but when trying to load http://print-designer.test:8000/ , it is saying server IP could not be found

**Comment by maharshivpatel** [comment]
This issue is not related to print designer.

can you please share information from terminal that you get when you run bench start ?

**Comment by yugajoshi** [comment]
bench --site print-designer.test install-app print_designer. This is the last command I executed on terminal to install. What is the next process as github says to click on  http://print-designer.test:8000/

**Comment by maharshivpatel** [comment]
```
bench start
```

run and visit the [link](http://print-designer.test:8000/) then share output  from terminal

**Comment by yugajoshi** [comment]
![MicrosoftTeams-image (1)](https://github.com/frappe/print_designer/assets/144673136/ed12f823-1885-4028-8d00-98dca35a6fb1)
![2023-09-11](https://github.com/frappe/print_designer/assets/144673136/a9807635-3577-4c49-831b-7a2e5626d1b3)

**Comment by maharshivpatel** [comment]
There are ways to solve this but easiest i would suggest is just restart your pc/laptop then run `bench start` command and the visit the link.

**Comment by yugajoshi** [comment]
yes, I have installed frappe on GCP cloud and trying to access it. is there any issue?

**Comment by yugajoshi** [comment]
Thank you boss. Its done

**Comment by yugajoshi** [comment]
Hello Maharshi,
I am using our thread of git issue and sorry for that as I have very minor
doubt. I just want to know how to add multiple pages print designer app
while designing print format. As of now I am able to add only onepage.
