### ISSUE TITLE
Infinite loop if referenced doc deleted.

### ISSUE THREAD

**Issue by batonac** [frappe/print_designer#55]
There's an issue at present with a the Print Designer if/when the doc originally referenced for the design is deleted.

### Steps to reproduce:

1. Create a new print format with the Print Designer and reference a doc for the specified DocType field preview.
2. Save the print format and delete the referenced doc.
3. Re-open the print format in print designer.

### Expected behavior:

- Referenced doc is cleared, new one can be set.
- Field previews update based on values from the new referenced doc.

### Actual behavior:

- On opening print format, a "Not found" message is printed.
- After closing message, the autocomplete link field gives a list of other docs, but any selection is cleared.

https://github.com/frappe/print_designer/assets/4996285/cae81399-25d4-42fa-9cd1-8f5997ed7397

- The browser dev tools reveal an infinite loop in the `data-ajax-state` attribute on the `body` tag.

https://github.com/frappe/print_designer/assets/4996285/82f39aa0-496a-4b7d-a4f0-7e2ef1d37b96

**Comment by maharshivpatel** [comment]
@batonac This should be fixed now. please update and check.  let me know if you find any more issues.

**Comment by batonac** [comment]
Much better, thanks so much 👏
