### ISSUE TITLE
Print Designer

### ISSUE THREAD

**Issue by github383560341** [frappe/print_designer#57]
I upgraded from v14 to v15, and currently, the 'Print Designer' app cannot be enabled. When I access http://print-designer.test:8000/, it still shows the old system, and I am unable to access the Print Designer.

**Comment by maharshivpatel** [comment]
did you follow the installation instructions? can you please share more information or error ?

**Comment by maharshivpatel** [comment]
@github383560341 closing as there is no response from your side and more information is required. you can easily reopen if you are still facing the issue. i will be more than happy to help.
