### ISSUE TITLE
Issues with Duplicating Print Formats

### ISSUE THREAD

**Issue by batonac** [frappe/print_designer#59]
After working out the styling of one print format, it's nice to be able to utilize that work across other print formats. The most obvious way to do this would be to duplicate an existing format and re-assign the doctype, but this ends up being not very doable.

**Steps to reproduce:**

1. Create a print format with Print Designer, populate it with fields specific to the selected doctype.
2. Duplicate the print format from the print format list (outside print designer), assign the new print format to another doctype.
3. Open the duplicate in Print Designer.

**Expected behavior:** The print format can be re-factored specific to the newly-selected doctype. Deprecated field and table assignments from the previous format can be re-assigned, while retaining placement and formatting from the original format.

**Actual Behavior:**

- Deprecated field assignments from the previous doctype can be opened in the field selector, but they cannot be removed or reassigned. Clicking on the field in the text-editor/field-assignemnt modal freezes the whole editor.
- A table can be deleted, but not re-assigned. Clicking into a column freezes the editor.

**Comment by ramalyb** [comment]
Dear @maharshivpatel,
I have the same issue like @batonac mentioned on removal of depreciated fields. any workaround for this?

**Comment by batonac** [comment]
The most obvious workaround at the moment is to simply delete and recreate the fields and tables in question, but this dramatically dampens the potential advantages of duplication.

This could also be addressed at the database level by swapping out field references in the print format data, but that's a tedious proposition.

**Comment by maharshivpatel** [comment]
@batonac ideal way i can think of is to have dialog with deprecated fields and option to replace it.

I am thinking similar interface to what we have in data import where we map excel columns to fields.

**Comment by batonac** [comment]
@maharshivpatel your proposed solution would be ideal, for sure.

Perhaps a bit less complicated in the meantime would be to resolve the interface freeze issue and allow these fields to be manually re-assigned. I'm thinking that field references which aren't valid in the current doctype could just be highlighted red or yellow in the designer to draw attention to themselves.

**Comment by maharshivpatel** [comment]
@batonac i think freezing issue is solved mostly. please try once with latest code.

**Comment by batonac** [comment]
Can verify that the freeze issues are resolved 👏🏆🎉
