### ISSUE TITLE
Quill classes override styling of Text Editor dynamic fields

### ISSUE THREAD

**Issue by batonac** [frappe/print_designer#62]
When inserting a dynamic HTML/Text Editor field into a Print Designer print format, the behavior of the field is not as expected.

- [x] Any `<p>` element in the dynamic HTML is given large margin, the equivalent to a few cm.
- [ ] The font/formatting options on the element have little to no effect.

Consider the `Terms and Conditions Details` field of a Sales Invoice. I had to insert it on the Print Designer far above where I intended it to be placed:
<img width="473" alt="image" src="https://github.com/frappe/print_designer/assets/4996285/d5c1c1ae-c3b6-410f-bbc0-d7f779435eb5">

In the actual rendering of the document, it is placed quite a bit lower:
<img width="519" alt="image" src="https://github.com/frappe/print_designer/assets/4996285/4e1ca7ed-bf49-4c8f-b839-a458f6b66210">

And the font size is quite a bit larger than what's selected on the backend:
<img width="156" alt="image" src="https://github.com/frappe/print_designer/assets/4996285/02e07f22-f722-4820-8676-f9f8fed83737">

**Comment by maharshivpatel** [comment]
@batonac i will fix the positioning part

Style is not applying because text inside is already formatted and user can type very complex value including tables, list, etc so we can't assume that it will be one single text and apply style on it. 

If you have some Suggestion i am happy to discuss.

**Comment by batonac** [comment]
@maharshivpatel that's fair enough... except for the fact that in this case, no manual formatting was applied to the content of the field in question:
<img width="640" alt="image" src="https://github.com/frappe/print_designer/assets/4996285/028fdea3-faf8-4dbf-a6f5-3a577dcb4880">

So yes, I agree with you regarding allowing for manual styling to override any print format styling. Where no styling is applied in the text editor, however, I believe the field should be rendered with the specific styling that is configured for the dynamic field in the print format.

**Comment by maharshivpatel** [comment]
@batonac if you open developer console and check output of this text. it will have divs, p tag etc. quill editor that is used adds styling by default.

**Comment by batonac** [comment]
@maharshivpatel I did check that, actually:
```
<div class="ql-container ql-snow" style="position: relative;">
    <div class="ql-editor" data-gramm="false" contenteditable="true" data-lt-tmp-id="lt-208377" spellcheck="false">
        <p>1.5% interest after 30 days. Thank-you for your business!</p>
    </div>
</div>
```
...so in this case, I can verify that, yes, the paragraph in question is inheriting `font-size: 13px;` from a rule set on `.ql-container` in the default quill editor styles. But again, that's a really poor user experience if quill default styles are allowed to override manually-configured print format rules.

**Comment by maharshivpatel** [comment]
@batonac Override styles is not going to be fixed anytime soon, other problem ( margin ) should be fixed now.

**Comment by maharshivpatel** [comment]
@batonac no because quill adds inline styles, otherwise it would be easy to overwrite them
