### ISSUE TITLE
Child tables do not work properly

### ISSUE THREAD

**Issue by JRII972** [frappe/print_designer#64]
Good morning
I can't configure the application properly.
I have tried installing and reinstalling several times.
The first time I made the mistake of not adding the host

I even put it into production and I can't do it.
Child tables do not work.

I would like to at least know the internal workings in order to understand how to solve my problem.

Thanks in advance

Run in a Hyper-V VM, on Xubuntu 22.x
Frappe 15 (dev - latest at 27/09/2023)
![image](https://github.com/frappe/print_designer/assets/59899019/9bb68a78-ce98-4c0f-979f-60f36b444920)

**Comment by maharshivpatel** [comment]
### can you share your format like this :
You can paste the data here ( change any personal info )

https://github.com/frappe/print_designer/assets/39730881/b7b761c7-a2b1-43d4-a3b3-0dde25ba9699

Also, a lot more information is required like what did you do step by step.

**Comment by maharshivpatel** [comment]
@JRII972 issue is print designer is unable to find child table. can you try creating print format for some other doctype that have child table just to isolate the issue.

**Comment by JRII972** [comment]
So, i try on new custom doctype, and i install ERP (reinstall the site (wipe data) > install ERP > start again)
And i can't create a new print format. It create the row in database, but i can't open it
![image](https://github.com/frappe/print_designer/assets/59899019/1fdc62ba-c57d-4bee-a110-5cdabf0c98c1)

on production mode i saw in log redis connexion failed
![image](https://github.com/frappe/print_designer/assets/59899019/1764cc9b-8ed6-4cf5-951c-daf36cbf06ff)

So, i stop the supervisor, start in the terminal, redis connexion worked. But i don't have redis socketio (i don't change the config file or Procfile)

![image](https://github.com/frappe/print_designer/assets/59899019/73f3ff2a-2ecd-43d1-965b-9a476ebf40a3)

I try to find what i did wrong, i'll try start from the beginning

**Comment by maharshivpatel** [comment]
@JRII972 were you able to make this work ? this seems to be issue with installation as i haven't found similar issue elsewhere. we can discuss and try to resolve this if this is still happening.

**Comment by maharshivpatel** [comment]
closing as resolved for now. if you still face the issue please reopen the issue and i will be more than happy to help you.

**Comment by JRII972** [comment]
Hi,

Yes, sorry I had to go abroad, and I couldn't continue working on it.

I understood that it is socket io which is not working correctly. I managed to get it to work for a while, but couldn't get it to work again.

I try to do tests with ```frappe.publish_realtime```, but nothing.

I don't really know where this comes from...

Thank you again for your help

**Comment by JRII972** [comment]
I found that the source of the error would be a variable ```_a2``` which would be a dictionary, empty and therefore we cannot access the value, I cannot find where it should be assigned .

```javascript
const selectField = async (field, fieldtype) => {
        var _a2, _b, _c, _d;
        let isRemoved = false;
        fieldnames.value = fieldnames.value.filter((el) => {
          if (el.parentField == previewRef.value.parentField && el.fieldname == field.fieldname) {
            isRemoved = true;
            MainStore.dynamicData.splice(MainStore.dynamicData.indexOf(el), 1);
            if (previewRef.value.selectedEl && el == previewRef.value.selectedEl.field) {
              previewRef.value.setSelectedEl(null);
            }
            return false;
          }
          return true;
        });
        if (isRemoved)
          return;
        let index = fieldnames.value.length;
        let value = previewRef.value.parentField ? await getValue(doctype.value, MainStore.docData[previewRef.value.parentField], field.fieldname) : props.table ? typeof ((_a2 = MainStore.docData[props.table.fieldname]) == null ? void 0 : _a2[0][field.fieldname]) != "undefined" ? frappe.format(
          MainStore.docData[props.table.fieldname][0][field.fieldname],
          { fieldtype: field.fieldtype, options: field.options },
          { inline: true },
          MainStore.docData
        ) : `{{ ${field.fieldname} }}` : frappe.format(
          MainStore.docData[field.fieldname],
          { fieldtype: field.fieldtype, options: field.options },
          { inline: true },
          MainStore.docData
        );
``` 
 ```_a2[0][field.fieldname]``` here that poses a problem
