### ISSUE TITLE
Feat: Allow printing hidden fields

### ISSUE THREAD

**Issue by batonac** [frappe/print_designer#65]
I assume this may be controversial, so I'm raising it as an issue for discussion. Print Designer currently prevents the selection of any field with the attribute "Print Hide" set. This would seem justifiable on the surface, but I'm suggesting the removal of this limitation for the following reasons:

1. The "Print Hide" field attribute is incredibly useful for auto-generated print formats. From that vantage point, it has enduring relevance for formats that are auto-generated, both by stock Frappe and, in the future, by the Print Designer. As such, they indicate the assumption of the DocType designer of whether a field should be included in a print-out by default.
2. Many standard DocTypes have fields that could be and are relevant to include in certain print formats, which are marked "Print Hide" by default. For example, the Status field on the Sales Invoice is useful for indicating whether an invoice is paid on a print format, but it's marked "Print Hide" by ERPNext.
3. Incorporating a dynamic field in a Print Format using the Print Designer requires a great deal of intentionality on the part of the user. Because fields are only added if they are explicitly wanted, this represents quite a different scenario from an auto-generated print format, which is the primary use-case for the "Print Hide" attribute.
4. The "Print Hide" attribute is somewhat obscure, and it creates a very confusing UX for users when fields are obviously present on the DocType but not available for selection in the Print Designer.

In light of the above, I am proposing that the filter be removed and all fields become available for selection in the Print Designer, regardless of the "Print Hide" attribute.

**Comment by maharshivpatel** [comment]
You could have also created discussion 😅

anyways, reason for hiding those fields is that we don't want to overwhelm the users with so many fields and having meta of doctype as source of truth is also good to prevent cases like someone accidentally choosing the field that they are not suppose to. user can always unhide from doctype.

i am not against your proposal but will have to think about it. we can show hidden field by toggle and a friendly warning that you are printing hidden fields

**Comment by batonac** [comment]
> You could have also created discussion 😅

Of course, noted 😳

> i am not against your proposal but will have to think about it. we can show hidden field by toggle and a friendly warning that you are printing hidden fields

I like the idea of a toggle 😀👍
