### ISSUE TITLE
Not able to access print-designer in browser

### ISSUE THREAD

**Issue by yugajoshi** [frappe/print_designer#67]
I have hosted erpnext on AWS instance and it is multitenant site. On this instance, earlier I had 2 sites. To install print-designer app I have  followed commands given on github. After this, print-designer.test site was created on which the app is installed. To access the site, I logged in to site by entering print-designer.test. But after entering the app name in URL, it is saying no app found

**Comment by maharshivpatel** [comment]
You will need to enter your sites url and not  print-designer.test . for example https://your-domain-name.com

**Comment by yugajoshi** [comment]
After logging in it is not showing in installed apps. Initially I have mfs.com as my site. Now there is one more site added print-designer.test. I am entering IP address of my cloud instance in browser to access it. Is it correct way to access it?

**Comment by maharshivpatel** [comment]
you need to point a real domain or subdomain and install it on that.

for example. setup dns for print-designer.mfs.com then create site for print-designer.mfs.com and install print designer on it.

**Comment by maharshivpatel** [comment]
@yugajoshi are you able to access now ? please share more information if you are still facing the issue

**Comment by yugajoshi** [comment]
Yes now it’s accessible. Earlier trying to access it in wrong way. The other issue is- in your YouTube video, I can see the table option below Image icon. But in my app I am seeing barcode option and there is no table option.On 13-Oct-2023, at 11:59 AM, Maharshi Patel ***@***.***> wrote:﻿
@yugajoshi are you able to access now ? please share more information if you are still facing the issue

**Comment by maharshivpatel** [comment]
@yugajoshi Table option is not available because in your selected  document/doctype there is no child table so there is nothing to print in table. hence, table is not visible. select doctype that have child table ( eg. sales invoice ) or add child table to your existing doctype.
