### ISSUE TITLE
Z-axis on objects 

### ISSUE THREAD

**Issue by IvanGuevaraM** [frappe/print_designer#68]
This development is just great! 

I have tried the app, and the only function that i can´t find is the z-axis, to change the order of the objects.

In other idea, i´m working to develop a way to have multiple print settings on frappe, perhaps diferent settings for company and doctype. Settings like paper size ¨Letter¨for Employee info print, and another print settings "Employe" for Customized paper size for id badging...

Thank you so much for the contribution

**Comment by maharshivpatel** [comment]
You don't need z axis because element will go inside other element if it's rectangle. can you share use case where you need z axis ?

you can create format for any page size in print designer. select letter or just type in width and height for custom size

**Comment by IvanGuevaraM** [comment]
The use case is for design ID badges, if we use a print format and duplicate it to use it as template for other badge id template, is better to start a new one, for the cases that designer have to change some object order.

The print (result pdf) of print designer is excelent. But by default we have selected "Letter" to print all the DocTypes. But for ID badging the customized size for a CR80, on the preview page of Frappe gets very out of bounds.  
Dont looks good on print preview, but it works.

**Comment by IvanGuevaraM** [comment]
... on the layers colum. Looks like the object order can be changed.

**Comment by maharshivpatel** [comment]
> But by default we have selected "Letter" to print all the DocTypes. 

Go to the sidebar of print designer, In sidebar enter your custom size 54 mm ( width ) x 86 mm ( height ) and it will print in that size only even if you selected letter. look at the image below.

<img width="1335" alt="Screenshot 2023-10-14 at 9 37 24 AM" src="https://github.com/frappe/print_designer/assets/39730881/fe8d5a81-6b7e-4057-83ec-5894bb418d74">

> But for ID badging the customized size for a CR80, on the preview page of Frappe gets very out of bounds.

> Dont looks good on print preview, but it works.

I tried and looks ok, can you please share screenshot of how it gets very out of bounds

<img width="1440" alt="Screenshot 2023-10-14 at 9 44 34 AM" src="https://github.com/frappe/print_designer/assets/39730881/c6fd9729-711f-48d1-bbb7-9552e82c8e74">

<img width="1440" alt="Screenshot 2023-10-14 at 9 44 46 AM" src="https://github.com/frappe/print_designer/assets/39730881/91fcb1e9-34d8-4c99-acc4-77924010c92f">


> ... on the layers colum. Looks like the object order can be changed.


That is work in progress feature. someday, layers panel  will have actions 🤞. lock, group, axis etc.

**Comment by maharshivpatel** [comment]
fixed by #252
