### ISSUE TITLE
Option to add separator for child table rows 

### ISSUE THREAD

**Issue by girumtibebu** [frappe/print_designer#71]
I am not sure if its implemented from print designer side but if there's an option to add a separator row that we can give title and all th columns merged for that we can have a more organized row lists. Especially on long lows it is essential to group the items. Currently what i did is created an item called separator and used a custom jinja template so whenever users add that item while preparing quotations it'll be displayed as a separator.

**Comment by girumtibebu** [comment]
I suggest two options: 
1. On items doctype adding Separator toggle like  the Page Break toggle. Whenever separator toggle is on it displays separator option fileds like title, background color and more. Then the print designer checks for the separator toggle and it adds a separator row and assign the visual settings like all the columns, giving it a background color and title.
2. To have an 'add a separator' button similar to 'add row' button in the child table. Then it adds a row that we can give title. On the print format designer will render it as a separator merging all the columns, giving it a background color and title.

Both ways my suggestion is adding fields to items doctype and customizing rendering of the rows using css based on the fields from item doctype.

**Comment by maharshivpatel** [comment]
@girumtibebu This is good idea but we can't add anything to items doctype. whatever we add needs to apply on all child tables. We can go this route but this will require some brainstorming and will take time.

**Comment by girumtibebu** [comment]
Yeah it's more of a hack than formal approach.
Currently this is how we use it. We have an item called separator, so whenever we want to add a separator we add that item, and add the give its a description on the form view. We have a custom html with jinja template while populating the table whenever it gets an item with name 'separator' it gives the row a custom css and renderes the item description title for separator.
![image](https://github.com/frappe/print_designer/assets/5276422/87744f9f-a343-4405-8862-6c34d0dd46d9)
![image](https://github.com/frappe/print_designer/assets/5276422/1cf6b6aa-3cbe-466b-9989-41cf60a09d15)

I don't know if its a good user experience to adopt its a standard tho.

**Comment by maharshivpatel** [comment]
This is edge case and is not planned to be implemented in print designer as of now. Thank you.
