### ISSUE TITLE
The final view is different from the designed view.

### ISSUE THREAD

**Issue by 2old4thisShit** [frappe/print_designer#73]
I am designing some printing formats and I find that the final view is different from the designed view.

This is my original design:
![image](https://github.com/frappe/print_designer/assets/46288096/3f90ffca-a9a6-4a71-a8b4-e246a8d3ba51)

This is the final view:
![image](https://github.com/frappe/print_designer/assets/46288096/8f4cb813-8c67-4447-b63a-56934600a3aa)
![image](https://github.com/frappe/print_designer/assets/46288096/e7df6352-2b81-4a7f-9bf3-f086c6a59236)

bench version:

![image](https://github.com/frappe/print_designer/assets/46288096/d1ce5337-6ece-44b9-84ec-e7a7219321c0)

PDF VIEW
[EXP-2023-000202.pdf](https://github.com/frappe/print_designer/files/13207205/EXP-2023-000202.pdf)

PRINT VIEW:
![image](https://github.com/frappe/print_designer/assets/46288096/50e77ad3-7327-42fa-9d1f-4996222aca31)

**Comment by maharshivpatel** [comment]
Frappe / Print Designer requires at least  [version 0.12.5 with patched qt](https://frappeframework.com/docs/v14/user/en/installation#pre-requisites)

Install correct version by following [installation guide](https://frappeframework.com/docs/v14/user/en/installation) and confirm : 

```
wkhtmltopdf --version
```
output should be similar to `wkhtmltopdf 0.12.6 (with patched qt)`


### can you share your format like this :
You can paste the data here ( change any personal info )

https://github.com/frappe/print_designer/assets/39730881/b7b761c7-a2b1-43d4-a3b3-0dde25ba9699

**Comment by 2old4thisShit** [comment]
That guide installs the version that was already installed and does not mention "patched qt"

wkhtmltopdf 0.12.6
![image](https://github.com/frappe/print_designer/assets/46288096/59c5d01d-dcc4-4562-a272-7b4de8bd3074)


Data:

{"name":"Esquela tipo 1","creation":"2023-10-27 08:39:31.105541","modified":"2023-10-30 16:49:30.494896","modified_by":"Administrator","docstatus":0,"idx":0,"print_designer_after_table":"[]","print_designer_settings":"{\"page\":{\"height\":1122.52,\"width\":793.701,\"marginTop\":0,\"marginBottom\":0,\"marginLeft\":0,\"marginRight\":0,\"headerHeight\":0,\"footerHeight\":0,\"UOM\":\"mm\",\"headerHeightWithMargin\":0,\"footerHeightWithMargin\":0},\"pdfPrintDPI\":96,\"globalStyles\":{\"staticText\":{\"isGlobalStyle\":true,\"styleEditMode\":\"main\",\"labelDisplayStyle\":\"standard\",\"type\":\"text\",\"isDynamic\":false,\"mainRuleSelector\":\".staticText\",\"style\":{\"display\":\"inline-block\",\"fontFamily\":\"Inter\",\"fontSize\":\"14px\",\"fontWeight\":400,\"color\":\"#000000\",\"textAlign\":\"left\",\"fontStyle\":\"normal\",\"textDecoration\":\"none\",\"textTransform\":\"none\",\"lineHeight\":1.25,\"letterSpacing\":\"0px\",\"contenteditable\":false,\"border\":\"none\",\"borderWidth\":\"0px\",\"borderColor\":\"#000000\",\"borderStyle\":\"solid\",\"borderRadius\":0,\"backgroundColor\":\"#ffffff\",\"paddingTop\":\"0px\",\"paddingBottom\":\"0px\",\"paddingLeft\":\"0px\",\"paddingRight\":\"0px\",\"margin\":\"0px\",\"minWidth\":\"0px\",\"minHeight\":\"0px\",\"boxShadow\":\"none\",\"overflow\":\"hidden\",\"overflowWrap\":\"break-word\",\"whiteSpace\":\"normal\",\"userSelect\":\"none\",\"opacity\":1,\"zIndex\":1},\"mainCssRule\":{}},\"dynamicText\":{\"isGlobalStyle\":true,\"styleEditMode\":\"main\",\"labelDisplayStyle\":\"standard\",\"type\":\"text\",\"isDynamic\":true,\"mainRuleSelector\":\".dynamicText\",\"labelRuleSelector\":\".dynamicText .label-text\",\"style\":{\"display\":\"inline-block\",\"fontFamily\":\"Inter\",\"fontSize\":\"14px\",\"fontWeight\":400,\"color\":\"#000000\",\"textAlign\":\"left\",\"fontStyle\":\"normal\",\"textDecoration\":\"none\",\"textTransform\":\"none\",\"lineHeight\":1.25,\"letterSpacing\":\"0px\",\"contenteditable\":false,\"border\":\"none\",\"borderWidth\":\"0px\",\"borderColor\":\"#000000\",\"borderStyle\":\"solid\",\"borderRadius\":0,\"backgroundColor\":\"#ffffff\",\"paddingTop\":\"0px\",\"paddingBottom\":\"0px\",\"paddingLeft\":\"0px\",\"paddingRight\":\"0px\",\"margin\":\"0px\",\"minWidth\":\"0px\",\"minHeight\":\"0px\",\"boxShadow\":\"none\",\"overflow\":\"hidden\",\"overflowWrap\":\"break-word\",\"whiteSpace\":\"normal\",\"userSelect\":\"none\",\"opacity\":1},\"labelStyle\":{\"fontFamily\":\"Inter\",\"fontSize\":\"14px\",\"fontWeight\":600,\"color\":\"#000000\",\"textAlign\":\"left\",\"fontStyle\":\"normal\",\"textDecoration\":\"none\",\"textTransform\":\"none\",\"lineHeight\":1.25,\"letterSpacing\":\"0px\",\"border\":\"none\",\"borderWidth\":\"0px\",\"borderColor\":\"#000000\",\"borderStyle\":\"solid\",\"borderRadius\":0,\"backgroundColor\":\"#ffffff\",\"paddingTop\":\"0px\",\"paddingBottom\":\"0px\",\"paddingLeft\":\"0px\",\"paddingRight\":\"0px\",\"margin\":\"0px\",\"minWidth\":\"0px\",\"minHeight\":\"0px\",\"boxShadow\":\"none\",\"whiteSpace\":\"normal\",\"userSelect\":\"none\",\"opacity\":1,\"zIndex\":1},\"mainCssRule\":{},\"labelCssRule\":{}},\"rectangle\":{\"isGlobalStyle\":true,\"styleEditMode\":\"main\",\"type\":\"rectangle\",\"isDynamic\":false,\"mainRuleSelector\":\".rectangle\",\"style\":{\"display\":\"inline-flex\",\"justifyContent\":\"flex-start\",\"alignItems\":\"flex-start\",\"alignContent\":\"flex-start\",\"flex\":1,\"paddingTop\":\"0px\",\"paddingBottom\":\"0px\",\"paddingLeft\":\"0px\",\"paddingRight\":\"0px\",\"margin\":\"0px\",\"whiteSpace\":\"normal\",\"userSelect\":\"none\",\"minWidth\":\"0px\",\"minHeight\":\"0px\",\"color\":\"#000000\",\"backgroundColor\":\"#ffffff\",\"border\":\"1px solid black\",\"borderColor\":\"#000000\",\"borderStyle\":\"solid\",\"borderWidth\":\"1px\",\"boxSizing\":\"border-box\",\"outline\":\"none\",\"borderRadius\":0,\"boxShadow\":\"none\",\"opacity\":1,\"zIndex\":0},\"mainCssRule\":{}},\"image\":{\"isGlobalStyle\":true,\"styleEditMode\":\"main\",\"type\":\"image\",\"isDynamic\":false,\"mainRuleSelector\":\".image\",\"style\":{\"display\":\"block\",\"border\":\"none\",\"borderWidth\":\"0px\",\"borderColor\":\"#000000\",\"borderStyle\":\"solid\",\"borderRadius\":0,\"backgroundColor\":\"\",\"paddingTop\":\"0px\",\"paddingBottom\":\"0px\",\"paddingLeft\":\"0px\",\"paddingRight\":\"0px\",\"margin\":\"0px\",\"minWidth\":\"0px\",\"minHeight\":\"0px\",\"boxShadow\":\"none\",\"whiteSpace\":\"normal\",\"userSelect\":\"none\",\"objectFit\":\"scale-down\",\"objectPosition\":\"center center\",\"backgroundSize\":\"contain\",\"backgroundPosition\":\"center center\",\"backgroundRepeat\":\"no-repeat\",\"opacity\":1},\"mainCssRule\":{}},\"barcode\":{\"isGlobalStyle\":true,\"styleEditMode\":\"main\",\"type\":\"barcode\",\"isDynamic\":false,\"mainRuleSelector\":\".barcode\",\"style\":{\"display\":\"block\",\"border\":\"none\",\"borderWidth\":\"0px\",\"borderColor\":\"#000000\",\"borderStyle\":\"solid\",\"borderRadius\":0,\"backgroundColor\":\"\",\"paddingTop\":\"0px\",\"paddingBottom\":\"0px\",\"paddingLeft\":\"0px\",\"paddingRight\":\"0px\",\"margin\":\"0px\",\"minWidth\":\"0px\",\"minHeight\":\"0px\",\"boxShadow\":\"none\",\"whiteSpace\":\"normal\",\"userSelect\":\"none\",\"opacity\":1},\"mainCssRule\":{}},\"table\":{\"isGlobalStyle\":true,\"styleEditMode\":\"main\",\"labelDisplayStyle\":\"standard\",\"type\":\"table\",\"isDynamic\":true,\"mainRuleSelector\":\".printTable td\",\"headerRuleSelector\":\".printTable th\",\"labelRuleSelector\":\".printTable .label-text\",\"style\":{\"fontFamily\":\"Inter\",\"fontSize\":\"10px\",\"fontWeight\":400,\"color\":\"#000000\",\"textAlign\":\"left\",\"fontStyle\":\"normal\",\"textDecoration\":\"none\",\"textTransform\":\"none\",\"lineHeight\":1.25,\"letterSpacing\":\"0px\",\"contenteditable\":false,\"border\":\"none\",\"borderWidth\":\"1px\",\"borderColor\":\"#000000\",\"borderStyle\":\"solid\",\"borderRadius\":0,\"backgroundColor\":\"#ffffff\",\"paddingTop\":\"10px\",\"paddingBottom\":\"10px\",\"paddingLeft\":\"10px\",\"paddingRight\":\"10px\",\"margin\":\"0px\",\"minWidth\":\"0px\",\"minHeight\":\"0px\",\"boxShadow\":\"none\",\"overflowWrap\":\"break-word\",\"whiteSpace\":\"normal\",\"userSelect\":\"none\",\"verticalAlign\":\"baseline\",\"opacity\":1},\"labelStyle\":{\"fontFamily\":\"Inter\",\"fontSize\":\"10px\",\"fontWeight\":600,\"color\":\"#000000\",\"textAlign\":\"left\",\"fontStyle\":\"normal\",\"textDecoration\":\"none\",\"textTransform\":\"none\",\"lineHeight\":1.25,\"letterSpacing\":\"0px\",\"border\":\"none\",\"borderWidth\":\"0px\",\"borderColor\":\"#000000\",\"borderStyle\":\"solid\",\"borderRadius\":0,\"backgroundColor\":\"#ffffff\",\"paddingTop\":\"0px\",\"paddingBottom\":\"0px\",\"paddingLeft\":\"0px\",\"paddingRight\":\"0px\",\"margin\":\"0px\",\"minWidth\":\"0px\",\"minHeight\":\"0px\",\"boxShadow\":\"none\",\"whiteSpace\":\"normal\",\"userSelect\":\"none\",\"opacity\":1,\"verticalAlign\":\"baseline\",\"zIndex\":1},\"headerStyle\":{\"fontFamily\":\"Inter\",\"fontSize\":\"11px\",\"fontWeight\":600,\"color\":\"#000000\",\"textAlign\":\"left\",\"fontStyle\":\"normal\",\"textDecoration\":\"none\",\"textTransform\":\"none\",\"lineHeight\":1.25,\"letterSpacing\":\"0px\",\"border\":\"none\",\"borderWidth\":\"1px\",\"borderColor\":\"#000000\",\"borderStyle\":\"solid\",\"borderRadius\":0,\"backgroundColor\":\"#ffffff\",\"paddingTop\":\"10px\",\"paddingBottom\":\"10px\",\"paddingLeft\":\"10px\",\"paddingRight\":\"10px\",\"margin\":\"0px\",\"minWidth\":\"0px\",\"minHeight\":\"0px\",\"boxShadow\":\"none\",\"whiteSpace\":\"normal\",\"userSelect\":\"none\",\"opacity\":1,\"zIndex\":1},\"mainCssRule\":{},\"labelCssRule\":{},\"headerCssRule\":{}}},\"currentPageSize\":\"A4\",\"isHeaderFooterAuto\":false,\"currentDoc\":\"EXP-2023-000202\",\"textControlType\":\"dynamic\",\"currentFonts\":[\"Inter\"],\"printHeaderFonts\":null,\"printFooterFonts\":null,\"printBodyFonts\":{\"Inter\":{\"weight\":[400,600],\"italic\":[]}}}","print_designer_header":"[]","print_designer_footer":"[]","print_designer_body":"[{\"id\":\"gCkjnybHlD\",\"type\":\"text\",\"content\":\"\",\"contenteditable\":false,\"isDynamic\":true,\"isFixedSize\":true,\"dynamicContent\":[{\"doctype\":\"\",\"parentField\":\"\",\"fieldname\":\"contenido_esquela\",\"value\":\"<div class=\\\"ql-editor read-mode\\\"><h1 style=\\\"text-align: center;\\\"><span style=\\\"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);\\\">Lorem Ipsum</span></h1><h4 style=\\\"text-align: center;\\\"><em style=\\\"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); font-size: 14px;\\\">\\\"Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...\\\"</em></h4><h5 style=\\\"text-align: center;\\\"><span style=\\\"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); font-size: 12px;\\\">\\\"There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain...\\\"</span></h5><p style=\\\"text-align: justify;\\\"><span style=\\\"background-color: rgb(255, 255, 255); font-size: 14px; color: rgb(0, 0, 0);\\\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ut feugiat nisi. Aenean gravida porta odio et venenatis. Aliquam finibus lacinia elit ut cursus. Aenean vitae vulputate nisi. Vivamus consequat dui quis semper pretium. Phasellus at consequat lacus. Morbi vel ultricies orci. Fusce scelerisque fringilla malesuada. Quisque tempor ac neque accumsan efficitur. Donec blandit eget ex ut tempor. Ut vel pellentesque lectus. Nullam eu sapien commodo diam pharetra finibus imperdiet sed orci. Nullam blandit odio leo, vitae tristique eros finibus quis. Nam non massa erat. Quisque et erat vulputate, porttitor mauris eget, malesuada quam. Etiam eleifend ligula massa, sit amet venenatis nisl lacinia at.</span></p><p style=\\\"text-align: justify;\\\"><span style=\\\"background-color: rgb(255, 255, 255); font-size: 14px; color: rgb(0, 0, 0);\\\">Praesent eleifend a orci a sollicitudin. Donec eget viverra justo, at convallis lacus. Pellentesque scelerisque venenatis eros, vitae congue erat finibus vitae. Aliquam erat volutpat. In sed augue interdum, sollicitudin metus a, euismod dui. Donec blandit vestibulum magna vel rhoncus. Etiam vulputate, tellus sit amet scelerisque placerat, enim ex cursus nisl, nec mattis ex metus at nunc. Donec nec facilisis libero, quis imperdiet lorem. Vestibulum dictum egestas velit, eget porta erat sodales at. Integer pretium risus dui, in iaculis metus sodales non. Phasellus ut turpis eu odio suscipit rhoncus. Ut sit amet justo nisl.</span></p><p style=\\\"text-align: justify;\\\"><span style=\\\"background-color: rgb(255, 255, 255); font-size: 14px; color: rgb(0, 0, 0);\\\">Pellentesque condimentum, eros in mattis egestas, sapien lacus tristique justo, non mattis ligula neque et sapien. Quisque tincidunt enim eget bibendum mollis. Nullam facilisis dui gravida justo vulputate aliquet. Sed eu quam ut elit egestas eleifend. Vivamus viverra est ac mattis interdum. Suspendisse scelerisque velit nec tellus ullamcorper pretium. Vestibulum vitae vulputate nisl. Fusce vestibulum, elit dapibus sollicitudin finibus, massa nisi ultricies nisi, vel fringilla nibh felis quis quam. Quisque elementum, mi sed aliquam laoreet, turpis nisl eleifend libero, ut egestas nibh sapien ac purus. Phasellus id hendrerit sem. Pellentesque metus risus, lacinia a pulvinar et, finibus vitae eros.</span></p><p style=\\\"text-align: justify;\\\"><span style=\\\"background-color: rgb(255, 255, 255); font-size: 14px; color: rgb(0, 0, 0);\\\">Integer non magna eros. Donec eleifend tortor eget diam suscipit ornare. In hac habitasse platea dictumst. In sit amet nunc id ante placerat hendrerit et sed nisi. In non turpis est. Maecenas quis lacus libero. Cras ac leo et tortor auctor condimentum elementum sit amet odio. In vitae tristique sapien, ac ultrices nisi. Vestibulum eget diam vestibulum, sagittis metus sed, tincidunt nisl. Sed tempor diam vel ligula euismod auctor.</span></p><p style=\\\"text-align: justify;\\\"><span style=\\\"background-color: rgb(255, 255, 255); font-size: 14px; color: rgb(0, 0, 0);\\\">Quisque a lacus ante. Etiam scelerisque tincidunt velit, venenatis tincidunt erat dignissim nec. Pellentesque tortor nunc, lobortis eu vehicula eu, porta convallis velit. Praesent eget gravida risus. Curabitur quis ante rutrum, euismod mauris eget, fermentum ante. Pellentesque at consequat lectus. Mauris eget ipsum nec lacus vulputate fringilla. Cras elementum ullamcorper felis sed molestie. Curabitur quis ornare orci. Mauris viverra, mi a bibendum facilisis, lacus ligula luctus augue, dictum bibendum arcu lorem vehicula orci. Etiam pulvinar nunc vel enim mollis, id accumsan lectus congue. Maecenas purus purus, lacinia at diam id, eleifend volutpat ipsum. Integer ornare vulputate libero, quis pulvinar leo rhoncus sit amet. Ut interdum elit sit amet nunc ullamcorper dapibus. Curabitur ullamcorper eros libero, in placerat justo faucibus et. Praesent tincidunt urna diam, id auctor ipsum finibus eu.</span></p><p><br></p></div>\",\"fieldtype\":\"Text Editor\",\"label\":\"Contenido :\",\"is_labelled\":false,\"is_static\":false,\"style\":{},\"labelStyle\":{},\"nextLine\":true,\"labelStyleEditing\":false}],\"selectedDynamicText\":null,\"isDraggable\":true,\"isResizable\":true,\"isDropZone\":false,\"startX\":37,\"startY\":194,\"pageX\":499,\"pageY\":-65,\"width\":736.703125,\"height\":767.953125,\"styleEditMode\":\"main\",\"labelDisplayStyle\":\"standard\",\"style\":{},\"labelStyle\":{},\"classes\":[],\"printY\":194},{\"id\":\"SmDerantIB\",\"type\":\"image\",\"isDraggable\":true,\"isResizable\":true,\"isDropZone\":false,\"isDynamic\":false,\"image\":{\"name\":\"4986b260ef\",\"file_name\":\"loremipsum-630x315.jpg\",\"file_url\":\"/files/loremipsum-630x315.jpg\",\"modified\":\"2023-10-30 16:49:26.054231\"},\"startX\":36,\"startY\":31,\"pageX\":493,\"pageY\":129,\"width\":281,\"height\":87,\"styleEditMode\":\"main\",\"style\":{},\"classes\":[],\"printY\":31}]","print_designer":1,"doc_type":"XF Expediente","module":"Xestion Funeraria Raul","standard":"No","custom_format":0,"disabled":0,"print_format_type":"Jinja","raw_printing":0,"margin_top":15,"margin_bottom":15,"margin_left":15,"margin_right":15,"align_labels_right":0,"show_section_headings":0,"line_breaks":0,"absolute_value":0,"font_size":14,"page_number":"Hide","css":".staticText { display: inline-block; font-family: Inter; font-size: 14px; font-weight: 400; color: rgb(0, 0, 0); text-align: left; font-style: normal; text-decoration: none; text-transform: none; line-height: 1.25; letter-spacing: 0px; border: 0px solid rgb(0, 0, 0); border-radius: 0px; background-color: rgb(255, 255, 255); padding: 0px; margin: 0px; min-width: 0px; min-height: 0px; box-shadow: none; overflow: hidden; overflow-wrap: break-word; white-space: normal; user-select: none; opacity: 1; z-index: 1; } .dynamicText { display: inline-block; font-family: Inter; font-size: 14px; font-weight: 400; color: rgb(0, 0, 0); text-align: left; font-style: normal; text-decoration: none; text-transform: none; line-height: 1.25; letter-spacing: 0px; border: 0px solid rgb(0, 0, 0); border-radius: 0px; background-color: rgb(255, 255, 255); padding: 0px; margin: 0px; min-width: 0px; min-height: 0px; box-shadow: none; overflow: hidden; overflow-wrap: break-word; white-space: normal; user-select: none; opacity: 1; } .dynamicText .label-text { font-family: Inter; font-size: 14px; font-weight: 600; color: rgb(0, 0, 0); text-align: left; font-style: normal; text-decoration: none; text-transform: none; line-height: 1.25; letter-spacing: 0px; border: 0px solid rgb(0, 0, 0); border-radius: 0px; background-color: rgb(255, 255, 255); padding: 0px; margin: 0px; min-width: 0px; min-height: 0px; box-shadow: none; white-space: normal; user-select: none; opacity: 1; z-index: 1; } .rectangle { display: inline-flex; place-content: flex-start; align-items: flex-start; flex: 1 1 0%; padding: 0px; margin: 0px; white-space: normal; user-select: none; min-width: 0px; min-height: 0px; color: rgb(0, 0, 0); background-color: rgb(255, 255, 255); border: 1px solid rgb(0, 0, 0); box-sizing: border-box; outline: none; border-radius: 0px; box-shadow: none; opacity: 1; z-index: 0; } .image { display: block; border: 0px solid rgb(0, 0, 0); border-radius: 0px; padding: 0px; margin: 0px; min-width: 0px; min-height: 0px; box-shadow: none; white-space: normal; user-select: none; object-fit: scale-down; object-position: center center; background-size: contain; background-position: center center; background-repeat: no-repeat; opacity: 1; } .barcode { display: block; border: 0px solid rgb(0, 0, 0); border-radius: 0px; padding: 0px; margin: 0px; min-width: 0px; min-height: 0px; box-shadow: none; white-space: normal; user-select: none; opacity: 1; } .printTable td { font-family: Inter; font-size: 10px; font-weight: 400; color: rgb(0, 0, 0); text-align: left; font-style: normal; text-decoration: none; text-transform: none; line-height: 1.25; letter-spacing: 0px; border: 1px solid rgb(0, 0, 0); border-radius: 0px; background-color: rgb(255, 255, 255); padding: 10px; margin: 0px; min-width: 0px; min-height: 0px; box-shadow: none; overflow-wrap: break-word; white-space: normal; user-select: none; vertical-align: baseline; opacity: 1; } .printTable .label-text { font-family: Inter; font-size: 10px; font-weight: 600; color: rgb(0, 0, 0); text-align: left; font-style: normal; text-decoration: none; text-transform: none; line-height: 1.25; letter-spacing: 0px; border: 0px solid rgb(0, 0, 0); border-radius: 0px; background-color: rgb(255, 255, 255); padding: 0px; margin: 0px; min-width: 0px; min-height: 0px; box-shadow: none; white-space: normal; user-select: none; opacity: 1; vertical-align: baseline; z-index: 1; } .printTable th { font-family: Inter; font-size: 11px; font-weight: 600; color: rgb(0, 0, 0); text-align: left; font-style: normal; text-decoration: none; text-transform: none; line-height: 1.25; letter-spacing: 0px; border: 1px solid rgb(0, 0, 0); border-radius: 0px; background-color: rgb(255, 255, 255); padding: 10px; margin: 0px; min-width: 0px; min-height: 0px; box-shadow: none; white-space: normal; user-select: none; opacity: 1; z-index: 1; } :root { --scale-factor: 1px; --modal-x: 0px; --modal-y: 0px; } :root, ::after, ::before { --print-width: 210.000mm; --print-height: 297.000mm; --print-container-width: 210.000mm; --print-container-height: 297.000mm; --print-margin-top: 0mm; --print-margin-bottom: 0.000mm; --print-margin-left: 0mm; --print-margin-right: 0.000mm; }@page { size: 210mm 297mm; margin: 0mm; } @page { size: 210mm 297mm; margin: 0mm; } @page { size: 210mm 297mm; margin: 0mm; }","print_format_builder":0,"print_format_builder_beta":0,"doctype":"Print Format","__onload":{"print_templates":[]},"__last_sync_on":"2023-10-30T16:16:41.119Z"}

**Comment by maharshivpatel** [comment]
@2old4thisShit Which platform (OS) are you using ?

**Comment by 2old4thisShit** [comment]
![image](https://github.com/frappe/print_designer/assets/46288096/3f9ac24b-ddfd-4645-b411-214f7644315e)

**Comment by 2old4thisShit** [comment]
I have updated to wkhtmltopdf 0.12.6.1 (with patched qt):

wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.jammy_amd64.deb
sudo dpkg -i wkhtmltox_0.12.6.1-2.jammy_amd64.deb
sudo apt-get install -f
wkhtmltopdf --version

![image](https://github.com/frappe/print_designer/assets/46288096/1e3cc3a3-6248-41b3-8051-d8fee94fccb7)

But the problem persists

**Comment by maharshivpatel** [comment]
@2old4thisShit So there is a bug which should be fixed in 1-2 that will fix the position of text. 

There shouldn't be any other styling issue, can you confirm that ?

**Comment by 2old4thisShit** [comment]
No, just this one. Nothing else.

Previously some image was not showing, but right now I can't reproduce. If it happens again, I'll open a new issue.

**Comment by 2old4thisShit** [comment]
Hi. Any news about this?
