### ISSUE TITLE
export design to code

### ISSUE THREAD

**Issue by 2old4thisShit** [frappe/print_designer#81]
Would it be possible to add a function that allows export the html and css code (I don't know if this is generated) from the design made with the print designer?

This would open the possibility of continuing to work with the html and css in another temporary design in case of a problem with the app, a bug...

**Comment by maharshivpatel** [comment]
@2old4thisShit if you know what you are doing you can go to print format doctype and change css, and object properties that renders html, you can also overwrite main.html jinja template in the print designer code. 

if you mean generate jinja template answer is no. reason for this is print designer is built to avoid writing code. technically you can do whatever you want if you understand how print designer works. if you have anything specific let me know! i can help you.

**Comment by maharshivpatel** [comment]
@2old4thisShit closing this as print designer doesn't export the code and workaround is as shared in the previous comment. If you have more questions suggestions please open new Issue. Thank you for sharing Issue
