### ISSUE TITLE
Add backlink for desk access, All fields of a doctype are not fetched

### ISSUE THREAD

**Issue by Omair1998** [frappe/print_designer#84]
1. Add Backlink for Desk: Encountering difficulty transitioning from the print designer to the desk for seamless navigation.

2. Add Fields:  Not all fields are being retrieved entirely, including the Total Tax and Charges, Additional Discount field and the absence of the QR code field in the sales invoice, as depicted in the image below.

![Screenshot 2023-11-16 132538](https://github.com/frappe/print_designer/assets/149870767/77a35a2b-b7cb-4498-adcf-f5209562dd5d)

**Comment by maharshivpatel** [comment]
1. Yeah, I am sorry about that. I was working on the exit button instead of the logo because the logo is not the same as the desk. I will fix this.
2. Not Sure what you mean can you please share one example.

**Comment by batonac** [comment]
As per the fields mentioned, point 2 is referring to #65

**Comment by Omair1998** [comment]
@maharshivpatel We are not able to add additional_discount_amount field to the invoice as a dynamic text because we don't see that field in the options. As you can see in the screenshot under currency we only see 4 fields. What about additional_discount_amount ??

**Comment by maharshivpatel** [comment]
@Omair1998 you can uncheck hidden from doctype and then it will be visible here. i will try to add hidden fields as @batonac shared the issue

**Comment by mujeerhashmi** [comment]
@maharshivpatel The field was not hidden bit print_hide property was selected for the additional_discount_field.
At the same time can you please explain to us how to bring the invoice QR Code into the print format. The QR code is a Attach Image field type which gets generated with each invoice on submission & gets attached to the Sales Invoice.
We failed with barcode & image features of print designer as of now. May be we are missing something basic to do this.

**Comment by maharshivpatel** [comment]
@mujeerhashmi Thanks 😅 i meant print_hide only.
You need to use the dynamic image feature in case it's already generated QR/barcode image like [this](https://youtu.be/XpmrLzbianE?si=8nL17734uV8EfxPf&t=363).

**Comment by mujeerhashmi** [comment]
We are not able to see the "ksa_einv_qr" image in the dynamic image options. However the customer_image option show up even though the field has print_hide selected.

![Screenshot from 2023-11-20 18-05-27](https://github.com/frappe/print_designer/assets/12420747/e12a4817-01d7-40a0-ae6a-ce973db9c23b)

**Comment by maharshivpatel** [comment]
@mujeerhashmi i will handle hidden fields in issue #65 . please follow there for updates. 
Thank you for reporting issue.

**Comment by maharshivpatel** [comment]
@mujeerhashmi Field needs to be `Image` or `Attach Image` because otherwise we can't be sure it will have image and not other kind of files. you need to change field type of Image or ask custom app developer to do it for you.

**Comment by Omair1998** [comment]
@maharshivpatel The field is set to 'Attach Image,' although it's not displaying in the dynamic image.
