### ISSUE TITLE
python-barcode version conflict with India compliance

### ISSUE THREAD

**Issue by HUMENTH** [frappe/print_designer#89]
Print designer and India Compliance apps dependencies version conflicting.

> print-designer 1.0.0 requires python-barcode~=0.13.1
india-compliance 15.0.2 requires python-barcode~=0.15.1

![image](https://github.com/frappe/print_designer/assets/4609678/4f0dc9b1-0845-41e4-b70a-343984954244)

**Comment by maharshivpatel** [comment]
@HUMENTH raise PR if interested by updating here : https://github.com/frappe/print_designer/blob/446039e7e69cf9d5ae4f754062ae5da2c0a894dc/pyproject.toml#L13 

I can also update if you wish

**Comment by HUMENTH** [comment]
PR raised #90
