### ISSUE TITLE
Role Permission 

### ISSUE THREAD

**Issue by ajiragroup** [frappe/print_designer#92]
When I installed first Print Designer on my erpnext instance, I found that all the existing users are automatically given access to Print Designer Module.

![image](https://github.com/frappe/print_designer/assets/108009061/6635a1d8-0dd4-41d0-acd2-9ecd341adf6a)

I think this should not be turned on by default to all users.

**Comment by maharshivpatel** [comment]
@ajiragroup it is not accessible to everyone. anyone who has system manager role has access to print designer. do all your users have system manager role ?

**Comment by ajiragroup** [comment]
No. Not all are system managers. We have not checked if everyone can access it. But the print designer module was allowed for all users even if they only have employee access. I think module access should also be disallowed by default to prevent any mis use in case of any permission overlap.

**Comment by maharshivpatel** [comment]
So, the Print Designer Module only have 1 custom page and that page is only allowed for system managers. 
so you can use Print Designer without worrying about everyone having access.

>  I think module access should also be disallowed by default to prevent any misuse in case of any permission overlap.
As of now, there isn't any risk but I understand your concern and will update it. Thank you so much for reporting this.
