### ISSUE TITLE
Export PDF - Alignment Issue 

### ISSUE THREAD

**Issue by dineshpanchal93** [frappe/print_designer#93]
A4 Size Pdf

https://github.com/frappe/print_designer/assets/21578167/cfd593e9-6630-40c3-a073-57bc604abeea

**Comment by dineshpanchal93** [comment]
Or please guide any setup issue?

**Comment by dineshpanchal93** [comment]
While exporting PDF it gives blank space ..

**Comment by maharshivpatel** [comment]
can you share pdf ?

**Comment by dineshpanchal93** [comment]
Print Setting A4 Size 

Print designer Also selected A4 Size

Also While creating a print format it looks good but when export it in right side it gives spaces

same happening with Header and Footer as well.

**Comment by dineshpanchal93** [comment]
[MAT-PRE-2023-00001 (11).pdf](https://github.com/frappe/print_designer/files/13536082/MAT-PRE-2023-00001.11.pdf)

**Comment by maharshivpatel** [comment]
Frappe / Print Designer requires at least  [version 0.12.5 with patched qt](https://frappeframework.com/docs/v14/user/en/installation#pre-requisites)

Install correct version by following [installation guide](https://frappeframework.com/docs/v14/user/en/installation) and confirm : 

```
wkhtmltopdf --version
```
output should be similar to `wkhtmltopdf 0.12.6 (with patched qt)`

**Comment by dineshpanchal93** [comment]
ok Got it.

Let me check

**Comment by maharshivpatel** [comment]
@dineshpanchal93 Let me know if this solves your problem

**Comment by dineshpanchal93** [comment]
Resolved !!!

**Comment by dineshpanchal93** [comment]
@maharshivpatel  Thanks alot for the prompt support.

Thanks
