### ISSUE TITLE
Terms & Conditions text is not resizing and some other issues.

### ISSUE THREAD

**Issue by ramalyb** [frappe/print_designer#95]
Hi @maharshivpatel ,

Your app is amazing and give a very professional look to the print formats. Thank you very much for that.

I have few questions to raise as below,

1. I have added term and condition section just after my other contents and it has different amount of words based on the selected term type. But in the designer, it uses the original fixed size to display the text and the rest is cropped. is there any way to fix this? (Cropped area marked in red)

![image](https://github.com/frappe/print_designer/assets/105539575/e2610bc8-53c7-4e6b-92e4-9ebb9e99878c)

2. When i add second table to the page (Ex: Payment Schedule) and then the main table views look jumbled as it goes back and the added lates table and other fields come top of if rather than going to the bottom of the Item table. please check on this too. this is happenning regardless of the location of the newly added table.

![image](https://github.com/frappe/print_designer/assets/105539575/f0eda99b-b9d7-4e37-9592-334bb83039ee)

3. Which field representing the documents status, like "Draft" in the print format?
4. QR Code not displaying in the preview, although its added and displayed in edit view.
5. Can we save some kind of script and then load it while start design a new one? as i want to keep the logo, header, footer and title positions intact for all the formats.
6. Unable to align row fields in column level, if i do all the columns are affected. but changing fonts and other settings can be done individually per column level.

Thank you,
Ramaly

**Comment by maharshivpatel** [comment]
@ramalyb 
1. Don't Resize the Element it will automatically take up as much space as required.
    - This is just a workaround and will only work if your terms and condition is the last object.
    - Actual Fix: I am working on Introducing Dynamic Containers to solve this problem ( Brainstorming Stage )
2. I will add an option for the Main Table which will repeat the page for the time being.
    - Workaround: If you don't mind repeating it on all pages just put it inside the footer area 😅
    - Actual Fix: I am working on Introducing Dynamic Containers to solve this problem ( Brainstorming Stage )
3. I will add an option to parse Jinja so you can just put in Jinja for such use cases.
4. Can you please share more information on this?
5. You can just go to the Print Format doctype and duplicate it. ( not soon but will add an option inside Print Designer)
6.  Can you please share more information on this?

**Comment by ramalyb** [comment]
Dear @maharshivpatel ,

Thank you for the swift response and please find below responses against each number.

1. ill try the workaround, but appreciates the fix.🙏 
2. I have tried repeating, but it makes the document complicated, so ill wait for the fix 😊
3. Thanks and noted.
4. I have added the QR code based on my SO number, it appears in the design view as below,

![image](https://github.com/frappe/print_designer/assets/105539575/8956ebf9-df2e-43a0-91f6-2e31c069b068)

but doesn't show when the actual print format is generated.
5. Noted and ill try that too. Thanks.🙏
6. Please find below image, i want to change the alignment of the column area 1 to right, but it changes area 2 texts as well. hope you get it what i m saying now.

![image](https://github.com/frappe/print_designer/assets/105539575/7ec12fab-1142-427b-8686-4792d55a6630)

Thank you,
Ramaly

**Comment by maharshivpatel** [comment]
@ramalyb 
4. have you updated the print designer to the latest version and ran `bench setup requirements` command ?
6. It is intentionally not applying because you can have more than 1 text field in the column but will think about how we can add this.

**Comment by ramalyb** [comment]
@maharshivpatel 

Ill check on latest bench update and please think on matter no: 06 and it will be very useful for a freak like me looking for  perfection in print formats 😂

**Comment by maharshivpatel** [comment]
3. Solved by https://github.com/frappe/print_designer/pull/99

**Comment by ramalyb** [comment]
Hi @maharshivpatel, 
Ran the bench update, but got following error at the end.

![image](https://github.com/frappe/print_designer/assets/105539575/884604ca-2a84-4759-b967-1f0d261b8fd7)

Any idea, 
this is the first time i had done a bench update.

Thank you 
Ramaly

**Comment by maharshivpatel** [comment]
@ramalyb looks like there was a issue with FC.

can you please try again now.

**Comment by ramalyb** [comment]
Hi @maharshivpatel its working now. thank you.
One more suggestion to came to my mind, Can you implement a feature that we can move objects forward and backward ? 

Thank you,
Ramaly

**Comment by maharshivpatel** [comment]
#68 can you share more info on why ?

**Comment by ramalyb** [comment]
Sometimes i add object at later stages, but then need to send it back of some other object. didnt see any options for that, so informed you. but its not a critical thing.

**Comment by maharshivpatel** [comment]
Workaround for No 2 : #107

**Comment by ramalyb** [comment]
Hi @maharshivpatel , Thank you for the update, Found some bugs after the latest update, Terms and conditions is displaying the complete content in the print designer but nothing showing up when open in actual print mode.
static texts doesn't get its styles like font and size and always give same size regardless of settings.

**Comment by maharshivpatel** [comment]
@ramalyb did this behaviour change from before ?

can you share details on them with example of each one with screenshot?

you can also share print format

**Comment by maharshivpatel** [comment]
### if you wish can you share your format like this :
You can paste the data here ( change any personal info ) it will make it really easy to fix the issue

https://github.com/frappe/print_designer/assets/39730881/b7b761c7-a2b1-43d4-a3b3-0dde25ba9699

**Comment by ramalyb** [comment]
@maharshivpatel ill share a video today for sure. it will be more understandable. 
Thanks

**Comment by maharshivpatel** [comment]
@ramalyb please share video whenever you get time so i can fix anything that is broken as soon as possible 😄

**Comment by ramalyb** [comment]
Hi @maharshivpatel sorry for the delay,
1.  Terms and Conditions issue

https://github.com/frappe/print_designer/assets/105539575/bb5f39a8-035e-41a0-9034-4051e6fafb91

2. Static text doesn't get changed when the size changed in edit mode.

https://github.com/frappe/print_designer/assets/105539575/a37cd0ce-a15e-4754-97ba-1d51753b03e9

**Comment by maharshivpatel** [comment]
1. terms and conditions please check if quotation ( document) that you are printing have terms and conditions set

**Comment by ramalyb** [comment]
Hi @maharshivpatel sorry, its my mistake as i was checking an existing RFQ and there were no terms and condition added to it. now Item no 01 is done.
Item 2, ill try it using plain text and advise you.

Thanks

**Comment by ramalyb** [comment]
Hi @maharshivpatel , I have few more issues in the app.
I had some custom fields in the form which i had it in Print format as well. Later i have removed it from Form and now i cannot remove it from print format unless i delete the entire text box. please find below video.


https://github.com/frappe/print_designer/assets/105539575/52a6278e-2fc3-46a7-a759-12fc244dff60

**Comment by maharshivpatel** [comment]
@ramalyb I am able to delete them. can you please update to the latest version and try again.
i would also request you to create/report  each issue separately. that way we can easily track and solve them one by one.

All of the issues are either fixed, have workaround or are already reported.
Thank you. I am closing this issue for now.
