### ISSUE TITLE
Uncaught Server Exception Error Code: 500

### ISSUE THREAD

**Issue by bobotdls** [frappe/print_designer#97]
After fresh install on V15 and successfully install the Print Designer.

I create a Print Designer format for Sales Invoice.

But when I try to print got error message

----------------------------------------
Uncaught Server Exception

Tehre was an error building this page

Home

Error Code: 500

If you don't know what just happened, and wish to file a ticket please
copy the error below and share it.

Show Error
----------------------------------------

The show error is not clickable.. meaning no error show

FYI: 
ERPNext: v15.3.0 (version-15)
Frappe Framework: v15.3.0 (version-15)
Print Designer: v1.0.0 (main)

Now my ERPNext is Production mode

**Comment by maharshivpatel** [comment]
@bobotdls can you share name of your print format so i can create a link where you can see the error.

**Comment by bobotdls** [comment]
SO -Test - BBT

**Comment by maharshivpatel** [comment]
Actually I need more information like site_url and sales order number 😅.  it is just better if you can do it as i have shown in the video.

Basically you replace `Standard` with `SO -Test - BBT` in url of Full Page

https://github.com/frappe/print_designer/assets/39730881/05086ee7-7c5a-4041-841d-20332cb4cfa2

**Comment by bobotdls** [comment]
I think I will give you the admin user. since this installation is just a testing for V15. 

url: 172.104.32.61
Username: administrator
password: IrIsV15@2023+-

**Comment by bobotdls** [comment]
please use the sales invoice module to check the print format

**Comment by maharshivpatel** [comment]
@bobotdls please delete the comment and change the password

**Comment by bobotdls** [comment]
sure thanks
