### ISSUE TITLE
Install print designer in ubuntu, You cannot see the print formats, nor the ErpNext doctypes (Quotation, Sales, etc.)

### ISSUE THREAD

**Issue by madco001** [frappe/print_designer#98]
I installed print designer on Frappe 15 alongside my ERPNex15 and I don't see the Doctypes or the PrintFormat. How do I link them?

**Comment by madco001** [comment]
![Screenshot_20231206_101917](https://github.com/frappe/print_designer/assets/118020503/b50fd787-8496-4796-b279-30d6c0e3760f)

It does not show the formats to edit them...

**Comment by maharshivpatel** [comment]
please make sure it is installed and search print designer on awesomebar

**Comment by madco001** [comment]
@maharshivpatel , 
I have them as independent sites. Is it wrong?

**Comment by maharshivpatel** [comment]
Oh, i understood now. yes that is wrong you need to install app on site that you want to use it.
